FillTypeManager = {}

FillTypeManager.FILLTYPE_START_TOTAL_AMOUNT = 50000.000000
FillTypeManager.SEND_NUM_BITS = 8.000000
FillTypeManager.MASS_SCALE = 0.500000

function FillTypeManager:getFillTypesFromXML() end
function FillTypeManager:new() end
function FillTypeManager:addFillType() end
function FillTypeManager:getFillTypeByIndex() end
function FillTypeManager:getSampleByFillType() end
function FillTypeManager:superClass() end
function FillTypeManager:loadDefaultTypes() end
function FillTypeManager:getFillTypesByNames() end
function FillTypeManager:getConverterDataByName() end
function FillTypeManager:addFillTypeConversion() end
function FillTypeManager:addFillTypeCategory() end
function FillTypeManager:addFillTypeToCategory() end
function FillTypeManager:getFillTypeByName() end
function FillTypeManager:getFillTypeIndexByName() end
function FillTypeManager:unloadMapData() end
function FillTypeManager:getFillTypesByCategoryNames() end
function FillTypeManager:class() end
function FillTypeManager:getFillTypeNameByIndex() end
function FillTypeManager:addFillTypeConverter() end
function FillTypeManager:copy() end
function FillTypeManager:isa() end
function FillTypeManager:loadFillTypes() end
function FillTypeManager:initDataStructures() end
function FillTypeManager:loadMapData() end
function FillTypeManager:getFillTypes() end