FruitTypeManager = {}

FruitTypeManager.GROUND_TYPE_CULTIVATOR = 1.000000
FruitTypeManager.GROUND_TYPE_NONE = 0.000000
FruitTypeManager.SEND_NUM_BITS = 6.000000
FruitTypeManager.GROUND_TYPE_GRASS = 5.000000
FruitTypeManager.GROUND_TYPE_SOWING_WIDTH = 4.000000
FruitTypeManager.GROUND_TYPE_PLOW = 2.000000
FruitTypeManager.GROUND_TYPE_SOWING = 3.000000

function FruitTypeManager:isFillTypeWindrow() end
function FruitTypeManager:loadFruitTypeCultivation() end
function FruitTypeManager:loadFruitTypeMapColors() end
function FruitTypeManager:loadFruitTypeGrowth() end
function FruitTypeManager:addFruitType() end
function FruitTypeManager:loadDefaultTypes() end
function FruitTypeManager:loadFruitTypeDestruction() end
function FruitTypeManager:copy() end
function FruitTypeManager:loadFruitTypeWeedData() end
function FruitTypeManager:getConverterDataByName() end
function FruitTypeManager:getFruitTypes() end
function FruitTypeManager:getFruitTypeByFillTypeIndex() end
function FruitTypeManager:addFruitTypeConversion() end
function FruitTypeManager:addFruitTypeConverter() end
function FruitTypeManager:getFillTypeLiterPerSqm() end
function FruitTypeManager:getWindrowFillTypeIndexByFruitTypeIndex() end
function FruitTypeManager:getFruitTypeIndexByFillTypeIndex() end
function FruitTypeManager:initDataStructures() end
function FruitTypeManager:getFillTypesByFruitTypeCategoryName() end
function FruitTypeManager:getFillTypesByFruitTypeNames() end
function FruitTypeManager:loadFruitTypeGeneral() end
function FruitTypeManager:getFruitTypesByNames() end
function FruitTypeManager:superClass() end
function FruitTypeManager:getFruitTypesByCategoryNames() end
function FruitTypeManager:getFruitTypeByIndex() end
function FruitTypeManager:addFruitTypeCategory() end
function FruitTypeManager:getFruitTypeByName() end
function FruitTypeManager:getFillTypeByFruitTypeIndex() end
function FruitTypeManager:getFruitTypeNameByIndex() end
function FruitTypeManager:getFillTypeIndexByFruitTypeIndex() end
function FruitTypeManager:new() end
function FruitTypeManager:class() end
function FruitTypeManager:getWeedFruitType() end
function FruitTypeManager:isa() end
function FruitTypeManager:loadFruitTypeOptions() end
function FruitTypeManager:loadFruitTypeWindrow() end
function FruitTypeManager:loadFruitTypePreparing() end
function FruitTypeManager:loadFruitTypes() end
function FruitTypeManager:loadFruitTypeHarvest() end
function FruitTypeManager:addFruitTypeToCategory() end
function FruitTypeManager:loadMapData() end