FruitTypeManager = {
  fillTypeIndexToFruitTypeIndex = {},
  fruitTypeIndexToWindrowFillTypeIndex = {},
  numCategories = 0,
  indexToFruitType = {},
  fruitTypes = {},
  nameToIndex = {},
  categoryToFruitTypes = {},
  weedFruitType = {},
  fruitTypeIndexToFillType = {},
  converterNameToIndex = {},
  indexToCategory = {},
  categories = {},
  windrowFillTypes = {},
  nameToConverter = {},
  loadedMapData = false,
  fruitTypeConverters = {},
  nameToFruitType = {}
}

-- fruitType table property types
-- g_fruitTypeManager.fruitTypes
fruitType = {
  groundTypeChangeGrowthState = 0,
  destroyedByRoller = false,
  useForFieldJob = false,
  alignsToSun = false,
  shownOnMap = false,
  groundTypeChangeMask = 0,
  needsSeeding = false,
  directionSnapAngle = 0,
  minHarvestingGrowthState = 0,
  minForageGrowthState = 0,
  witheringNumGrowthStates = 0,
  literPerSqm = 0.0,
  minPreparingGrowthState = 0,
  startSprayState = 0,
  allowsPartialGrowthState = false,
  allowsSeeding = false,
  numStateChannels = 0,
  regrows = false,
  numGrowthStates = 0,
  windrowLiterPerSqm = 0,
  destruction = {},
  startStateChannel = 0,
  fillType = {},
  lowSoilDensityRequired = false,
  plantsWeed = false,
  increasesSoilDensity = false,
  preparedGrowthState = 0,
  missionMultiplier = 0,
  maxPreparingGrowthState = 0,
  consumesLime = false,
  resetsSpray = false,
  seedUsagePerSqm = 0.0,
  name = '',
  windrowName = '',
  hasWindrow = false,
  index = 0,
  groundTypeChanged = 0,
  useSeedingWidth = false,
  growthRequiresLime = false,
  maxHarvestingGrowthState = 6,
  defaultMapColor = {},
  growthStateTime = 0,
  colorBlindMapColor = {},
  layerName = '',
  cutState = 8
}

FruitTypeManager.GROUND_TYPE_CULTIVATOR = 1.000000
FruitTypeManager.GROUND_TYPE_NONE = 0.000000
FruitTypeManager.SEND_NUM_BITS = 6.000000
FruitTypeManager.GROUND_TYPE_GRASS = 5.000000
FruitTypeManager.GROUND_TYPE_SOWING_WIDTH = 4.000000
FruitTypeManager.GROUND_TYPE_PLOW = 2.000000
FruitTypeManager.GROUND_TYPE_SOWING = 3.000000

function FruitTypeManager:isFillTypeWindrow() end
function FruitTypeManager:loadFruitTypeCultivation() end
function FruitTypeManager:loadFruitTypeMapColors() end
function FruitTypeManager:loadFruitTypeGrowth() end
function FruitTypeManager:addFruitType() end
function FruitTypeManager:loadDefaultTypes() end
function FruitTypeManager:loadFruitTypeDestruction() end
function FruitTypeManager:copy() end
function FruitTypeManager:loadFruitTypeWeedData() end
function FruitTypeManager:getConverterDataByName() end
function FruitTypeManager:getFruitTypes() end
function FruitTypeManager:getFruitTypeByFillTypeIndex() end
function FruitTypeManager:addFruitTypeConversion() end
function FruitTypeManager:addFruitTypeConverter() end
function FruitTypeManager:getFillTypeLiterPerSqm() end
function FruitTypeManager:getWindrowFillTypeIndexByFruitTypeIndex() end
function FruitTypeManager:getFruitTypeIndexByFillTypeIndex() end
function FruitTypeManager:initDataStructures() end
function FruitTypeManager:getFillTypesByFruitTypeCategoryName() end
function FruitTypeManager:getFillTypesByFruitTypeNames() end
function FruitTypeManager:loadFruitTypeGeneral() end
function FruitTypeManager:getFruitTypesByNames() end
function FruitTypeManager:superClass() end
function FruitTypeManager:getFruitTypesByCategoryNames() end
function FruitTypeManager:getFruitTypeByIndex() end
function FruitTypeManager:addFruitTypeCategory() end
function FruitTypeManager:getFruitTypeByName() end
function FruitTypeManager:getFillTypeByFruitTypeIndex() end
function FruitTypeManager:getFruitTypeNameByIndex() end
function FruitTypeManager:getFillTypeIndexByFruitTypeIndex() end
function FruitTypeManager:new() end
function FruitTypeManager:class() end
function FruitTypeManager:getWeedFruitType() end
function FruitTypeManager:isa() end
function FruitTypeManager:loadFruitTypeOptions() end
function FruitTypeManager:loadFruitTypeWindrow() end
function FruitTypeManager:loadFruitTypePreparing() end
function FruitTypeManager:loadFruitTypes() end
function FruitTypeManager:loadFruitTypeHarvest() end
function FruitTypeManager:addFruitTypeToCategory() end
function FruitTypeManager:loadMapData() end