LogManager = {}

function LogManager:new() end
function LogManager:isa() end
function LogManager:error() end
function LogManager:superClass() end
function LogManager:devWarning() end
function LogManager:devInfo() end
function LogManager:info() end
function LogManager:copy() end
function LogManager:xmlInfo() end
function LogManager:class() end
function LogManager:xmlWarning() end
function LogManager:xmlDevError() end
function LogManager:xmlDevWarning() end
function LogManager:devError() end
function LogManager:xmlDevInfo() end
function LogManager:xmlError() end
function LogManager:warning() end