DebugUtil = {}

function DebugUtil:drawDebugNode() end
function DebugUtil:printNodeHierarchy() end
function DebugUtil:drawDebugRectangle() end
function DebugUtil:drawDebugReferenceAxisFromNode() end
function DebugUtil:renderTable() end
function DebugUtil:drawDebugGizmoAtWorldPos() end
function DebugUtil:drawSimpleDebugCube() end
function DebugUtil:drawDebugCube() end
function DebugUtil:drawDebugParallelogram() end
function DebugUtil:drawDebugArea() end
function DebugUtil:printCallingFunctionLocation() end
function DebugUtil:drawDebugAreaRectangle() end
function DebugUtil:drawDebugCubeAtWorldPos() end
function DebugUtil:drawArea() end
function DebugUtil:drawOverlapBox() end
function DebugUtil:drawDebugReferenceAxis() end
function DebugUtil:printTableRecursively() end
function DebugUtil:drawDebugCircle() end
function DebugUtil:debugTableToString() end