InputHelpElement = {}

InputHelpElement.SEPARATOR = {
    COMBO_INPUT = 2.000000
    NONE = 1.000000
    ANY_INPUT = 3.000000
}

InputHelpElement.AXIS_ICON = {
    PIPE_ROTATE_Y = 'PIPE_ROTATE_Y'
    CRANE_ARM1_ROTATE_Y = 'CRANE_ARM1_ROTATE_Y'
    GRABBER_ROTATE_Y = 'GRABBER_ROTATE_Y'
    CRANE_ARM1_ROTATE_X = 'CRANE_ARM1_ROTATE_X'
    REEL_TRANSLATE_Y = 'REEL_TRANSLATE_Y'
    IMPLEMENT_ATTACHER_ROTX = 'IMPLEMENT_ATTACHER_ROTX'
    GRABBER_OPEN_CLOSE = 'GRABBER_OPEN_CLOSE'
    FRONTLOADER_ARM_ROTATE = 'FRONTLOADER_ARM_ROTATE'
    FRONTLOADER_ARM_ROTATE_TOOL = 'FRONTLOADER_ARM_ROTATE_TOOL'
    REEL_TRANSLATE_X = 'REEL_TRANSLATE_X'
    WORKING_WIDTH_TRANSLATE_X = 'WORKING_WIDTH_TRANSLATE_X'
    SUPPORT_ARM_TRANSLATE_Y = 'SUPPORT_ARM_TRANSLATE_Y'
    WHEEL_BASE_TRANSLATE_X = 'WHEEL_BASE_TRANSLATE_X'
    CRANE_ARM1_TRANSLATE = 'CRANE_ARM1_TRANSLATE'
    SPRAYER_ARM_TRANSLATE_Y = 'SPRAYER_ARM_TRANSLATE_Y'
    TOP_DOOR_ROTATE = 'TOP_DOOR_ROTATE'
    IMPLEMENT_ATTACHER_TRANS = 'IMPLEMENT_ATTACHER_TRANS'
    TOOL_OPEN_CLOSE = 'TOOL_OPEN_CLOSE'
    DRAWBAR_ROTATE_X = 'DRAWBAR_ROTATE_X'
    CRANE_ARM2_TRANSLATE = 'CRANE_ARM2_TRANSLATE'
    PIPE_END_ROTATE = 'PIPE_END_ROTATE'
    CRANE_ARM2_ROTATE_X = 'CRANE_ARM2_ROTATE_X'
    CRANE_ARM2_ROTATE_TOOL = 'CRANE_ARM2_ROTATE_TOOL'
}
InputHelpElement.NO_DATA = {}

function InputHelpElement:copy() end
function InputHelpElement:isa() end
function InputHelpElement:class() end
function InputHelpElement:getActionNames() end
function InputHelpElement:superClass() end
function InputHelpElement:new() end