FSBaseMission = {}

FSBaseMission.INGAME_NOTIFICATION_OK = {
    1 = 0.097600
    2 = 0.624000
    3 = 0.000000
    4 = 1.000000
}
FSBaseMission.DEBUG_SHOW_FIELDSTATUS_SIZE = 5.000000
FSBaseMission.USER_STATE_SYNCHRONIZING = 2.000000
FSBaseMission.INGAME_NOTIFICATION_CRITICAL = {
    1 = 0.930100
    2 = 0.287400
    3 = 0.013000
    4 = 1.000000
}
FSBaseMission.USER_STATE_LOADING = 1.000000
FSBaseMission.RADIO_ALWAYS = 3.000000
FSBaseMission.USER_STATE_CONNECTED = 3.000000
FSBaseMission.INGAME_NOTIFICATION_GREATDEMAND = {
    1 = 1.000000
    2 = 1.000000
    3 = 1.000000
    4 = 1.000000
}
FSBaseMission.USER_STATE_INGAME = 4.000000
FSBaseMission.INGAME_NOTIFICATION_INFO = {
    1 = 1.000000
    2 = 1.000000
    3 = 1.000000
    4 = 1.000000
}
FSBaseMission.LIMITED_OBJECT_TYPE_BALE = 1.000000
FSBaseMission.CONNECTION_LOST_BANNED = 2.000000
FSBaseMission.RADIO_OFF = 1.000000
FSBaseMission.DEBUG_SHOW_FIELDSTATUS = false
FSBaseMission.CONNECTION_LOST_DEFAULT = 0.000000
FSBaseMission.RADIO_VEHICLE_ONLY = 2.000000
FSBaseMission.CONNECTION_LOST_KICKED = 1.000000

function FSBaseMission:onStartMission() end
function FSBaseMission:onUserAdded() end
function FSBaseMission:getDefaultServerName() end
function FSBaseMission:saveSavegame() end
function FSBaseMission:consoleCommandShowTipCollisions() end
function FSBaseMission:getFruitTypeGroundTypeValue() end
function FSBaseMission:onUserRemoved() end
function FSBaseMission:kickUser() end
function FSBaseMission:showFuelContext() end
function FSBaseMission:subscribeMessages() end
function FSBaseMission:onSoundPlayerChange() end
function FSBaseMission:getHasPlayerPermission() end
function FSBaseMission:setHelperBuyFertilizer() end
function FSBaseMission:onRadioVehicleOnlyChanged() end
function FSBaseMission:onSplitShapesProgress() end
function FSBaseMission:getMoney() end
function FSBaseMission:onShowHelpIconsChanged() end
function FSBaseMission:onChangeTimescale() end
function FSBaseMission:getAllowsGuiDisplay() end
function FSBaseMission:copy() end
function FSBaseMission:onSoundPlayerStreamAccess() end
function FSBaseMission:showMoneyChange() end
function FSBaseMission:toggleChat() end
function FSBaseMission:showAttachContext() end
function FSBaseMission:consoleCommandAddAnimal() end
function FSBaseMission:addTrainSystem() end
function FSBaseMission:onToggleMenu() end
function FSBaseMission:getIsRadioPlaying() end
function FSBaseMission:registerActionEvents() end
function FSBaseMission:registerPauseActionEvents() end
function FSBaseMission:consoleCommandAddPallet() end
function FSBaseMission:removeMapHotspot() end
function FSBaseMission:removeManureHeap() end
function FSBaseMission:addLeasedItem() end
function FSBaseMission:setLoadingScreen() end
function FSBaseMission:addMapHotspot() end
function FSBaseMission:onEndMissionCallback() end
function FSBaseMission:playerOwnsAllFields() end
function FSBaseMission:doPauseGame() end
function FSBaseMission:onRadioIsActiveChanged() end
function FSBaseMission:removeKnownSplitShape() end
function FSBaseMission:onConnectionFinishedLoading() end
function FSBaseMission:setPlayerPermission() end
function FSBaseMission:getCanAddLimitedObject() end
function FSBaseMission:updateDedicatedServerXML() end
function FSBaseMission:onMeshEvent() end
function FSBaseMission:onConnectionPacketLost() end
function FSBaseMission:consoleCommandLoadTree() end
function FSBaseMission:onConnectionWriteUpdateStream() end
function FSBaseMission:updateMissionDynamicInfo() end
function FSBaseMission:removeLoadingStation() end
function FSBaseMission:consoleCommandExportStoreItems() end
function FSBaseMission:showTipContext() end
function FSBaseMission:broadcastEventToFarm() end
function FSBaseMission:addPlaceableToDelete() end
function FSBaseMission:removeAllHelpIcons() end
function FSBaseMission:load() end
function FSBaseMission:updateFoundHelpIcons() end
function FSBaseMission:onStreamAccessAllowed() end
function FSBaseMission:onConnectionClosed() end
function FSBaseMission:consoleCommandAddDirtAmount() end
function FSBaseMission:consoleCommandToggleDebugFieldStatus() end
function FSBaseMission:onLeaveVehicle() end
function FSBaseMission:consoleCommandRemoveAnimal() end
function FSBaseMission:getServerUserId() end
function FSBaseMission:onToggleStore() end
function FSBaseMission:new() end
function FSBaseMission:updatePauseInputContext() end
function FSBaseMission:removeVehicle() end
function FSBaseMission:setSavegameName() end
function FSBaseMission:consoleActivateCameraPath() end
function FSBaseMission:delete() end
function FSBaseMission:isInGameMessageActive() end
function FSBaseMission:onShutdownEventOk() end
function FSBaseMission:consoleCommandAddBale() end
function FSBaseMission:consoleCommandUpdateTipCollisions() end
function FSBaseMission:addLoadingStation() end
function FSBaseMission:consoleCommandShowPlacementCollisions() end
function FSBaseMission:removeOwnedItem() end
function FSBaseMission:onConnectionPacketSent() end
function FSBaseMission:loadFoliageLayer() end
function FSBaseMission:consoleCommandShowVehicleDistance() end
function FSBaseMission:registerHusbandry() end
function FSBaseMission:onFinishedReceivingDynamicData() end
function FSBaseMission:addStorageToUnloadingStations() end
function FSBaseMission:onConnectionDenyAccept() end
function FSBaseMission:broadcastEventToMasterUser() end
function FSBaseMission:consoleCommandSetOperatingTime() end
function FSBaseMission:update() end
function FSBaseMission:updateGameStatsXML() end
function FSBaseMission:setPlantGrowthRateLocked() end
function FSBaseMission:onYesNoSavegameOverwrite() end
function FSBaseMission:consoleCommandReloadVehicle() end
function FSBaseMission:setAutomaticMotorStartEnabled() end
function FSBaseMission:consoleCommandCheatMoney() end
function FSBaseMission:getManureHeapInfo() end
function FSBaseMission:setPlantWitheringEnabled() end
function FSBaseMission:consoleCommandLoadAllVehicles() end
function FSBaseMission:consoleCommandAddWearAmount() end
function FSBaseMission:getFoliageGrowthStateTimeMultiplier() end
function FSBaseMission:getCanAcceptPlayers() end
function FSBaseMission:initTerrain() end
function FSBaseMission:consoleCommandTeleport() end
function FSBaseMission:updateMasterServerInfo() end
function FSBaseMission:notifyPlayerFarmChanged() end
function FSBaseMission:setLimeRequired() end
function FSBaseMission:removeStorageFromLoadingStations() end
function FSBaseMission:addMoney() end
function FSBaseMission:addLimitedObject() end
function FSBaseMission:getFruitPixelsToSqm() end
function FSBaseMission:consoleCommandFillUnitAdd() end
function FSBaseMission:addIngameNotification() end
function FSBaseMission:consoleCommandCheatSilo() end
function FSBaseMission:consoleStartGreatDemand() end
function FSBaseMission:keyEvent() end
function FSBaseMission:addManureHeap() end
function FSBaseMission:broadcastMissionDynamicInfo() end
function FSBaseMission:getFarmSiloCapacity() end
function FSBaseMission:updatePlantWithering() end
function FSBaseMission:onToggleRadio() end
function FSBaseMission:addVehicle() end
function FSBaseMission:removeStorage() end
function FSBaseMission:setWeedsEnabled() end
function FSBaseMission:addStorageToLoadingStations() end
function FSBaseMission:setEnvironmentVolume() end
function FSBaseMission:setVehicleVolume() end
function FSBaseMission:setRadioVolume() end
function FSBaseMission:consoleCommandSaveDediXMLStatsFile() end
function FSBaseMission:setRadioActionEventsState() end
function FSBaseMission:onYesNoSavegameSelectDevice() end
function FSBaseMission:playRadio() end
function FSBaseMission:pauseRadio() end
function FSBaseMission:addOnCreateLoadedObject() end
function FSBaseMission:updateMaxNumHirables() end
function FSBaseMission:getHusbandries() end
function FSBaseMission:getHusbandryByAnimalType() end
function FSBaseMission:unregisterHusbandry() end
function FSBaseMission:getIngameMap() end
function FSBaseMission:addLiquidManureFillTrigger() end
function FSBaseMission:onDayChanged() end
function FSBaseMission:startSaveCurrentGame() end
function FSBaseMission:onHourChanged() end
function FSBaseMission:getDoghouse() end
function FSBaseMission:onConnectionRequestAnswerOk() end
function FSBaseMission:removeLimitedObject() end
function FSBaseMission:removeTrainSystem() end
function FSBaseMission:setVisibilityOfGUIComponents() end
function FSBaseMission:hasStorage() end
function FSBaseMission:updatePlantRegrowth() end
function FSBaseMission:setHelperSlurrySource() end
function FSBaseMission:setAutoSaveInterval() end
function FSBaseMission:setMoneyUnit() end
function FSBaseMission:setHelperManureSource() end
function FSBaseMission:isa() end
function FSBaseMission:setHelperBuySeeds() end
function FSBaseMission:getTerrainDetailPixelsToSqm() end
function FSBaseMission:draw() end
function FSBaseMission:setTutorialProgress() end
function FSBaseMission:setHelperBuyFuel() end
function FSBaseMission:addStorage() end
function FSBaseMission:consoleCommandListHusbandries() end
function FSBaseMission:setTrafficEnabled() end
function FSBaseMission:removeVehicleChangeListener() end
function FSBaseMission:setStopAndGoBraking() end
function FSBaseMission:consoleCommandTipFillType() end
function FSBaseMission:cancelPlayersSynchronizing() end
function FSBaseMission:getClientPosition() end
function FSBaseMission:mouseEvent() end
function FSBaseMission:class() end
function FSBaseMission:onShutdownEvent() end
function FSBaseMission:setFruitDestructionEnabled() end
function FSBaseMission:updateFoliageGrowthStateTime() end
function FSBaseMission:updateSaving() end
function FSBaseMission:addVehicleChangeListener() end
function FSBaseMission:setDirtInterval() end
function FSBaseMission:loadMap() end
function FSBaseMission:onFinishedLoading() end
function FSBaseMission:addOwnedItem() end
function FSBaseMission:removeStorageFromUnloadingStations() end
function FSBaseMission:setPlantGrowthRate() end
function FSBaseMission:loadMapFinished() end
function FSBaseMission:setTimeScale() end
function FSBaseMission:canUnpauseGame() end
function FSBaseMission:doUnpauseGame() end
function FSBaseMission:sendNumPlayersToMasterServer() end
function FSBaseMission:initialize() end
function FSBaseMission:configureMesh() end
function FSBaseMission:setPlayerPermissions() end
function FSBaseMission:showFillDogBowlContext() end
function FSBaseMission:onConnectionRequestAcceptedLoad() end
function FSBaseMission:setConnectionLostState() end
function FSBaseMission:addMoneyChange() end
function FSBaseMission:onEnterVehicle() end
function FSBaseMission:addUnloadingStation() end
function FSBaseMission:drawMissionFailed() end
function FSBaseMission:onSaveGameUpdateComplete() end
function FSBaseMission:consoleCommandSetMotorTemperature() end
function FSBaseMission:setMissionInfo() end
function FSBaseMission:setHarvestScaleRatio() end
function FSBaseMission:getPlayerByConnection() end
function FSBaseMission:getFarmId() end
function FSBaseMission:setPlowingRequiredEnabled() end
function FSBaseMission:getHarvestScaleMultiplier() end
function FSBaseMission:onMinuteChanged() end
function FSBaseMission:addVehicleHotspot() end
function FSBaseMission:setGUIVolume() end
function FSBaseMission:getVehicleName() end
function FSBaseMission:onMasterUserAdded() end
function FSBaseMission:banUser() end
function FSBaseMission:getSynchronizingPercentage() end
function FSBaseMission:createPlayer() end
function FSBaseMission:updateMenuAccessibleVehicles() end
function FSBaseMission:superClass() end
function FSBaseMission:farmStats() end
function FSBaseMission:removeLeasedItem() end
function FSBaseMission:onConnectionReadUpdateStream() end
function FSBaseMission:onConnectionRequest() end
function FSBaseMission:onConnectionRequestAnswer() end
function FSBaseMission:removeUnloadingStation() end
function FSBaseMission:registerToLoadOnMapFinished() end
function FSBaseMission:broadcastNotifications() end
function FSBaseMission:onConnectionOpened() end
function FSBaseMission:addGroundValueId() end
function FSBaseMission:onMasterServerConnectionFailed() end
function FSBaseMission:setFuelUsageLow() end
function FSBaseMission:drawMissionCompleted() end
function FSBaseMission:onConnectionReady() end
function FSBaseMission:addKnownSplitShape() end
function FSBaseMission:getStorageTargetsInRange() end
function FSBaseMission:onConnectionRequestAccepted() end
function FSBaseMission:onFinishedClientsWriteUpdateStream() end
function FSBaseMission:consoleCommandSetFuel() end
function FSBaseMission:consoleCommandFillVehicle() end
function FSBaseMission:onConnectionsUpdateTick() end
function FSBaseMission:showPauseDisplay() end
function FSBaseMission:consoleCommandClearTipArea() end
function FSBaseMission:onConnectionAccepted() end
function FSBaseMission:getIsAutoSaveSupported() end
function FSBaseMission:setTrainSystemTabbable() end