g_currentMission = {}

g_currentMission.fillTypeManager = {} -- lookup: g_currentMission/fillTypeManager.lua
g_currentMission.fruitTypeManager = {} -- lookup: g_currentMission/fruitTypeManager.lua
g_currentMission.modManager = {} -- lookup: g_currentMission/modManager.lua
g_currentMission.userManager = {} -- lookup: g_currentMission/userManager.lua

g_currentMission.landscapingController = {} -- lookup: g_currentMission/landscapingController.lua
g_currentMission.environment = {} -- lookup: g_currentMission/environment.lua

g_currentMission.fieldCropsUpdatersCellSize = 16
g_currentMission.terrainDetailTypeFirstChannel = 0
g_currentMission.limeCounterFirstChannel = 11
g_currentMission.slotUsage = 0
g_currentMission.sendMoneyUserIndex = 1
g_currentMission.cultivatorValue = 1
g_currentMission.mountThreshold = 6
g_currentMission.numFruitDensityMapChannels = 10
g_currentMission.grassValue = 5
g_currentMission.storeIsActive = false
g_currentMission.cameraPathIsPlaying = false
g_currentMission.plowCounterFirstChannel = 10
g_currentMission.waitForCorruptDlcs = false
g_currentMission.manualPaused = false
g_currentMission.plowCounterMaxValue = 1
g_currentMission.terrainDetailId = 0
g_currentMission.mapSplitShapesRevision = 1
g_currentMission.lastSowableValue = 2
g_currentMission.sowingValue = 3
g_currentMission.mapWidth = 2048
g_currentMission.isToggleVehicleAllowed = true
g_currentMission.mapTerrainLodTextureRevision = 1
g_currentMission.terrainDetailAngleMaxValue = 3
g_currentMission.mapImageFilename = 'data/maps/mapUS/pda_map_H.png'
g_currentMission.xmlFile = 14471
g_currentMission.isPlayerFrozen = false
g_currentMission.controlPlayer = true
g_currentMission.disableCombineAI = false
g_currentMission.waterY = 22.5
g_currentMission.sprayMaxValue = 7
g_currentMission.gameStarted = false
g_currentMission.numLoadingMaps = 0
g_currentMission.isSaving = false
g_currentMission.gameStatsTime = 60000
g_currentMission.currentDeviceHasNoSpace = false
g_currentMission.snapAIDirection = true
g_currentMission.gameStatsInterval = 60000
g_currentMission.sprayLevelMaxValue = 2
g_currentMission.terrainDetailAngleFirstChannel = 6
g_currentMission.endTimeStamp = 0
g_currentMission.chatMessagesHistoryNum = 50
g_currentMission.renderTime = true
g_currentMission.plowValue = 2
g_currentMission.masterUserCount = 0
g_currentMission.preSimulateTime = 4000
g_currentMission.eventRadioToggle = ''
g_currentMission.splitShapesPercentageFraction = 0.2
g_currentMission.connectedToDedicatedServer = false
g_currentMission.textureMemoryUsage = 884448704
g_currentMission.isLoaded = false
g_currentMission.placeablesDeleteTestTime = 0
g_currentMission.cullingWorldXZOffset = 600
g_currentMission.time = 0
g_currentMission.lastSowingValue = 5
g_currentMission.playerUserId = 1
g_currentMission.mapTipCollisionRevision = 1
g_currentMission.limeCounterMaxValue = 3
g_currentMission.missionTime = 0
g_currentMission.eventActivateObject = ''
g_currentMission.terrainSize = 1
g_currentMission.numLoadingTasks = 1
g_currentMission.isAppSuspended = false
g_currentMission.numOnCreateLoadedObjectsToSave = 0
g_currentMission.state = 0
g_currentMission.tipTriggerRangeThreshold = 1
g_currentMission.wasNetworkError = false
g_currentMission.densityMapPercentageFraction = 0.7
g_currentMission.sowingWidthValue = 4
g_currentMission.fieldCropsAllowGrowing = true
g_currentMission.indexBufferMemoryUsage = 15013438
g_currentMission.sprayNumChannels = 3
g_currentMission.cullingWorldMinY = -100
g_currentMission.terrainDetailHeightTypeNumChannels = 5
g_currentMission.isInsideBuilding = false
g_currentMission.vertexBufferMemoryUsage = 115264720
g_currentMission.firstTimeRun = false
g_currentMission.fruitMapSize = 1
g_currentMission.terrainDetailMapSize = 1
g_currentMission.baseDirectory = ''
g_currentMission.meshEnabled = false
g_currentMission.densityMapSyncerCellSize = 32
g_currentMission.meshActive = false
g_currentMission.isSynchronizingWithPlayers = false
g_currentMission.disableTractorAI = false
g_currentMission.paused = false
g_currentMission.playerStartIsAbsolute = false
g_currentMission.isExitingGame = false
g_currentMission.cullingWorldMaxY = 500
g_currentMission.restPercentageFraction = 0.1
g_currentMission.firstSowableValue = 1
g_currentMission.limeCounterNumChannels = 2
g_currentMission.sprayLevelNumChannels = 2
g_currentMission.sprayLevelFirstChannel = 8
g_currentMission.mapHeight = 2048
g_currentMission.terrainDetailAngleNumChannels = 2
g_currentMission.terrainDetailTypeNumChannels = 3
g_currentMission.loadingMapBaseDirectory = ''
g_currentMission.isTutorialMission = false
g_currentMission.doSaveGameState = 0
g_currentMission.siloTriggers = {} -- todo (?)
g_currentMission.isTipTriggerInRange = false
g_currentMission.lastNonPauseGameState = 5
g_currentMission.physicsPaused = false
g_currentMission.connectionWasClosed = false
g_currentMission.endDelayTime = 5000
g_currentMission.plowCounterNumChannels = 1
g_currentMission.sprayFirstChannel = 3
g_currentMission.maxNumHirables = 10
g_currentMission.waitForDLCVerification = false
g_currentMission.isLoadingMap = false
g_currentMission.terrainDetailHeightTypeFirstChannel = 0
g_currentMission.firstSowingValue = 3
g_currentMission.isMissionStarted = false
g_currentMission.isMasterUser = true
g_currentMission.cancelLoading = false
g_currentMission.connectionWasAccepted = true
g_currentMission.mapDensityMapRevision = 1
g_currentMission.isRunning = false
g_currentMission.lastInteractionTime = -1
g_currentMission.mapPlacementCollisionRevision = 1
g_currentMission.chopperGroundLayerType = 5

g_currentMission.cameraPaths = {} -- todo (?)
g_currentMission.nodeToObject = {} -- todo (?)
g_currentMission.objectToRailroadVehicle = {} -- todo (?)
g_currentMission.loadingConnection = {} -- todo (?)
g_currentMission.loadSpawnPlaces = {} -- todo (?)
g_currentMission.ownedItems = {} -- todo (?)
g_currentMission.inGameMenu = {} -- todo (?)
g_currentMission.messages = {} -- todo (?)
g_currentMission.usedLoadPlaces = {} -- todo (?)
g_currentMission.fieldCropsUpdaters = {} -- todo (?)
g_currentMission.trailerTipTriggers = {} -- todo (?)
g_currentMission.missionDynamicInfo = {} -- todo (?)
g_currentMission.nonUpdateables = {} -- todo (?)
g_currentMission.objectsToCallOnMissionStarted = {} -- todo (?)
g_currentMission.attachables = {} -- todo (?)
g_currentMission.restrictedZones = {} -- todo (?)
g_currentMission.pedestrianSystem = {} -- todo (?)
g_currentMission.limitedObjects = {} -- todo (?)
g_currentMission.shopController = {} -- todo (?)
g_currentMission.trafficSystem = {} -- todo (?)
g_currentMission.inputDisplayManager = {} -- todo (?)
g_currentMission.mapsSplitShapeFileIds = {} -- todo (?)
g_currentMission.objectsToCallOnMapFinished = {} -- todo (?)
g_currentMission.missionInfo = {} -- todo (?)
g_currentMission.itemsToSave = {} -- todo (?)
g_currentMission.loadingScreen = {} -- todo (?)
g_currentMission.shopMenu = {} -- todo (?)
g_currentMission.liquidManureTriggerMapping = {} -- todo (?)
g_currentMission.animalController = {} -- todo (?)
g_currentMission.loadingStations = {} -- todo (?)
g_currentMission.foliageBendingSystem = {} -- todo (?)
g_currentMission.pauseListeners = {} -- todo (?)
g_currentMission.groundValueIds = {} -- todo (?)
g_currentMission.mapHotspots = {} -- todo (?)
g_currentMission.loadFinishedListeners = {} -- todo (?)
g_currentMission.interactiveVehicles = {} -- todo (?)
g_currentMission.dynamicFoliageLayers = {} -- todo (?)
g_currentMission.mesh = {} -- todo (?)
g_currentMission.leasedVehicles = {} -- todo (?)
g_currentMission.achievementManager = {} -- todo (?)
g_currentMission.chatMessages = {} -- todo (?)
g_currentMission.triggerMarkers = {} -- todo (?)
g_currentMission.enterables = {} -- todo (?)
g_currentMission.tourIconsBase = {} -- todo (?)
g_currentMission.inputManager = {} -- todo (?)
g_currentMission.tipTriggers = {} -- todo (?)
g_currentMission.radioEvents = {} -- todo (?)
g_currentMission.server = {} -- todo (?)
g_currentMission.masterUsers = {} -- todo (?)
g_currentMission.onCreateLoadedObjectsToSaveByIndex = {} -- todo (?)
g_currentMission.vehicleChangeListeners = {} -- todo (?)
g_currentMission.client = {} -- todo (?)
g_currentMission.fruitsList = {} -- todo (?)
g_currentMission.manureHeaps = {} -- todo (?)
g_currentMission.accessHandler = {} -- todo (?)
g_currentMission.liquidManureTriggers = {} -- todo (?)
g_currentMission.doghouses = {} -- todo (?)
g_currentMission.husbandries = {} -- todo (?)
g_currentMission.controlledVehicles = {} -- todo (?)
g_currentMission.hud = {} -- todo (?)
g_currentMission.vehicles = {} -- todo (?)
g_currentMission.densityHeightMapModifiers = {} -- todo (?)
g_currentMission.moneyChanges = {} -- todo (?)
g_currentMission.dynamicallyLoadedObjects = {} -- todo (?)
g_currentMission.boughtVehiclesToLoad = {} -- todo (?)
g_currentMission.guiTopDownCamera = {} -- todo (?)
g_currentMission.onCreateLoadedObjects = {} -- todo (?)
g_currentMission.placeablesToDelete = {} -- todo (?)
g_currentMission.surfaceSounds = {} -- todo (?)
g_currentMission.activatableObjects = {} -- todo (?)
g_currentMission.placeholdersObject = {} -- todo (?)
g_currentMission.bans = {} -- todo (?)
g_currentMission.blockedIps = {} -- todo (?)
g_currentMission.onCreateLoadedObjectsToSave = {} -- todo (?)
g_currentMission.playersSynchronizing = {} -- todo (?)
g_currentMission.maps = {} -- todo (?)
g_currentMission.fruits = {} -- todo (?)
g_currentMission.playersLoading = {} -- todo (?)
g_currentMission.guiSoundPlayer = {} -- todo (?)
g_currentMission.densityMapModifiers = {} -- todo (?)
g_currentMission.unloadingStations = {} -- todo (?)
g_currentMission.storages = {} -- todo (?)
g_currentMission.messageCenter = {} -- todo (?)
g_currentMission.vehiclesToDelete = {} -- todo (?)
g_currentMission.activateListeners = {} -- todo (?)
g_currentMission.cuttingSounds = {} -- todo (?)
g_currentMission.usedStorePlaces = {} -- todo (?)
g_currentMission.vehiclesToSpawn = {} -- todo (?)
g_currentMission.players = {} -- todo (?)
g_currentMission.objectsToClassName = {} -- todo (?)
g_currentMission.playersToAccept = {} -- todo (?)
g_currentMission.mapPerformanceTestUtil = {} -- todo (?)
g_currentMission.trainSystems = {} -- todo (?)
g_currentMission.placeables = {} -- todo (?)
g_currentMission.vehiclesToAttach = {} -- todo (?)
g_currentMission.savegameController = {} -- todo (?)
g_currentMission.storeSpawnPlaces = {} -- todo (?)
g_currentMission.updateables = {} -- todo (?)
g_currentMission.placementController = {} -- todo (?)
g_currentMission.connectionsToPlayer = {} -- todo (?)
g_currentMission.tourVehicles = {} -- todo (?)