-- lookup: misc/FruitTypeManager.lua
g_fruitTypeManager = {}

g_fruitTypeManager.fillTypeIndexToFruitTypeIndex = {}
g_fruitTypeManager.fruitTypeIndexToWindrowFillTypeIndex = {}
g_fruitTypeManager.numCategories = 9
g_fruitTypeManager.indexToFruitType = {}
g_fruitTypeManager.fruitTypes = {}
g_fruitTypeManager.nameToIndex = {}
g_fruitTypeManager.categoryToFruitTypes = {}
g_fruitTypeManager.weedFruitType = {}
g_fruitTypeManager.fruitTypeIndexToFillType = {}
g_fruitTypeManager.converterNameToIndex = {}
g_fruitTypeManager.indexToCategory = {}
g_fruitTypeManager.categories = {}
g_fruitTypeManager.windrowFillTypes = {}
g_fruitTypeManager.nameToConverter = {}
g_fruitTypeManager.loadedMapData = true
g_fruitTypeManager.fruitTypeConverters = {}
g_fruitTypeManager.nameToFruitType = {}