GameSettings = {}

GameSettings.SETTING = {
    USE_COLORBLIND_MODE = "useColorblindMode",
    PLAYER_HAIR_INDEX = "playerHairIndex",
    MP_LANGUAGE = "mpLanguage",
    SHOW_FIELD_INFO = "showFieldInfo",
    SHOW_HELP_ICONS = "showHelpIcons",
    VOLUME_MASTER = "masterVolume",
    RADIO_IS_ACTIVE = "radioIsActive",
    PLAYER_ACCESSORY_INDEX = "playerAccessoryIndex",
    RESET_CAMERA = "resetCamera",
    IS_SOUND_PLAYER_STREAM_ACCESS_ALLOWED = "isSoundPlayerStreamAccessAllowed",
    CAMERA_SENSITIVITY = "cameraSensitivity",
    NICKNAME = "nickname",
    IS_HEAD_TRACKING_ENABLED = "isHeadTrackingEnabled",
    HORSE_ABANDON_TIMER_DURATION = "horseAbandonTimerDuration",
    JOYSTICK_VIBRATION_ENABLED = "joystickVibrationEnabled",
    UI_SCALE = "uiScale",
    STEERING_BACK_SPEED = "steeringBackSpeed",
    DEFAULT_SERVER_PORT = "defaultServerPort",
    FOV_Y = "fovY",
    LIGHTS_PROFILE = "lightsProfile",
    VOLUME_MUSIC = "musicVolume",
    MOTOR_STOP_TIMER_DURATION = "motorStopTimerDuration",
    RADIO_VEHICLE_ONLY = "radioVehicleOnly",
    REAL_BEACON_LIGHTS = "realBeaconLights",
    INGAME_MAP_FILTER = "ingameMapFilter",
    USE_FAHRENHEIT = "useFahrenheit",
    PLAYER_BODY_INDEX = "playerBodyIndex",
    USE_WORLD_CAMERA = "useWorldCamera",
    IS_TRAIN_TABBABLE = "isTrainTabbable",
    PLAYER_JACKET_INDEX = "playerJacketIndex",
    EASY_ARM_CONTROL = "easyArmControl",
    VEHICLE_ARM_SENSITIVITY = "vehicleArmSensitivity",
    INVERT_Y_LOOK = "invertYLook",
    INGAME_MAP_STATE = "ingameMapState",
    USE_MILES = "useMiles",
    INPUT_HELP_MODE = "inputHelpMode",
    VOLUME_ENVIRONMENT = "environmentVolume",
    GAMEPAD_ENABLED_SET_BY_USER = "gamepadEnabledSetByUser",
    MAX_NUM_MIRRORS = "maxNumMirrors",
    PLAYER_MODEL_INDEX = "playerModelIndex",
    PLAYER_COLOR_INDEX = "playerColorIndex",
    IS_GAMEPAD_ENABLED = "isGamepadEnabled",
    VOLUME_GUI = "volumeGUI",
    PLAYER_HAT_INDEX = "playerHatIndex",
    SHOW_HELP_MENU = "showHelpMenu",
    VOLUME_RADIO = "radioVolume",
    HEAD_TRACKING_ENABLED_SET_BY_USER = "headTrackingEnabledSetByUser",
    MONEY_UNIT = "moneyUnit",
    USE_ACRE = "useAcre",
    SHOW_TRIGGER_MARKER = "showTriggerMarker",
    VOLUME_VEHICLE = "vehicleVolume"
}
function GameSettings:getTableValue() end
function GameSettings:new() end
function GameSettings:setTableValue() end
function GameSettings:isa() end
function GameSettings:loadFromXML() end
function GameSettings:setValue() end
function GameSettings:setXMLValue() end
function GameSettings:superClass() end
function GameSettings:saveToXMLFile() end
function GameSettings:getValue() end
function GameSettings:setTableValueFromXML() end
function GameSettings:class() end
function GameSettings:copy() end