HusbandryModuleFood = {}

function HusbandryModuleFood:new() end
function HusbandryModuleFood:initDataStructures() end
function HusbandryModuleFood:onFillProgressChanged() end
function HusbandryModuleFood:delete() end
function HusbandryModuleFood:getIsNodeUsed() end
function HusbandryModuleFood:superClass() end
function HusbandryModuleFood:getFoodFactor() end
function HusbandryModuleFood:loadFromXMLFile() end
function HusbandryModuleFood:getCapacity() end
function HusbandryModuleFood:changeFillLevels() end
function HusbandryModuleFood:updateFillPlane() end
function HusbandryModuleFood:readStream() end
function HusbandryModuleFood:getFilltypeInfos() end
function HusbandryModuleFood:getTotalFillLevel() end
function HusbandryModuleFood:copy() end
function HusbandryModuleFood:onIntervalUpdate() end
function HusbandryModuleFood:class() end
function HusbandryModuleFood:addFillLevelFromTool() end
function HusbandryModuleFood:getFillLevel() end
function HusbandryModuleFood:writeStream() end
function HusbandryModuleFood:setCapacity() end
function HusbandryModuleFood:setupFoodGroups() end
function HusbandryModuleFood:getConsumedFood() end
function HusbandryModuleFood:isa() end
function HusbandryModuleFood:updateFillPlaneColor() end
function HusbandryModuleFood:getFreeCapacity() end
function HusbandryModuleFood:load() end