HusbandryModuleFoodSpillage = {}

function HusbandryModuleFoodSpillage:readStream() end
function HusbandryModuleFoodSpillage:initDataStructures() end
function HusbandryModuleFoodSpillage:delete() end
function HusbandryModuleFoodSpillage:superClass() end
function HusbandryModuleFoodSpillage:loadFromXMLFile() end
function HusbandryModuleFoodSpillage:getSpillageFactor() end
function HusbandryModuleFoodSpillage:copy() end
function HusbandryModuleFoodSpillage:onIntervalUpdate() end
function HusbandryModuleFoodSpillage:class() end
function HusbandryModuleFoodSpillage:writeUpdateStream() end
function HusbandryModuleFoodSpillage:readUpdateStream() end
function HusbandryModuleFoodSpillage:writeStream() end
function HusbandryModuleFoodSpillage:updateCleanlinessFactor() end
function HusbandryModuleFoodSpillage:saveToXMLFile() end
function HusbandryModuleFoodSpillage:getFoodSpillageLevel() end
function HusbandryModuleFoodSpillage:updateFoodSpillage() end
function HusbandryModuleFoodSpillage:isa() end
function HusbandryModuleFoodSpillage:load() end
function HusbandryModuleFoodSpillage:new() end