HusbandryModuleBase = {}

function HusbandryModuleBase:finalizePlacement() end
function HusbandryModuleBase:new() end
function HusbandryModuleBase:getHasSpaceForUnloading() end
function HusbandryModuleBase:delete() end
function HusbandryModuleBase:loadFromXMLFile() end
function HusbandryModuleBase:update() end
function HusbandryModuleBase:getProvidedFillTypes() end
function HusbandryModuleBase:getTotalFillLevel() end
function HusbandryModuleBase:onIntervalUpdate() end
function HusbandryModuleBase:setSingleAnimalUsagePerDay() end
function HusbandryModuleBase:getFillLevel() end
function HusbandryModuleBase:setCapacity() end
function HusbandryModuleBase:saveToXMLFile() end
function HusbandryModuleBase:hasModule() end
function HusbandryModuleBase:getIsFillAllowedToFarm() end
function HusbandryModuleBase:readStream() end
function HusbandryModuleBase:createModule() end
function HusbandryModuleBase:initDataStructures() end
function HusbandryModuleBase:getCapacity() end
function HusbandryModuleBase:getIsInUse() end
function HusbandryModuleBase:onFillProgressChanged() end
function HusbandryModuleBase:addFillLevelToFillableObject() end
function HusbandryModuleBase:superClass() end
function HusbandryModuleBase:getAllFillLevels() end
function HusbandryModuleBase:onDayChanged() end
function HusbandryModuleBase:addFillLevelFromTool() end
function HusbandryModuleBase:changeFillLevels() end
function HusbandryModuleBase:onSell() end
function HusbandryModuleBase:getFillProgress() end
function HusbandryModuleBase:registerModule() end
function HusbandryModuleBase:copy() end
function HusbandryModuleBase:onQuarterHourChanged() end
function HusbandryModuleBase:onHourChanged() end
function HusbandryModuleBase:getIsFillTypeAllowed() end
function HusbandryModuleBase:writeUpdateStream() end
function HusbandryModuleBase:readUpdateStream() end
function HusbandryModuleBase:writeStream() end
function HusbandryModuleBase:load() end
function HusbandryModuleBase:isa() end
function HusbandryModuleBase:setFillLevel() end
function HusbandryModuleBase:class() end
function HusbandryModuleBase:getIsNodeUsed() end
function HusbandryModuleBase:getFreeCapacity() end
function HusbandryModuleBase:getIsToolTypeAllowed() end