SoundPlayer = {}

function SoundPlayer:new() end
function SoundPlayer:setStreamAccessAllowed() end
function SoundPlayer:isa() end
function SoundPlayer:changeChannel() end
function SoundPlayer:setStreamingAccessOwner() end
function SoundPlayer:superClass() end
function SoundPlayer:getIsPlaying() end
function SoundPlayer:play() end
function SoundPlayer:update() end
function SoundPlayer:addEventListener() end
function SoundPlayer:nextItem() end
function SoundPlayer:onChange() end
function SoundPlayer:copy() end
function SoundPlayer:pause() end
function SoundPlayer:class() end
function SoundPlayer:getChannelName() end
function SoundPlayer:getItemName() end
function SoundPlayer:previousItem() end
function SoundPlayer:initializeSoundPlayer() end
function SoundPlayer:startChannel() end
function SoundPlayer:nextChannel() end
function SoundPlayer:updateMetaData() end
function SoundPlayer:delete() end
function SoundPlayer:previousChannel() end
function SoundPlayer:removeEventListener() end