FarmStats = {}

FarmStats.HERO_STAT_NAMES = {
    1 = 'playTime',
    2 = 'moneyEarned',
    3 = 'traveledDistance',
    4 = 'completedMissions',
    5 = 'threshedHectares'
}
FarmStats.STAT_NAMES = {
    1 = 'fuelUsage',
    2 = 'seedUsage',
    3 = 'sprayUsage',
    4 = 'traveledDistance',
    5 = 'workedHectares',
    6 = 'cultivatedHectares',
    7 = 'plowedHectares',
    8 = 'sownHectares',
    9 = 'fertilizedHectares',
    10 = 'threshedHectares',
    11 = 'sprayedHectares',
    12 = 'weededHectares',
    13 = 'workedTime',
    14 = 'cultivatedTime',
    15 = 'plowedTime',
    16 = 'sownTime',
    17 = 'fertilizedTime',
    18 = 'threshedTime',
    19 = 'sprayedTime',
    20 = 'weededTime',
    21 = 'baleCount',
    22 = 'breedCowsCount',
    23 = 'breedPigsCount',
    24 = 'breedSheepCount',
    25 = 'breedChickenCount',
    26 = 'breedHorsesCount',
    27 = 'revenue',
    28 = 'expenses',
    29 = 'playTime',
    30 = 'workersHired',
    31 = 'storageCapacity',
    32 = 'fieldJobMissionCount',
    33 = 'fieldJobMissionByNPC',
    34 = 'transportMissionCount',
    35 = 'plantedTreeCount',
    36 = 'cutTreeCount',
    37 = 'woodTonsSold',
    38 = 'treeTypesCut',
    39 = 'windTurbineCount'
}

function FarmStats:changeFinanceStats() end
function FarmStats:new() end
function FarmStats:isa() end
function FarmStats:merge() end
function FarmStats:addStatistic() end
function FarmStats:delete() end
function FarmStats:addHeroStat() end
function FarmStats:superClass() end
function FarmStats:updateTreeTypesCut() end
function FarmStats:loadFromXMLFile() end
function FarmStats:getCompletedMissionsSession() end
function FarmStats:update() end
function FarmStats:getCompletedFieldMissionsSession() end
function FarmStats:updateTransportJobsDone() end
function FarmStats:getSessionValue() end
function FarmStats:updateFieldJobsDone() end
function FarmStats:copy() end
function FarmStats:getTotalValue() end
function FarmStats:class() end
function FarmStats:getCompletedFieldMissions() end
function FarmStats:updateStats() end
function FarmStats:getStatisticData() end
function FarmStats:getCompletedMissions() end
function FarmStats:saveToXMLFile() end
function FarmStats:getCompletedTransportMissionsSession() end
function FarmStats:getCompletedTransportMissions() end
function FarmStats:archiveFinances() end
function FarmStats:addValueToHeroStat() end