AnimatedObject = {}

AnimatedObject.classId = 50.000000
AnimatedObject.className = 'AnimatedObject'

function AnimatedObject:onCreate() end
function AnimatedObject:registerActionEventsWhenInRange() end
function AnimatedObject:new() end
function AnimatedObject:updateActionEventTexts() end
function AnimatedObject:isa() end
function AnimatedObject:removeActionEvents() end
function AnimatedObject:delete() end
function AnimatedObject:superClass() end
function AnimatedObject:loadFromXMLFile() end
function AnimatedObject:update() end
function AnimatedObject:setFrameValues() end
function AnimatedObject:triggerCallback() end
function AnimatedObject:copy() end
function AnimatedObject:setAnimTime() end
function AnimatedObject:class() end
function AnimatedObject:writeUpdateStream() end
function AnimatedObject:readUpdateStream() end
function AnimatedObject:writeStream() end
function AnimatedObject:load() end
function AnimatedObject:saveToXMLFile() end
function AnimatedObject:readStream() end
function AnimatedObject:onAnimationInputToggle() end
function AnimatedObject:hourChanged() end
function AnimatedObject:loadFrameValues() end
function AnimatedObject:onAnimationInputContinuous() end