Bale = {}

Bale.classId = 6.000000
Bale.className = 'Bale'

function Bale:unmount() end
function Bale:new() end
function Bale:delete() end
function Bale:getSupportsTensionBelts() end
function Bale:loadFromMemory() end
function Bale:loadFromXMLFile() end
function Bale:setColor() end
function Bale:copy() end
function Bale:getFillLevel() end
function Bale:setCanBeSold() end
function Bale:getValue() end
function Bale:getMeshNodes() end
function Bale:readStream() end
function Bale:mount() end
function Bale:isa() end
function Bale:superClass() end
function Bale:createNode() end
function Bale:getFillType() end
function Bale:getTensionBeltNodeId() end
function Bale:load() end
function Bale:class() end
function Bale:getCanBeSold() end
function Bale:readUpdateStream() end
function Bale:writeStream() end
function Bale:loadExtraAttributesFromXMLFile() end
function Bale:setFillLevel() end
function Bale:setWrappingState() end
function Bale:saveToXMLFile() end
function Bale:setNodeId() end
function Bale:writeUpdateStream() end
function Bale:applyExtraAttributes() end