BunkerSilo = {}

BunkerSilo.STATE_FERMENTED = 2.000000
BunkerSilo.STATE_DRAIN = 3.000000
BunkerSilo.classId = 28.000000
BunkerSilo.STATE_CLOSED = 1.000000
BunkerSilo.COMPACTING_BASE_MASS = 5.000000
BunkerSilo.className = 'BunkerSilo'
BunkerSilo.STATE_FILL = 0.000000
BunkerSilo.NUM_STATES = 4.000000

function BunkerSilo:onCreate() end
function BunkerSilo:new() end
function BunkerSilo:getInteractionPosition() end
function BunkerSilo:delete() end
function BunkerSilo:updateTick() end
function BunkerSilo:update() end
function BunkerSilo:getCanInteract() end
function BunkerSilo:copy() end
function BunkerSilo:saveToXMLFile() end
function BunkerSilo:getCanOpenSilo() end
function BunkerSilo:setState() end
function BunkerSilo:readStream() end
function BunkerSilo:clearSiloArea() end
function BunkerSilo:isa() end
function BunkerSilo:getCanCloseSilo() end
function BunkerSilo:getIsCloserToFront() end
function BunkerSilo:superClass() end
function BunkerSilo:switchFillTypeAtOffset() end
function BunkerSilo:onChangedFillLevelCallback() end
function BunkerSilo:interactionTriggerCallback() end
function BunkerSilo:class() end
function BunkerSilo:writeUpdateStream() end
function BunkerSilo:readUpdateStream() end
function BunkerSilo:writeStream() end
function BunkerSilo:load() end
function BunkerSilo:openSilo() end
function BunkerSilo:getBunkerAreaOffset() end
function BunkerSilo:updateFillLevel() end
function BunkerSilo:loadFromXMLFile() end