SellingStation = {}

SellingStation.className = 'SellingStation'
SellingStation.PRICE_CLIMBING = 2.000000
SellingStation.PRICE_HIGH = 4.000000
SellingStation.PRICE_LOW = 3.000000
SellingStation.PRICE_FALLING = 1.000000
SellingStation.PRICE_DROP_DELAY = 3600000.000000
SellingStation.classId = 16.000000
SellingStation.PRICE_GREAT_DEMAND = 5.000000

function SellingStation:setIsInGreatDemand() end
function SellingStation:new() end
function SellingStation:getSupportsGreatDemand() end
function SellingStation:setPriceMultiplier() end
function SellingStation:addAcceptedFillType() end
function SellingStation:executePriceDrop() end
function SellingStation:copy() end
function SellingStation:doPriceDrop() end
function SellingStation:saveToXMLFile() end
function SellingStation:getTotalReceived() end
function SellingStation:addTargetStorage() end
function SellingStation:getPriceMultiplier() end
function SellingStation:readStream() end
function SellingStation:isa() end
function SellingStation:getIncomeNameForFillType() end
function SellingStation:getAppearsOnStats() end
function SellingStation:superClass() end
function SellingStation:getIsFillAllowedFromFarm() end
function SellingStation:update() end
function SellingStation:addFillLevelFromTool() end
function SellingStation:updatePrices() end
function SellingStation:getCurrentPricingTrend() end
function SellingStation:initPricingDynamics() end
function SellingStation:loadFromXMLFile() end
function SellingStation:sellFillType() end
function SellingStation:load() end
function SellingStation:getIsFillTypeAllowed() end
function SellingStation:writeUpdateStream() end
function SellingStation:readUpdateStream() end
function SellingStation:writeStream() end
function SellingStation:class() end
function SellingStation:getTotalPaid() end
function SellingStation:updateTick() end
function SellingStation:getFreeCapacity() end
function SellingStation:getEffectiveFillTypePrice() end