VehicleSellingPoint = {}

function VehicleSellingPoint:updateIconVisibility() end
function VehicleSellingPoint:new() end
function VehicleSellingPoint:isa() end
function VehicleSellingPoint:delete() end
function VehicleSellingPoint:superClass() end
function VehicleSellingPoint:sellAreaTriggerCallback() end
function VehicleSellingPoint:determineCurrentVehicle() end
function VehicleSellingPoint:setOwnerFarmId() end
function VehicleSellingPoint:triggerCallback() end
function VehicleSellingPoint:copy() end
function VehicleSellingPoint:getOwnerFarmId() end
function VehicleSellingPoint:class() end
function VehicleSellingPoint:onActivateObject() end
function VehicleSellingPoint:load() end
function VehicleSellingPoint:playerFarmChanged() end
function VehicleSellingPoint:getIsActivatable() end
function VehicleSellingPoint:drawActivate() end
function VehicleSellingPoint:shouldRemoveActivatable() end
function VehicleSellingPoint:update() end