UnloadTrigger = {}

UnloadTrigger.classId = 13.000000
UnloadTrigger.className = 'UnloadTrigger'

function UnloadTrigger:getTarget() end
function UnloadTrigger:loadBaleTrigger() end
function UnloadTrigger:new() end
function UnloadTrigger:getFillUnitIndexFromNode() end
function UnloadTrigger:isa() end
function UnloadTrigger:getFillUnitExactFillRootNode() end
function UnloadTrigger:delete() end
function UnloadTrigger:getCustomDischargeNotAllowedWarning() end
function UnloadTrigger:superClass() end
function UnloadTrigger:getFillUnitSupportsFillType() end
function UnloadTrigger:loadFillTypes() end
function UnloadTrigger:getFillUnitFreeCapacity() end
function UnloadTrigger:update() end
function UnloadTrigger:getIsFillAllowedFromFarm() end
function UnloadTrigger:loadAvoidFillTypes() end
function UnloadTrigger:getIsFillTypeSupported() end
function UnloadTrigger:copy() end
function UnloadTrigger:getIsFillTypeAllowed() end
function UnloadTrigger:class() end
function UnloadTrigger:loadAcceptedToolType() end
function UnloadTrigger:getFillUnitAllowsFillType() end
function UnloadTrigger:getFillUnitSupportsToolType() end
function UnloadTrigger:load() end
function UnloadTrigger:baleTriggerCallback() end
function UnloadTrigger:setTarget() end
function UnloadTrigger:addFillUnitFillLevel() end
function UnloadTrigger:updateBales() end
function UnloadTrigger:getIsToolTypeAllowed() end