Vehicle = {}

Vehicle.classId = 2.000000
Vehicle.NUM_STATE_CHANGES = 8.000000
Vehicle.debugNetworkUpdate = false
Vehicle.PROPERTY_STATE_NONE = 0.000000
Vehicle.PROPERTY_STATE_OWNED = 1.000000
Vehicle.SPRING_SCALE = 10.000000
Vehicle.INPUT_CONTEXT_NAME = 'VEHICLE'
Vehicle.STATE_CHANGE_LOWER_ALL_IMPLEMENTS = 3.000000
Vehicle.className = 'Vehicle'
Vehicle.PROPERTY_STATE_SHOP_CONFIG = 4.000000
Vehicle.PROPERTY_STATE_MISSION = 3.000000
Vehicle.STATE_CHANGE_ATTACH = 1.000000
Vehicle.STATE_CHANGE_AI_END_LINE = 7.000000
Vehicle.STATE_CHANGE_MOTOR_TURN_OFF = 5.000000
Vehicle.STATE_CHANGE_DETACH = 2.000000
Vehicle.STATE_CHANGE_AI_START_LINE = 6.000000
Vehicle.STATE_CHANGE_MOTOR_TURN_ON = 4.000000
Vehicle.INTERACTION_FLAG_NONE = 0.000000
Vehicle.defaultLength = 8.000000
Vehicle.STATE_CHANGE_FILLTYPE_CHANGE = 8.000000
Vehicle.defaultWidth = 8.000000
Vehicle.NUM_INTERACTION_FLAGS = 0.000000
Vehicle.DAMAGED_SPEEDLIMIT_REDUCTION = 0.300000
Vehicle.PROPERTY_STATE_LEASED = 2.000000

function Vehicle:getLastSpeed() end
function Vehicle:setMassDirty() end
function Vehicle:unselectVehicle() end
function Vehicle:onVehicleWakeUpCallback() end
function Vehicle:setWorldPosition() end
function Vehicle:getPrice() end
function Vehicle:copy() end
function Vehicle:getCanToggleSelectable() end
function Vehicle:getRootVehicle() end
function Vehicle:getReloadXML() end
function Vehicle:addSubselection() end
function Vehicle:getSpecValueSlots() end
function Vehicle:getIsAIActive() end
function Vehicle:registerSelectableObjects() end
function Vehicle:doCollisionMaskCheck() end
function Vehicle:deactivate() end
function Vehicle:setAbsolutePosition() end
function Vehicle:setComponentJointRotLimit() end
function Vehicle:setComponentJointFrame() end
function Vehicle:clearActionEventsTable() end
function Vehicle:load() end
function Vehicle:getIsReadyForAutomatedTrainTravel() end
function Vehicle:addNodeObjectMapping() end
function Vehicle:registerInteractionFlag() end
function Vehicle:saveStatsToXMLFile() end
function Vehicle:getIsActive() end
function Vehicle:loadSchemaOverlay() end
function Vehicle:addToPhysics() end
function Vehicle:delete() end
function Vehicle:getDailyUpkeep() end
function Vehicle:updateTick() end
function Vehicle:loadComponentJointFromXML() end
function Vehicle:registerEvents() end
function Vehicle:loadComponentFromXML() end
function Vehicle:getName() end
function Vehicle:raiseStateChange() end
function Vehicle:getIsActiveForSound() end
function Vehicle:setRelativePosition() end
function Vehicle:setLoadingState() end
function Vehicle:getActiveFarm() end
function Vehicle:getSpecValueDailyUpkeep() end
function Vehicle:updateSelectableObjects() end
function Vehicle:getSpeedLimit() end
function Vehicle:setSelectedVehicle() end
function Vehicle:writeUpdateStream() end
function Vehicle:registerStateChange() end
function Vehicle:getSelectedVehicle() end
function Vehicle:selectVehicle() end
function Vehicle:getParentComponent() end
function Vehicle:getLimitedVehicleYPosition() end
function Vehicle:getCanBeReset() end
function Vehicle:setSelectedObject() end
function Vehicle:drawUIInfo() end
function Vehicle:removeFromPhysics() end
function Vehicle:getWorkLoad() end
function Vehicle:getTotalMass() end
function Vehicle:getTailwaterDepth() end
function Vehicle:getSelectedObject() end
function Vehicle:isa() end
function Vehicle:draw() end
function Vehicle:getSellPrice() end
function Vehicle:hasInputConflictWithSelection() end
function Vehicle:getIsSelected() end
function Vehicle:setOperatingTime() end
function Vehicle:getAdditionalComponentMass() end
function Vehicle:readUpdateStream() end
function Vehicle:new() end
function Vehicle:getIsOperating() end
function Vehicle:getIsOnField() end
function Vehicle:getDistanceToNode() end
function Vehicle:loadSpecValueCombinations() end
function Vehicle:getSpecValueSpeedLimit() end
function Vehicle:loadSpecValueSpeedLimit() end
function Vehicle:getSpecValueWorkingWidth() end
function Vehicle:getSpecValueOperatingTime() end
function Vehicle:addActionEvent() end
function Vehicle:actionEventToggleSelection() end
function Vehicle:registerFunctions() end
function Vehicle:getFullName() end
function Vehicle:getIsInUse() end
function Vehicle:init() end
function Vehicle:getOwner() end
function Vehicle:interact() end
function Vehicle:addVehicleToAIImplementList() end
function Vehicle:getCanBeSelected() end
function Vehicle:writeStream() end
function Vehicle:loadSpecValueWorkingWidth() end
function Vehicle:loadFinished() end
function Vehicle:getDeactivateOnLeave() end
function Vehicle:getInteractionHelp() end
function Vehicle:getCanBePickedUp() end
function Vehicle:removeNodeObjectMapping() end
function Vehicle:saveToXMLFile() end
function Vehicle:updateActionEvents() end
function Vehicle:getChildVehicles() end
function Vehicle:createComponentJoint() end
function Vehicle:setWorldPositionQuaternion() end
function Vehicle:getAdditionalSchemaText() end
function Vehicle:getIsLowered() end
function Vehicle:getRepairPrice() end
function Vehicle:readStream() end
function Vehicle:superClass() end
function Vehicle:getUpdatePriority() end
function Vehicle:removeActionEvents() end
function Vehicle:getVehicleDamage() end
function Vehicle:registerActionEvents() end
function Vehicle:getOperatingTime() end
function Vehicle:requestActionEventUpdate() end
function Vehicle:setBroken() end
function Vehicle:updateVehicleSpeed() end
function Vehicle:getIsVehicleNode() end
function Vehicle:dayChanged() end
function Vehicle:updateMass() end
function Vehicle:activate() end
function Vehicle:removeActionEvent() end
function Vehicle:getIsActiveForInput() end
function Vehicle:prefixSchemaOverlayName() end
function Vehicle:update() end
function Vehicle:getSpecValueCombinations() end
function Vehicle:getFillLevelInformation() end
function Vehicle:getCanByMounted() end
function Vehicle:updateEnd() end
function Vehicle:class() end
function Vehicle:doCheckSpeedLimit() end
function Vehicle:setComponentJointTransLimit() end
function Vehicle:getSpecValueAge() end