Environment = {}

function Environment:consoleCommandSetFixedExposureSettings() end
function Environment:consoleCommandReloadEnvironment() end
function Environment:onCreateSunLight() end
function Environment:addDayChangeListener() end
function Environment:isa() end
function Environment:onGameStateChanged() end
function Environment:removeWeatherChangeListener() end
function Environment:delete() end
function Environment:loadSettings() end
function Environment:superClass() end
function Environment:addWeatherChangeListener() end
function Environment:loadFromXMLFile() end
function Environment:removeHourChangeListener() end
function Environment:update() end
function Environment:getEnvironmentTime() end
function Environment:setCustomLighting() end
function Environment:addMinuteChangeListener() end
function Environment:removeRealHourChangeListener() end
function Environment:copy() end
function Environment:addRealHourChangeListener() end
function Environment:class() end
function Environment:consoleCommandSetDayTime() end
function Environment:onCreateWater() end
function Environment:updateSceneParameters() end
function Environment:removeDayChangeListener() end
function Environment:saveToXMLFile() end
function Environment:addHourChangeListener() end
function Environment:setEnvironmentTime() end
function Environment:removeMinuteChangeListener() end
function Environment:new() end
function Environment:getDayAndDayTime() end