AnimatedVehicle = {}

function AnimatedVehicle:postInitializeAnimationPart() end
function AnimatedVehicle:updateAnimation() end
function AnimatedVehicle:registerFunctions() end
function AnimatedVehicle:getNextPartIsPlaying() end
function AnimatedVehicle:prerequisitesPresent() end
function AnimatedVehicle:onDelete() end
function AnimatedVehicle:initializeAnimationPart() end
function AnimatedVehicle:setRealAnimationTime() end
function AnimatedVehicle:loadWorkAreaFromXML() end
function AnimatedVehicle:registerEvents() end
function AnimatedVehicle:registerOverwrittenFunctions() end
function AnimatedVehicle:getAnimationTime() end
function AnimatedVehicle:initializeAnimationPartAttribute() end
function AnimatedVehicle:onUpdate() end
function AnimatedVehicle:getIsSpeedRotatingPartActive() end
function AnimatedVehicle:onLoad() end
function AnimatedVehicle:getIsAnimationPlaying() end
function AnimatedVehicle:getRealAnimationTime() end
function AnimatedVehicle:initializeAnimationParts() end
function AnimatedVehicle:setMovedLimitedValues4() end
function AnimatedVehicle:getNumOfActiveAnimations() end
function AnimatedVehicle:registerEventListeners() end
function AnimatedVehicle:updateAnimationPart() end
function AnimatedVehicle:updateAnimationCurrentTime() end
function AnimatedVehicle:updateAnimationByName() end
function AnimatedVehicle:updateAnimations() end
function AnimatedVehicle:getAnimationExists() end
function AnimatedVehicle:getDurationToEndOfPart() end
function AnimatedVehicle:resetAnimationValues() end
function AnimatedVehicle:findCurrentPartIndex() end
function AnimatedVehicle:loadSpeedRotatingPartFromXML() end
function AnimatedVehicle:setMovedLimitedValues3() end
function AnimatedVehicle:getMovedLimitedValue() end
function AnimatedVehicle:stopAnimation() end
function AnimatedVehicle:animPartSorterReverse() end
function AnimatedVehicle:setAnimationTime() end
function AnimatedVehicle:loadAnimation() end
function AnimatedVehicle:onPostLoad() end
function AnimatedVehicle:setAnimationSpeed() end
function AnimatedVehicle:getAnimationDuration() end
function AnimatedVehicle:playAnimation() end
function AnimatedVehicle:getIsWorkAreaActive() end
function AnimatedVehicle:animPartSorter() end
function AnimatedVehicle:loadAnimationPart() end
function AnimatedVehicle:resetAnimationPartValues() end
function AnimatedVehicle:setAnimationStopTime() end