AttacherJointControl = {}

function AttacherJointControl:actionEventAttacherJointControlSetPoint() end
function AttacherJointControl:controlAttacherJoint() end
function AttacherJointControl:onRegisterActionEvents() end
function AttacherJointControl:actionEventAttacherJointControl() end
function AttacherJointControl:registerFunctions() end
function AttacherJointControl:onReadUpdateStream() end
function AttacherJointControl:prerequisitesPresent() end
function AttacherJointControl:onDelete() end
function AttacherJointControl:onReadStream() end
function AttacherJointControl:onWriteUpdateStream() end
function AttacherJointControl:getCanBeSelected() end
function AttacherJointControl:onWriteStream() end
function AttacherJointControl:onPreDetach() end
function AttacherJointControl:registerOverwrittenFunctions() end
function AttacherJointControl:loadInputAttacherJoint() end
function AttacherJointControl:getLoweringActionEventState() end
function AttacherJointControl:getControlAttacherJointDirection() end
function AttacherJointControl:onPostAttach() end
function AttacherJointControl:controlAttacherJointTilt() end
function AttacherJointControl:controlAttacherJointHeight() end
function AttacherJointControl:registerLoweringActionEvent() end
function AttacherJointControl:onUpdate() end
function AttacherJointControl:registerEventListeners() end
function AttacherJointControl:onLoad() end