Attachable = {}

function Attachable:getSteeringAxleBaseVehicle() end
function Attachable:getOwner() end
function Attachable:getInputAttacherJoints() end
function Attachable:getAttachbleAirConsumerUsage() end
function Attachable:registerFunctions() end
function Attachable:setLowered() end
function Attachable:onDeactivate() end
function Attachable:prerequisitesPresent() end
function Attachable:getIsInputAttacherActive() end
function Attachable:onReadStream() end
function Attachable:postDetach() end
function Attachable:getActiveInputAttacherJointDescIndex() end
function Attachable:attachableRemoveToolCameras() end
function Attachable:registerEvents() end
function Attachable:registerOverwrittenFunctions() end
function Attachable:onStateChange() end
function Attachable:onAIImplementEndLine() end
function Attachable:getIsFoldAllowed() end
function Attachable:onAIImplementStartLine() end
function Attachable:saveToXMLFile() end
function Attachable:getInputAttacherJointByJointDescIndex() end
function Attachable:mountDynamic() end
function Attachable:onUpdate() end
function Attachable:getCanToggleTurnedOn() end
function Attachable:onLoad() end
function Attachable:getIsLowered() end
function Attachable:getActiveInputAttacherJoint() end
function Attachable:getActiveFarm() end
function Attachable:getCanBeSelected() end
function Attachable:getCanAIImplementContinueWork() end
function Attachable:getDeactivateOnLeave() end
function Attachable:getBrakeForce() end
function Attachable:registerEventListeners() end
function Attachable:loadInputAttacherJoint() end
function Attachable:getIsActive() end
function Attachable:getRootVehicle() end
function Attachable:getIsAttachedTo() end
function Attachable:initSpecialization() end
function Attachable:onUnselect() end
function Attachable:onSelect() end
function Attachable:preDetach() end
function Attachable:onWriteStream() end
function Attachable:getLoweringActionEventState() end
function Attachable:registerLoweringActionEvent() end
function Attachable:getAttacherVehicle() end
function Attachable:onPostLoad() end
function Attachable:getAllowsLowering() end
function Attachable:isDetachAllowed() end
function Attachable:preAttach() end
function Attachable:onPreDelete() end
function Attachable:postAttach() end
function Attachable:setLoweredAll() end
function Attachable:getIsImplementChainLowered() end
function Attachable:getIsOperating() end
function Attachable:getIsInWorkPosition() end
function Attachable:attachableAddToolCameras() end
function Attachable:getIsInUse() end