AttacherJoints = {}

AttacherJoints.jointTypeNameToInt = {
  trailerLow = 3,
  semitrailerHook = 8,
  trailer = 2,
  semitrailer = 7,
  wheelLoader = 10,
  loaderFork = 6,
  hookLift = 16,
  conveyor = 15,
  train = 17,
  implement = 1,
  skidSteer = 14,
  cutter = 12,
  telehandler = 4,
  cutterHarvester = 13,
  attachableFrontloader = 9,
  manureBarrel = 11,
  frontloader = 5
}

AttacherJoints.NUM_JOINTTYPES = 17
AttacherJoints.MAX_ATTACH_DISTANCE_SQ = 1
AttacherJoints.MAX_ATTACH_ANGLE = 0.34202
AttacherJoints.JOINTTYPE_TELEHANDLER = 4
AttacherJoints.JOINTTYPE_HOOKLIFT = 16
AttacherJoints.JOINTTYPE_ATTACHABLEFRONTLOADER = 9
AttacherJoints.JOINTTYPE_TRAILER = 2
AttacherJoints.JOINTTYPE_WHEELLOADER = 10
AttacherJoints.JOINTTYPE_MANUREBARREL = 11
AttacherJoints.JOINTTYPE_IMPLEMENT = 1
AttacherJoints.JOINTTYPE_TRAIN = 17
AttacherJoints.JOINTTYPE_TRAILERLOW = 3
AttacherJoints.JOINTTYPE_CONVEYOR = 15
AttacherJoints.JOINTTYPE_SEMITRAILERHOOK = 8
AttacherJoints.JOINTTYPE_SKIDSTEER = 14
AttacherJoints.JOINTTYPE_LOADERFORK = 6
AttacherJoints.JOINTTYPE_CUTTERHARVESTER = 13
AttacherJoints.JOINTTYPE_CUTTER = 12
AttacherJoints.JOINTTYPE_SEMITRAILER = 7
AttacherJoints.JOINTTYPE_FRONTLOADER = 5

function AttacherJoints:handleLowerImplementEvent() end
function AttacherJoints:getSelectedImplement() end
function AttacherJoints:updateAttacherJointGraphics() end
function AttacherJoints:playDetachSound() end
function AttacherJoints:loadAttacherJointFromXML() end
function AttacherJoints:createAttachmentJoint() end
function AttacherJoints:onDeactivate() end
function AttacherJoints:prerequisitesPresent() end
function AttacherJoints:onPreDelete() end
function AttacherJoints:setJointMoveDown() end
function AttacherJoints:attachImplement() end
function AttacherJoints:registerSelfLoweringActionEvent() end
function AttacherJoints:deactivateAttachmentsLights() end
function AttacherJoints:onTurnedOn() end
function AttacherJoints:activateAttachments() end
function AttacherJoints:onTurnedOff() end
function AttacherJoints:actionEventLowerImplement() end
function AttacherJoints:actionEventAttach() end
function AttacherJoints:onLoad() end
function AttacherJoints:getTotalMass() end
function AttacherJoints:getImplementByObject() end
function AttacherJoints:registerJointType() end
function AttacherJoints:callFunctionOnAllImplements() end
function AttacherJoints:getCanToggleAttach() end
function AttacherJoints:detachImplement() end
function AttacherJoints:findVehicleInAttachRange() end
function AttacherJoints:initSpecialization() end
function AttacherJoints:onDeactivateLights() end
function AttacherJoints:getAttacherJointIndexFromImplementIndex() end
function AttacherJoints:getAttacherJointByJointDescIndex() end
function AttacherJoints:onBrake() end
function AttacherJoints:updateAttacherJointRotation() end
function AttacherJoints:playAttachSound() end
function AttacherJoints:onReverseLightsVisibilityChanged() end
function AttacherJoints:onBrakeLightsVisibilityChanged() end
function AttacherJoints:onDraw() end
function AttacherJoints:onPostLoad() end
function AttacherJoints:detachingIsPossible() end
function AttacherJoints:onTurnLightStateChanged() end
function AttacherJoints:onLightsTypesMaskChanged() end
function AttacherJoints:setSelectedImplementByObject() end
function AttacherJoints:hardAttachImplement() end
function AttacherJoints:onStateChange() end
function AttacherJoints:getDirectionSnapAngle() end
function AttacherJoints:onLeaveVehicle() end
function AttacherJoints:onReverseDirectionChanged() end
function AttacherJoints:updateAttacherJointRotationNodes() end
function AttacherJoints:onActivate() end
function AttacherJoints:registerActionEvents() end
function AttacherJoints:getAttacherJoints() end
function AttacherJoints:saveAttachmentsToXMLFile() end
function AttacherJoints:handleLowerImplementByAttacherJointIndex() end
function AttacherJoints:registerFunctions() end
function AttacherJoints:onPostUpdate() end
function AttacherJoints:actionEventLowerAllImplements() end
function AttacherJoints:getObjectFromImplementIndex() end
function AttacherJoints:onDelete() end
function AttacherJoints:hardDetachImplement() end
function AttacherJoints:raiseActive() end
function AttacherJoints:loadAttachmentsFromXMLFile() end
function AttacherJoints:attachableRemoveToolCameras() end
function AttacherJoints:getIsReadyForAutomatedTrainTravel() end
function AttacherJoints:registerEvents() end
function AttacherJoints:registerOverwrittenFunctions() end
function AttacherJoints:registerSelectableObjects() end
function AttacherJoints:attachableAddToolCameras() end
function AttacherJoints:getFillLevelInformation() end
function AttacherJoints:getAttacherJointIndexFromObject() end
function AttacherJoints:saveToXMLFile() end
function AttacherJoints:getAICollisionTriggers() end
function AttacherJoints:getChildVehicles() end
function AttacherJoints:onUpdate() end
function AttacherJoints:addVehicleToAIImplementList() end
function AttacherJoints:getAirConsumerUsage() end
function AttacherJoints:addToPhysics() end
function AttacherJoints:deactivateAttachments() end
function AttacherJoints:detachImplementByObject() end
function AttacherJoints:onRegisterActionEvents() end
function AttacherJoints:getIsHardAttachAllowed() end
function AttacherJoints:removeActionEvents() end
function AttacherJoints:loadDashboardGroupFromXML() end
function AttacherJoints:onUpdateTick() end
function AttacherJoints:getImplementIndexByObject() end
function AttacherJoints:startAttacherJointCombo() end
function AttacherJoints:registerEventListeners() end
function AttacherJoints:onWriteStream() end
function AttacherJoints:postAttachImplement() end
function AttacherJoints:onBeaconLightsVisibilityChanged() end
function AttacherJoints:calculateAttacherJointMoveUpperLowerAlpha() end
function AttacherJoints:isDetachAllowed() end
function AttacherJoints:getImplementByJointDescIndex() end
function AttacherJoints:onReadStream() end
function AttacherJoints:getIsDashboardGroupActive() end
function AttacherJoints:getAttachedImplements() end
function AttacherJoints:getAttacherJointDescFromObject() end
function AttacherJoints:getImplementFromAttacherJointIndex() end
function AttacherJoints:getImplementIndexByJointDescIndex() end