BaleLoader = {}

BaleLoader.EMPTY_WAIT_TO_DROP = 9
BaleLoader.EMPTY_SINK = 11
BaleLoader.EMPTY_WAIT_TO_SINK = 10
BaleLoader.CHANGE_EMPTY_HIDE_PUSHER1 = 17
BaleLoader.CHANGE_BUTTON_EMPTY = 23
BaleLoader.CHANGE_EMPTY_WAIT_TO_REDO = 22
BaleLoader.CHANGE_MOVE_TO_WORK = 6
BaleLoader.CHANGE_MOVE_TO_TRANSPORT = 7
BaleLoader.CHANGE_EMPTY_STATE_NIL = 21
BaleLoader.CHANGE_DROP_BALES = 1
BaleLoader.CHANGE_EMPTY_WAIT_TO_DROP = 20
BaleLoader.CHANGE_EMPTY_ROTATE1 = 15
BaleLoader.CHANGE_ROTATE_PLATFORM = 13
BaleLoader.CHANGE_BUTTON_EMPTY_ABORT = 24
BaleLoader.GRAB_DROP_BALE = 3
BaleLoader.GRAB_MOVE_DOWN = 2
BaleLoader.CHANGE_BUTTON_WORK_TRANSPORT = 25
BaleLoader.EMPTY_ROTATE_PLATFORM = 3
BaleLoader.CHANGE_EMPTY_CLOSE_GRIPPERS = 16
BaleLoader.CHANGE_EMPTY_REDO = 3
BaleLoader.EMPTY_CANCEL = 12
BaleLoader.EMPTY_ROTATE1 = 4
BaleLoader.CHANGE_EMPTY_START = 4
BaleLoader.CHANGE_SINK = 2
BaleLoader.GRAB_MOVE_UP = 1
BaleLoader.CHANGE_GRAB_DROP_BALE = 10
BaleLoader.CHANGE_EMPTY_CANCEL = 5
BaleLoader.EMPTY_WAIT_TO_REDO = 13
BaleLoader.CHANGE_GRAB_MOVE_UP = 9
BaleLoader.CHANGE_GRAB_MOVE_DOWN = 11
BaleLoader.CHANGE_EMPTY_ROTATE2 = 19
BaleLoader.EMPTY_ROTATE2 = 8
BaleLoader.EMPTY_NONE = 1
BaleLoader.EMPTY_HIDE_PUSHER1 = 6
BaleLoader.CHANGE_EMPTY_HIDE_PUSHER2 = 18
BaleLoader.CHANGE_FRONT_PUSHER = 12
BaleLoader.EMPTY_HIDE_PUSHER2 = 7
BaleLoader.CHANGE_GRAB_BALE = 8
BaleLoader.EMPTY_CLOSE_GRIPPERS = 5
BaleLoader.CHANGE_EMPTY_ROTATE_PLATFORM = 14
BaleLoader.EMPTY_TO_WORK = 2

function BaleLoader:moveToTransportPosition() end
function BaleLoader:prerequisitesPresent() end
function BaleLoader:onReadStream() end
function BaleLoader:getAllowDynamicMountFillLevelInfo() end
function BaleLoader:getIsBaleGrabbingAllowed() end
function BaleLoader:unmountDynamicBale() end
function BaleLoader:doStateChange() end
function BaleLoader:actionEventAbortEmpty() end
function BaleLoader:onPostLoad() end
function BaleLoader:getAllowsStartUnloading() end
function BaleLoader:addNodeObjectMapping() end
function BaleLoader:registerFunctions() end
function BaleLoader:getCanBeSelected() end
function BaleLoader:rotatePlatform() end
function BaleLoader:registerOverwrittenFunctions() end
function BaleLoader:actionEventWorkTransport() end
function BaleLoader:getBaleInRange() end
function BaleLoader:mountDynamicBale() end
function BaleLoader:removeNodeObjectMapping() end
function BaleLoader:saveToXMLFile() end
function BaleLoader:actionEventEmpty() end
function BaleLoader:onUpdate() end
function BaleLoader:getBaleGrabberDropBaleAnimName() end
function BaleLoader:onDelete() end
function BaleLoader:onRegisterActionEvents() end
function BaleLoader:onLoad() end
function BaleLoader:updateBalePlacesAnimations() end
function BaleLoader:moveToWorkPosition() end
function BaleLoader:pickupBale() end
function BaleLoader:onUpdateTick() end
function BaleLoader:onWriteStream() end
function BaleLoader:registerEventListeners() end
function BaleLoader:baleGrabberTriggerCallback() end
function BaleLoader:onDeactivate() end