BaleWrapper = {}

BaleWrapper.STATE_NUM_BITS = 3
BaleWrapper.STATE_MOVING_GRABBER_TO_WORK = 2
BaleWrapper.STATE_WRAPPER_FINSIHED = 4
BaleWrapper.STATE_WRAPPER_RESETTING_PLATFORM = 6
BaleWrapper.STATE_NONE = 0
BaleWrapper.STATE_WRAPPER_WRAPPING_BALE = 3
BaleWrapper.STATE_WRAPPER_DROPPING_BALE = 5
BaleWrapper.STATE_MOVING_BALE_TO_WRAPPER = 1
BaleWrapper.CHANGE_WRAPPER_START_DROP_BALE = 5
BaleWrapper.CHANGE_DROP_BALE_AT_GRABBER = 2
BaleWrapper.CHANGE_WRAPPER_PLATFORM_RESET = 7
BaleWrapper.CHANGE_BUTTON_EMPTY = 8
BaleWrapper.CHANGE_GRAB_BALE = 1
BaleWrapper.CHANGE_WRAPPER_BALE_DROPPED = 6
BaleWrapper.CHANGE_WRAPPING_BALE_FINSIHED = 4
BaleWrapper.CHANGE_WRAPPING_START = 3

function BaleWrapper:playMoveToWrapper() end
function BaleWrapper:registerFunctions() end
function BaleWrapper:onDeactivate() end
function BaleWrapper:prerequisitesPresent() end
function BaleWrapper:onDelete() end
function BaleWrapper:onReadStream() end
function BaleWrapper:getCanBeSelected() end
function BaleWrapper:registerOverwrittenFunctions() end
function BaleWrapper:getBaleInRange() end
function BaleWrapper:updateWrapNodes() end
function BaleWrapper:getIsFoldAllowed() end
function BaleWrapper:saveToXMLFile() end
function BaleWrapper:onUpdate() end
function BaleWrapper:onLoad() end
function BaleWrapper:updateWrappingState() end
function BaleWrapper:allowsGrabbingBale() end
function BaleWrapper:registerEventListeners() end
function BaleWrapper:onUpdateTick() end
function BaleWrapper:doStateChange() end
function BaleWrapper:onWriteStream() end
function BaleWrapper:actionEventEmpty() end
function BaleWrapper:getIsBaleFillTypeSkiped() end
function BaleWrapper:onRegisterActionEvents() end
function BaleWrapper:onDraw() end
function BaleWrapper:onPostLoad() end
function BaleWrapper:loadWrapperFromXML() end
function BaleWrapper:pickupWrapperBale() end
function BaleWrapper:getWrapperBaleType() end
function BaleWrapper:initSpecialization() end