Baler = {}

Baler.UNLOADING_CLOSED = 1
Baler.UNLOADING_OPEN = 3
Baler.UNLOADING_OPENING = 2
Baler.UNLOADING_CLOSING = 4

function Baler:registerFunctions() end
function Baler:onEndWorkAreaProcessing() end
function Baler:onDeactivate() end
function Baler:setBaleTime() end
function Baler:onDelete() end
function Baler:onReadStream() end
function Baler:onWriteUpdateStream() end
function Baler:getDefaultSpeedLimit() end
function Baler:dropBale() end
function Baler:processBalerArea() end
function Baler:createBale() end
function Baler:registerOverwrittenFunctions() end
function Baler:moveBale() end
function Baler:saveToXMLFile() end
function Baler:onTurnedOff() end
function Baler:isUnloadingAllowed() end
function Baler:onUpdate() end
function Baler:getIsSpeedRotatingPartActive() end
function Baler:onLoad() end
function Baler:getConsumingLoad() end
function Baler:onRegisterActionEvents() end
function Baler:finishBale() end
function Baler:registerEventListeners() end
function Baler:getCanBeTurnedOn() end
function Baler:actionEventUnloading() end
function Baler:onReadUpdateStream() end
function Baler:initSpecialization() end
function Baler:onStartWorkAreaProcessing() end
function Baler:getCanBeSelected() end
function Baler:setIsUnloadingBale() end
function Baler:getIsWorkAreaActive() end
function Baler:loadSpeedRotatingPartFromXML() end
function Baler:onFillUnitFillLevelChanged() end
function Baler:onTurnedOn() end
function Baler:moveBales() end
function Baler:prerequisitesPresent() end
function Baler:onPostLoad() end
function Baler:getIsFoldAllowed() end
function Baler:onUpdateTick() end
function Baler:getCanUnloadUnfinishedBale() end
function Baler:doCheckSpeedLimit() end
function Baler:onWriteStream() end
function Baler:getTimeFromLevel() end