ConnectionHoses = {}

function ConnectionHoses:connectHoseToSkipNode() end
function ConnectionHoses:updateToolConnectionHose() end
function ConnectionHoses:connectHosesToAttacherVehicle() end
function ConnectionHoses:registerFunctions() end
function ConnectionHoses:getConnectionTarget() end
function ConnectionHoses:getCenterPointAngleRegulation() end
function ConnectionHoses:prerequisitesPresent() end
function ConnectionHoses:onPreDetach() end
function ConnectionHoses:getIsConnectionTargetUsed() end
function ConnectionHoses:loadHoseSkipNode() end
function ConnectionHoses:onPostAttach() end
function ConnectionHoses:retryHoseSkipNodeConnections() end
function ConnectionHoses:getIsConnectionHoseUsed() end
function ConnectionHoses:getCenterPointAngle() end
function ConnectionHoses:connectHose() end
function ConnectionHoses:getIsSkipNodeAvailable() end
function ConnectionHoses:getConnectionHosesByInputAttacherJoint() end
function ConnectionHoses:loadToolConnectorHoseNode() end
function ConnectionHoses:disconnectHose() end
function ConnectionHoses:addHoseToDelayedMountings() end
function ConnectionHoses:loadHoseTargetNode() end
function ConnectionHoses:loadHoseNode() end
function ConnectionHoses:addHoseTargetNodes() end
function ConnectionHoses:onPreUpdate() end
function ConnectionHoses:getClonedSkipHoseNode() end
function ConnectionHoses:registerEventListeners() end
function ConnectionHoses:onLoad() end