Cultivator = {}

function Cultivator:registerEventListeners() end
function Cultivator:onEndWorkAreaProcessing() end
function Cultivator:onDeactivate() end
function Cultivator:prerequisitesPresent() end
function Cultivator:onDelete() end
function Cultivator:getDoGroundManipulation() end
function Cultivator:loadWorkAreaFromXML() end
function Cultivator:onPreDetach() end
function Cultivator:getDirtMultiplier() end
function Cultivator:onStartWorkAreaProcessing() end
function Cultivator:registerOverwrittenFunctions() end
function Cultivator:getWearMultiplier() end
function Cultivator:getDefaultSpeedLimit() end
function Cultivator:onLoad() end
function Cultivator:initSpecialization() end
function Cultivator:getIsWorkAreaActive() end
function Cultivator:doCheckSpeedLimit() end
function Cultivator:registerFunctions() end
function Cultivator:processCultivatorArea() end
function Cultivator:onPostAttach() end