Cylindered = {}

function Cylindered:loadDependentParts() end
function Cylindered:onDeactivate() end
function Cylindered:prerequisitesPresent() end
function Cylindered:loadDependentWheels() end
function Cylindered:onReadStream() end
function Cylindered:onWriteUpdateStream() end
function Cylindered:loadDependentTranslatingParts() end
function Cylindered:setObjectChangeValues() end
function Cylindered:setToolRotation() end
function Cylindered:onLoadFinished() end
function Cylindered:allowLoadMovingToolStates() end
function Cylindered:onLoad() end
function Cylindered:loadDependentMovingTools() end
function Cylindered:updateDependentAnimations() end
function Cylindered:loadDependentAnimations() end
function Cylindered:loadMovingPartFromXML() end
function Cylindered:updateWheels() end
function Cylindered:updateRotationBasedLimits() end
function Cylindered:setIsEasyControlActive() end
function Cylindered:loadDependentComponentJoints() end
function Cylindered:onUnselect() end
function Cylindered:setComponentJointFrame() end
function Cylindered:onDraw() end
function Cylindered:onPostLoad() end
function Cylindered:limitInterpolator() end
function Cylindered:getShovelNodeIsActive() end
function Cylindered:onPostAttach() end
function Cylindered:updateCylinderedInitial() end
function Cylindered:loadDependentAttacherJoints() end
function Cylindered:updateDelayedTool() end
function Cylindered:registerFunctions() end
function Cylindered:onPostUpdate() end
function Cylindered:getIsMovingToolActive() end
function Cylindered:onSelect() end
function Cylindered:getIsDynamicMountGrabOpened() end
function Cylindered:onDelete() end
function Cylindered:loadShovelNode() end
function Cylindered:registerEvents() end
function Cylindered:registerOverwrittenFunctions() end
function Cylindered:setDirty() end
function Cylindered:getWearMultiplier() end
function Cylindered:getMovingToolState() end
function Cylindered:updateExtraDependentParts() end
function Cylindered:onUpdate() end
function Cylindered:movingToolDashboardAttributes() end
function Cylindered:onRegisterActionEvents() end
function Cylindered:getDischargeNodeEmptyFactor() end
function Cylindered:updateComponentJoints() end
function Cylindered:registerEventListeners() end
function Cylindered:actionEventInput() end
function Cylindered:updateAttacherJoints() end
function Cylindered:onReadUpdateStream() end
function Cylindered:onUpdateTick() end
function Cylindered:updateMovingPart() end
function Cylindered:getMovingToolDashboardState() end
function Cylindered:setToolAnimation() end
function Cylindered:loadObjectChangeValuesFromXML() end
function Cylindered:onWriteStream() end
function Cylindered:setMovingToolDirty() end
function Cylindered:loadMovingToolFromXML() end
function Cylindered:loadExtraDependentParts() end
function Cylindered:getMovingPartByNode() end
function Cylindered:loadCopyLocalDirectionParts() end
function Cylindered:isDetachAllowed() end
function Cylindered:updateEasyControl() end
function Cylindered:getMovingToolByNode() end
function Cylindered:saveToXMLFile() end
function Cylindered:setDelayedData() end
function Cylindered:loadRotationBasedLimits() end
function Cylindered:loadDischargeNode() end
function Cylindered:loadDynamicMountGrabFromXML() end
function Cylindered:getAdditionalSchemaText() end
function Cylindered:setToolTranslation() end