DynamicMountAttacher = {}

function DynamicMountAttacher:getAllowDynamicMountObjects() end
function DynamicMountAttacher:registerFunctions() end
function DynamicMountAttacher:addDynamicMountedObject() end
function DynamicMountAttacher:onUpdateTick() end
function DynamicMountAttacher:onDelete() end
function DynamicMountAttacher:onWriteUpdateStream() end
function DynamicMountAttacher:updateExtraDependentParts() end
function DynamicMountAttacher:dynamicMountTriggerCallback() end
function DynamicMountAttacher:removeDynamicMountedObject() end
function DynamicMountAttacher:loadExtraDependentParts() end
function DynamicMountAttacher:registerOverwrittenFunctions() end
function DynamicMountAttacher:registerEventListeners() end
function DynamicMountAttacher:removeNodeObjectMapping() end
function DynamicMountAttacher:setDynamicMountAnimationState() end
function DynamicMountAttacher:getFillLevelInformation() end
function DynamicMountAttacher:getAllowDynamicMountFillLevelInfo() end
function DynamicMountAttacher:loadDynamicMountGrabFromXML() end
function DynamicMountAttacher:getIsDynamicMountGrabOpened() end
function DynamicMountAttacher:onReadUpdateStream() end
function DynamicMountAttacher:addNodeObjectMapping() end
function DynamicMountAttacher:prerequisitesPresent() end
function DynamicMountAttacher:onLoad() end