FoliageBending = {}

function FoliageBending:onFinishedWheelLoading() end
function FoliageBending:postInitializeAnimationPart() end
function FoliageBending:deactivateBendingNodes() end
function FoliageBending:registerEventListeners() end
function FoliageBending:onDeactivate() end
function FoliageBending:prerequisitesPresent() end
function FoliageBending:onDelete() end
function FoliageBending:initializeAnimationPart() end
function FoliageBending:getFoliageBendingNodeByIndex() end
function FoliageBending:loadBendingNodeFromXML() end
function FoliageBending:resetAnimationPartValues() end
function FoliageBending:updateAnimationPart() end
function FoliageBending:onPostLoad() end
function FoliageBending:onActivate() end
function FoliageBending:activateBendingNodes() end
function FoliageBending:loadAnimationPart() end
function FoliageBending:registerFunctions() end
function FoliageBending:registerOverwrittenFunctions() end
function FoliageBending:loadBendingNodeModifierFromXML() end
function FoliageBending:updateFoliageBendingAttributes() end
function FoliageBending:onLoad() end