FruitPreparer = {}

function FruitPreparer:getAllowCutterAIFruitRequirements() end
function FruitPreparer:registerFunctions() end
function FruitPreparer:onReadUpdateStream() end
function FruitPreparer:prerequisitesPresent() end
function FruitPreparer:initSpecialization() end
function FruitPreparer:getDoGroundManipulation() end
function FruitPreparer:onWriteUpdateStream() end
function FruitPreparer:loadWorkAreaFromXML() end
function FruitPreparer:getDirtMultiplier() end
function FruitPreparer:onStartWorkAreaProcessing() end
function FruitPreparer:registerOverwrittenFunctions() end
function FruitPreparer:getWearMultiplier() end
function FruitPreparer:onTurnedOn() end
function FruitPreparer:processFruitPreparerArea() end
function FruitPreparer:getDefaultSpeedLimit() end
function FruitPreparer:doCheckSpeedLimit() end
function FruitPreparer:onTurnedOff() end
function FruitPreparer:onDelete() end
function FruitPreparer:registerEventListeners() end
function FruitPreparer:onLoad() end