HookLiftTrailer = {}

function HookLiftTrailer:onPreDetachImplement() end
function HookLiftTrailer:getIsTippingAllowed() end
function HookLiftTrailer:stopTipping() end
function HookLiftTrailer:registerEventListeners() end
function HookLiftTrailer:onUpdateTick() end
function HookLiftTrailer:onPostAttachImplement() end
function HookLiftTrailer:getPtoRpm() end
function HookLiftTrailer:getDoConsumePtoPower() end
function HookLiftTrailer:getCanDetachContainer() end
function HookLiftTrailer:isDetachAllowed() end
function HookLiftTrailer:onPostLoad() end
function HookLiftTrailer:getIsFoldAllowed() end
function HookLiftTrailer:registerOverwrittenFunctions() end
function HookLiftTrailer:prerequisitesPresent() end
function HookLiftTrailer:registerFunctions() end
function HookLiftTrailer:startTipping() end
function HookLiftTrailer:onLoad() end