Lights = {}

Lights.turnLightSendNumBits = 3
Lights.TURNLIGHT_OFF = 0
Lights.TURNLIGHT_LEFT = 1
Lights.TURNLIGHT_RIGHT = 2
Lights.TURNLIGHT_HAZARD = 3

function Lights:loadSharedLight() end
function Lights:actionEventToggleTurnLightRight() end
function Lights:dashboardLightState() end
function Lights:registerFunctions() end
function Lights:loadRealLights() end
function Lights:actionEventToggleTurnLightHazard() end
function Lights:prerequisitesPresent() end
function Lights:onDelete() end
function Lights:onReadStream() end
function Lights:getLightsTypesMask() end
function Lights:getTurnLightState() end
function Lights:getUseHighProfile() end
function Lights:registerEvents() end
function Lights:getCanToggleLight() end
function Lights:dashboardLightAttributes() end
function Lights:actionEventToggleBeaconLights() end
function Lights:getBeaconLightsVisibility() end
function Lights:actionEventToggleTurnLightLeft() end
function Lights:setInteriorLightsVisibility() end
function Lights:actionEventToggleHighBeamLight() end
function Lights:actionEventToggleWorkLightFront() end
function Lights:setBrakeLightsVisibility() end
function Lights:actionEventToggleWorkLightBack() end
function Lights:onLoad() end
function Lights:deactivateLights() end
function Lights:actionEventToggleLightFront() end
function Lights:loadVisualLights() end
function Lights:onRegisterActionEvents() end
function Lights:onAIContinue() end
function Lights:loadRealLightSetup() end
function Lights:registerEventListeners() end
function Lights:onAIBlock() end
function Lights:onReadUpdateStream() end
function Lights:onUpdateTick() end
function Lights:onUpdate() end
function Lights:setTurnLightState() end
function Lights:onPostDetach() end
function Lights:setReverseLightsVisibility() end
function Lights:onWriteStream() end
function Lights:onAutomatedTrainTravelActive() end
function Lights:setLightsTypesMask() end
function Lights:setBeaconLightsVisibility() end
function Lights:onStartReverseDirectionChange() end
function Lights:onEnterVehicle() end
function Lights:updateAILights() end
function Lights:onAIActive() end
function Lights:getIsActiveForLights() end
function Lights:setNextLightsState() end
function Lights:actionEventToggleLights() end
function Lights:onStopMotor() end
function Lights:onWriteUpdateStream() end
function Lights:onPostAttach() end