LivestockTrailer = {}

function LivestockTrailer:getAnimals() end
function LivestockTrailer:registerFunctions() end
function LivestockTrailer:getSpecValueNumberAnimalsCow() end
function LivestockTrailer:prerequisitesPresent() end
function LivestockTrailer:getAnimalPlaces() end
function LivestockTrailer:getSpecValueNumberAnimals() end
function LivestockTrailer:onWriteUpdateStream() end
function LivestockTrailer:getCurrentAnimalType() end
function LivestockTrailer:registerOverwrittenFunctions() end
function LivestockTrailer:removeAnimal() end
function LivestockTrailer:onLoadFinished() end
function LivestockTrailer:getSpecValueNumberAnimalsPig() end
function LivestockTrailer:addAnimal() end
function LivestockTrailer:onLoad() end
function LivestockTrailer:setLoadingTrigger() end
function LivestockTrailer:registerEventListeners() end
function LivestockTrailer:onReadUpdateStream() end
function LivestockTrailer:initSpecialization() end
function LivestockTrailer:loadSpecValueNumberAnimalsPig() end
function LivestockTrailer:onWriteStream() end
function LivestockTrailer:getSupportsAnimalType() end
function LivestockTrailer:addAnimals() end
function LivestockTrailer:getSpecValueNumberAnimalsHorse() end
function LivestockTrailer:getSpecValueNumberAnimalsSheep() end
function LivestockTrailer:getAdditionalComponentMass() end
function LivestockTrailer:onUpdate() end
function LivestockTrailer:loadSpecValueNumberAnimalsCow() end
function LivestockTrailer:loadSpecValueNumberAnimals() end
function LivestockTrailer:onDelete() end
function LivestockTrailer:saveToXMLFile() end
function LivestockTrailer:removeAnimals() end
function LivestockTrailer:onReadStream() end
function LivestockTrailer:loadSpecValueNumberAnimalsHorse() end
function LivestockTrailer:loadSpecValueNumberAnimalsSheep() end