Mountable = {}

function Mountable:unmount() end
function Mountable:getIsActive() end
function Mountable:getOwner() end
function Mountable:getDynamicMountObject() end
function Mountable:registerEventListeners() end
function Mountable:getSupportsMountDynamic() end
function Mountable:unmountDynamic() end
function Mountable:onDelete() end
function Mountable:getMountObject() end
function Mountable:mountableTriggerCallback() end
function Mountable:mountDynamic() end
function Mountable:registerOverwrittenFunctions() end
function Mountable:onPostAttach() end
function Mountable:onDynamicMountJointBreak() end
function Mountable:onEnterVehicle() end
function Mountable:prerequisitesPresent() end
function Mountable:registerFunctions() end
function Mountable:getRootVehicle() end
function Mountable:mount() end
function Mountable:onLoad() end