Mower = {}

function Mower:processDropArea() end
function Mower:updateActionEventToggleDrop() end
function Mower:onRegisterActionEvents() end
function Mower:onDelete() end
function Mower:getDefaultSpeedLimit() end
function Mower:registerEventListeners() end
function Mower:onEndWorkAreaProcessing() end
function Mower:getMowerLoadPercentage() end
function Mower:onReadUpdateStream() end
function Mower:prerequisitesPresent() end
function Mower:initSpecialization() end
function Mower:onReadStream() end
function Mower:onWriteUpdateStream() end
function Mower:loadWorkAreaFromXML() end
function Mower:onWriteStream() end
function Mower:setDropEffectEnabled() end
function Mower:getDirtMultiplier() end
function Mower:onStartWorkAreaProcessing() end
function Mower:registerOverwrittenFunctions() end
function Mower:onTurnedOff() end
function Mower:getWearMultiplier() end
function Mower:setUseMowerWindrowDropAreas() end
function Mower:onTurnedOn() end
function Mower:getCanBeSelected() end
function Mower:onLoad() end
function Mower:doCheckSpeedLimit() end
function Mower:actionEventToggleDrop() end
function Mower:registerFunctions() end
function Mower:processMowerArea() end
function Mower:getDropArea() end