Pickup = {}

function Pickup:allowPickingUp() end
function Pickup:registerFunctions() end
function Pickup:onSetLoweredAll() end
function Pickup:prerequisitesPresent() end
function Pickup:onReadStream() end
function Pickup:registerLoweringActionEvent() end
function Pickup:onWriteStream() end
function Pickup:getDirtMultiplier() end
function Pickup:registerOverwrittenFunctions() end
function Pickup:getWearMultiplier() end
function Pickup:onPostLoad() end
function Pickup:getIsLowered() end
function Pickup:actionEventTogglePickup() end
function Pickup:updateActionEvents() end
function Pickup:setPickupState() end
function Pickup:getCanChangePickupState() end
function Pickup:registerEventListeners() end
function Pickup:onLoad() end