Pipe = {}

function Pipe:getPipeDischargeNodeIndex() end
function Pipe:loadCoverFromXML() end
function Pipe:getIsDischargeNodeActive() end
function Pipe:registerFunctions() end
function Pipe:updateBendingRegulationNodes() end
function Pipe:getIsMovingToolActive() end
function Pipe:prerequisitesPresent() end
function Pipe:onDelete() end
function Pipe:onReadStream() end
function Pipe:onWriteUpdateStream() end
function Pipe:getIsNextCoverStateAllowed() end
function Pipe:loadMovingToolFromXML() end
function Pipe:registerOverwrittenFunctions() end
function Pipe:getIsFoldAllowed() end
function Pipe:getIsPipeStateChangeAllowed() end
function Pipe:saveToXMLFile() end
function Pipe:unloadingTriggerCallback() end
function Pipe:onUpdate() end
function Pipe:updateActionEventText() end
function Pipe:onLoad() end
function Pipe:loadPipeNodes() end
function Pipe:onRegisterActionEvents() end
function Pipe:registerEventListeners() end
function Pipe:getCanToggleDischargeToObject() end
function Pipe:onReadUpdateStream() end
function Pipe:onUpdateTick() end
function Pipe:handleDischarge() end
function Pipe:handleDischargeRaycast() end
function Pipe:onWriteStream() end
function Pipe:onDischargeStateChanged() end
function Pipe:actionEventTogglePipe() end
function Pipe:updateNearestObjectInTriggers() end
function Pipe:onMovingToolChanged() end
function Pipe:onPostLoad() end
function Pipe:getCanBeSelected() end
function Pipe:onDeletePipeObject() end
function Pipe:updatePipeNodes() end
function Pipe:initSpecialization() end
function Pipe:getCanBeTurnedOn() end
function Pipe:setPipeState() end
function Pipe:loadUnloadingTriggers() end
function Pipe:getTurnedOnNotAllowedWarning() end