Plow = {}

function Plow:onStartAnimation() end
function Plow:registerFunctions() end
function Plow:onEndWorkAreaProcessing() end
function Plow:onFinishAnimation() end
function Plow:onDeactivate() end
function Plow:setPlowLimitToField() end
function Plow:onDelete() end
function Plow:onReadStream() end
function Plow:getCanBeSelected() end
function Plow:setRotationMax() end
function Plow:registerOverwrittenFunctions() end
function Plow:getWearMultiplier() end
function Plow:getIsFoldAllowed() end
function Plow:saveToXMLFile() end
function Plow:onUpdate() end
function Plow:getIsSpeedRotatingPartActive() end
function Plow:onLoad() end
function Plow:getSpeedRotatingPartDirection() end
function Plow:onRegisterActionEvents() end
function Plow:onAIImplementTurnProgress() end
function Plow:registerEventListeners() end
function Plow:actionEventLimitToField() end
function Plow:initSpecialization() end
function Plow:actionEventTurn() end
function Plow:getAIInvertMarkersOnTurn() end
function Plow:onPreDetach() end
function Plow:getIsFoldMiddleAllowed() end
function Plow:loadSpeedRotatingPartFromXML() end
function Plow:getDirtMultiplier() end
function Plow:getCanAIImplementContinueWork() end
function Plow:onStartWorkAreaProcessing() end
function Plow:prerequisitesPresent() end
function Plow:processPlowArea() end
function Plow:onPostLoad() end
function Plow:doCheckSpeedLimit() end
function Plow:getIsPlowRotationAllowed() end
function Plow:setRotationCenter() end
function Plow:getIsWorkAreaActive() end
function Plow:onWriteStream() end
function Plow:loadWorkAreaFromXML() end
function Plow:getDefaultSpeedLimit() end
function Plow:onPostAttach() end