PowerTakeOffs = {}

function PowerTakeOffs:detachPowerTakeOff() end
function PowerTakeOffs:placeLocalPowerTakeOff() end
function PowerTakeOffs:registerFunctions() end
function PowerTakeOffs:loadInputPowerTakeOff() end
function PowerTakeOffs:prerequisitesPresent() end
function PowerTakeOffs:onDelete() end
function PowerTakeOffs:loadBasicPowerTakeOff() end
function PowerTakeOffs:getInputPowerTakeOffsByJointDescIndexAndName() end
function PowerTakeOffs:getIsPowerTakeOffActive() end
function PowerTakeOffs:registerOverwrittenFunctions() end
function PowerTakeOffs:updateSingleJointPowerTakeOff() end
function PowerTakeOffs:parkPowerTakeOff() end
function PowerTakeOffs:getInputPowerTakeOffs() end
function PowerTakeOffs:updatePowerTakeOff() end
function PowerTakeOffs:onLoad() end
function PowerTakeOffs:updateDoubleJointPowerTakeOff() end
function PowerTakeOffs:updateDistanceOfTypedPowerTakeOff() end
function PowerTakeOffs:registerEventListeners() end
function PowerTakeOffs:updateExtraDependentParts() end
function PowerTakeOffs:initSpecialization() end
function PowerTakeOffs:onLoadFinished() end
function PowerTakeOffs:validatePowerTakeOffAttachment() end
function PowerTakeOffs:detachTypedPowerTakeOff() end
function PowerTakeOffs:onPostAttachImplement() end
function PowerTakeOffs:loadLocalPowerTakeOff() end
function PowerTakeOffs:onPreAttachImplement() end
function PowerTakeOffs:loadExtraDependentParts() end
function PowerTakeOffs:updatePowerTakeOffLength() end
function PowerTakeOffs:loadOutputPowerTakeOff() end
function PowerTakeOffs:getOutputPowerTakeOffsByJointDescIndex() end
function PowerTakeOffs:onPostLoad() end
function PowerTakeOffs:loadDoubleJointPowerTakeOff() end
function PowerTakeOffs:getOutputPowerTakeOffs() end
function PowerTakeOffs:onPreUpdate() end
function PowerTakeOffs:loadSingleJointPowerTakeOff() end
function PowerTakeOffs:attachTypedPowerTakeOff() end
function PowerTakeOffs:onPreDetachImplement() end
function PowerTakeOffs:loadPowerTakeOffFromConfigFile() end
function PowerTakeOffs:attachPowerTakeOff() end