PowerConsumer = {}

function PowerConsumer:getConsumingLoad() end
function PowerConsumer:getMaxPtoRpm() end
function PowerConsumer:getConsumedPtoTorque() end
function PowerConsumer:getTurnedOnNotAllowedWarning() end
function PowerConsumer:getCanBeTurnedOn() end
function PowerConsumer:prerequisitesPresent() end
function PowerConsumer:initSpecialization() end
function PowerConsumer:getTotalConsumedPtoTorque() end
function PowerConsumer:getPtoRpm() end
function PowerConsumer:getDoConsumePtoPower() end
function PowerConsumer:registerOverwrittenFunctions() end
function PowerConsumer:getSpecValueNeededPower() end
function PowerConsumer:loadSpecValueNeededPower() end
function PowerConsumer:loadPowerSetup() end
function PowerConsumer:getPowerMultiplier() end
function PowerConsumer:registerFunctions() end
function PowerConsumer:onUpdate() end
function PowerConsumer:registerEventListeners() end
function PowerConsumer:onLoad() end