Shovel = {}

function Shovel:getDischargeNodeEmptyFactor() end
function Shovel:registerFunctions() end
function Shovel:getCanToggleDischargeToObject() end
function Shovel:onReadUpdateStream() end
function Shovel:onUpdateTick() end
function Shovel:handleDischarge() end
function Shovel:onReadStream() end
function Shovel:onWriteUpdateStream() end
function Shovel:onWriteStream() end
function Shovel:loadShovelNode() end
function Shovel:onDelete() end
function Shovel:registerOverwrittenFunctions() end
function Shovel:getCanShovelAtPosition() end
function Shovel:handleDischargeOnEmpty() end
function Shovel:getWearMultiplier() end
function Shovel:getShovelTipFactor() end
function Shovel:getCanToggleDischargeToGround() end
function Shovel:handleDischargeRaycast() end
function Shovel:registerEventListeners() end
function Shovel:updateDebugValues() end
function Shovel:prerequisitesPresent() end
function Shovel:getShovelNodeIsActive() end
function Shovel:onLoad() end