Sprayer = {}

function Sprayer:getSprayerFillUnitIndex() end
function Sprayer:getAIRequiresTurnOffOnHeadland() end
function Sprayer:registerFunctions() end
function Sprayer:onEndWorkAreaProcessing() end
function Sprayer:getDrawFirstFillText() end
function Sprayer:prerequisitesPresent() end
function Sprayer:onDelete() end
function Sprayer:loadWorkAreaFromXML() end
function Sprayer:getAISizeMarkers() end
function Sprayer:registerEvents() end
function Sprayer:registerOverwrittenFunctions() end
function Sprayer:getWearMultiplier() end
function Sprayer:onTurnedOn() end
function Sprayer:onTurnedOff() end
function Sprayer:processSprayerArea() end
function Sprayer:getCanToggleTurnedOn() end
function Sprayer:onLoad() end
function Sprayer:setSprayerAITerrainDetailProhibitedRange() end
function Sprayer:getAIImplementCollisionTriggers() end
function Sprayer:onSprayTypeChange() end
function Sprayer:getActiveSprayType() end
function Sprayer:registerEventListeners() end
function Sprayer:getCanBeTurnedOn() end
function Sprayer:getUseSprayerAIRequirements() end
function Sprayer:onUpdateTick() end
function Sprayer:initSpecialization() end
function Sprayer:getAIMarkers() end
function Sprayer:getSprayerUsage() end
function Sprayer:getDefaultSpeedLimit() end
function Sprayer:getDirtMultiplier() end
function Sprayer:onStartWorkAreaProcessing() end
function Sprayer:onAIImplementEnd() end
function Sprayer:onFillUnitFillLevelChanged() end
function Sprayer:getIsSprayTypeActive() end
function Sprayer:onSetLowered() end
function Sprayer:loadSprayTypeFromXML() end
function Sprayer:onStateChange() end
function Sprayer:getExternalFill() end
function Sprayer:doCheckSpeedLimit() end
function Sprayer:onPreDetach() end
function Sprayer:getIsWorkAreaActive() end
function Sprayer:getAreEffectsVisible() end
function Sprayer:getFillVolumeUVScrollSpeed() end