Tedder = {}

function Tedder:processDropArea() end
function Tedder:registerFunctions() end
function Tedder:onEndWorkAreaProcessing() end
function Tedder:getDefaultSpeedLimit() end
function Tedder:onReadUpdateStream() end
function Tedder:onUpdateTick() end
function Tedder:initSpecialization() end
function Tedder:onReadStream() end
function Tedder:onWriteUpdateStream() end
function Tedder:loadWorkAreaFromXML() end
function Tedder:onWriteStream() end
function Tedder:onDeactivate() end
function Tedder:getDirtMultiplier() end
function Tedder:onStartWorkAreaProcessing() end
function Tedder:registerOverwrittenFunctions() end
function Tedder:onTurnedOff() end
function Tedder:getWearMultiplier() end
function Tedder:onPostLoad() end
function Tedder:onTurnedOn() end
function Tedder:processTedderArea() end
function Tedder:preprocessTedderArea() end
function Tedder:doCheckSpeedLimit() end
function Tedder:registerEventListeners() end
function Tedder:onDelete() end
function Tedder:prerequisitesPresent() end
function Tedder:onLoad() end