TreePlanter = {}

function TreePlanter:registerFunctions() end
function TreePlanter:palletTriggerCallback() end
function TreePlanter:prerequisitesPresent() end
function TreePlanter:onDelete() end
function TreePlanter:onReadStream() end
function TreePlanter:onWriteUpdateStream() end
function TreePlanter:getCanBeSelected() end
function TreePlanter:setPlantLimitToField() end
function TreePlanter:registerOverwrittenFunctions() end
function TreePlanter:removeNodeObjectMapping() end
function TreePlanter:onTurnedOn() end
function TreePlanter:saveToXMLFile() end
function TreePlanter:onTurnedOff() end
function TreePlanter:onUpdate() end
function TreePlanter:getIsSpeedRotatingPartActive() end
function TreePlanter:onLoad() end
function TreePlanter:onRegisterActionEvents() end
function TreePlanter:createTree() end
function TreePlanter:registerEventListeners() end
function TreePlanter:onReadUpdateStream() end
function TreePlanter:onUpdateTick() end
function TreePlanter:onWriteStream() end
function TreePlanter:getSaplingPalletInRange() end
function TreePlanter:onDeleteTreePlanterObject() end
function TreePlanter:onFillUnitFillLevelChanged() end
function TreePlanter:getDefaultSpeedLimit() end
function TreePlanter:onDraw() end
function TreePlanter:actionEventToggleTreePlanterFieldLimitation() end
function TreePlanter:doCheckSpeedLimit() end
function TreePlanter:getDirtMultiplier() end
function TreePlanter:removeMountedObject() end
function TreePlanter:getIsWorkAreaActive() end
function TreePlanter:getWearMultiplier() end
function TreePlanter:addNodeObjectMapping() end
function TreePlanter:loadPallet() end
function TreePlanter:getIsOnField() end