TurnOnVehicle = {}

function TurnOnVehicle:onAlarmTriggerChanged() end
function TurnOnVehicle:getAIRequiresTurnOffOnHeadland() end
function TurnOnVehicle:registerFunctions() end
function TurnOnVehicle:onAIImplementBlock() end
function TurnOnVehicle:onAIImplementContinue() end
function TurnOnVehicle:prerequisitesPresent() end
function TurnOnVehicle:onDelete() end
function TurnOnVehicle:onReadStream() end
function TurnOnVehicle:getCanBeSelected() end
function TurnOnVehicle:onPreDetach() end
function TurnOnVehicle:loadShovelNode() end
function TurnOnVehicle:registerEvents() end
function TurnOnVehicle:registerOverwrittenFunctions() end
function TurnOnVehicle:onTurnedOn() end
function TurnOnVehicle:getIsSeedChangeAllowed() end
function TurnOnVehicle:onAIImplementStartLine() end
function TurnOnVehicle:onTurnedOff() end
function TurnOnVehicle:onUpdate() end
function TurnOnVehicle:getCanToggleTurnedOn() end
function TurnOnVehicle:onLoad() end
function TurnOnVehicle:onRegisterActionEvents() end
function TurnOnVehicle:loadAlarmTrigger() end
function TurnOnVehicle:registerEventListeners() end
function TurnOnVehicle:getCanBeTurnedOn() end
function TurnOnVehicle:actionEventTurnOn() end
function TurnOnVehicle:loadWorkAreaFromXML() end
function TurnOnVehicle:onUpdateTick() end
function TurnOnVehicle:onDeactivate() end
function TurnOnVehicle:onStateChange() end
function TurnOnVehicle:onSetBroken() end
function TurnOnVehicle:setIsTurnedOn() end
function TurnOnVehicle:getAlarmTriggerIsActive() end
function TurnOnVehicle:onAIImplementEndLine() end
function TurnOnVehicle:onAIImplementEnd() end
function TurnOnVehicle:getCanAIImplementContinueWork() end
function TurnOnVehicle:onAIImplementStart() end
function TurnOnVehicle:loadInputAttacherJoint() end
function TurnOnVehicle:getIsPowerTakeOffActive() end
function TurnOnVehicle:getAIRequiresTurnOn() end
function TurnOnVehicle:getIsTurnedOn() end
function TurnOnVehicle:getTurnedOnNotAllowedWarning() end
function TurnOnVehicle:getIsFillUnitActive() end
function TurnOnVehicle:getIsWorkAreaActive() end
function TurnOnVehicle:getIsOperating() end
function TurnOnVehicle:onWriteStream() end
function TurnOnVehicle:getShovelNodeIsActive() end
function TurnOnVehicle:onPostAttach() end