Windrower = {}

function Windrower:processDropArea() end
function Windrower:registerEventListeners() end
function Windrower:registerFunctions() end
function Windrower:onEndWorkAreaProcessing() end
function Windrower:loadWorkAreaFromXML() end
function Windrower:onDeactivate() end
function Windrower:onUpdateTick() end
function Windrower:initSpecialization() end
function Windrower:onReadStream() end
function Windrower:onWriteUpdateStream() end
function Windrower:getDefaultSpeedLimit() end
function Windrower:onWriteStream() end
function Windrower:loadRakeFromXML() end
function Windrower:getDirtMultiplier() end
function Windrower:onStartWorkAreaProcessing() end
function Windrower:registerOverwrittenFunctions() end
function Windrower:updateRake() end
function Windrower:getWearMultiplier() end
function Windrower:onPostLoad() end
function Windrower:onTurnedOn() end
function Windrower:doCheckSpeedLimit() end
function Windrower:processWindrowerArea() end
function Windrower:onTurnedOff() end
function Windrower:onDelete() end
function Windrower:prerequisitesPresent() end
function Windrower:onReadUpdateStream() end
function Windrower:onLoad() end