WoodHarvester = {}

function WoodHarvester:cutTree() end
function WoodHarvester:onRegisterActionEvents() end
function WoodHarvester:registerFunctions() end
function WoodHarvester:actionEventSetCutlength() end
function WoodHarvester:onDeactivate() end
function WoodHarvester:onUpdateTick() end
function WoodHarvester:onDelete() end
function WoodHarvester:onReadStream() end
function WoodHarvester:actionEventCutTree() end
function WoodHarvester:getCanBeSelected() end
function WoodHarvester:onWriteStream() end
function WoodHarvester:setLastTreeDiameter() end
function WoodHarvester:onDelimbTree() end
function WoodHarvester:registerEvents() end
function WoodHarvester:registerOverwrittenFunctions() end
function WoodHarvester:woodHarvesterSplitShapeCallback() end
function WoodHarvester:onDraw() end
function WoodHarvester:onPostLoad() end
function WoodHarvester:onTurnedOn() end
function WoodHarvester:onCutTree() end
function WoodHarvester:saveToXMLFile() end
function WoodHarvester:onTurnedOff() end
function WoodHarvester:prerequisitesPresent() end
function WoodHarvester:onUpdate() end
function WoodHarvester:registerEventListeners() end
function WoodHarvester:onLoad() end