WoodCrusher = {}

function WoodCrusher:updateWoodCrusher() end
function WoodCrusher:woodCrusherMoveTriggerCallback() end
function WoodCrusher:registerFunctions() end
function WoodCrusher:getCanBeTurnedOn() end
function WoodCrusher:turnOffWoodCrusher() end
function WoodCrusher:onReadUpdateStream() end
function WoodCrusher:onCrushedSplitShape() end
function WoodCrusher:onDelete() end
function WoodCrusher:deleteWoodCrusher() end
function WoodCrusher:onWriteUpdateStream() end
function WoodCrusher:woodCrusherSplitShapeCallback() end
function WoodCrusher:getDirtMultiplier() end
function WoodCrusher:turnOnWoodCrusher() end
function WoodCrusher:registerOverwrittenFunctions() end
function WoodCrusher:crushSplitShape() end
function WoodCrusher:getWearMultiplier() end
function WoodCrusher:updateTickWoodCrusher() end
function WoodCrusher:onTurnedOn() end
function WoodCrusher:prerequisitesPresent() end
function WoodCrusher:onUpdateTick() end
function WoodCrusher:onTurnedOff() end
function WoodCrusher:loadWoodCrusher() end
function WoodCrusher:onUpdate() end
function WoodCrusher:registerEventListeners() end
function WoodCrusher:onLoad() end