WorkParticles = {}

function WorkParticles:registerFunctions() end
function WorkParticles:loadGroundParticleMapping() end
function WorkParticles:onUpdateTick() end
function WorkParticles:onDelete() end
function WorkParticles:loadGroundReferenceNode() end
function WorkParticles:loadGroundEffects() end
function WorkParticles:getFillTypeFromWorkAreaIndex() end
function WorkParticles:registerOverwrittenFunctions() end
function WorkParticles:updateGroundReferenceNode() end
function WorkParticles:onDeactivate() end
function WorkParticles:registerEventListeners() end
function WorkParticles:loadGroundParticles() end
function WorkParticles:loadGroundAnimations() end
function WorkParticles:prerequisitesPresent() end
function WorkParticles:getDoGroundManipulation() end
function WorkParticles:loadGroundAnimationMapping() end
function WorkParticles:onLoad() end