InGameMenuMultiplayerFarmsFrame = {}

InGameMenuMultiplayerFarmsFrame.PROFILE = {
  FARM_ITEM_SELECTED = 'ingameMenuMPFarmsListItemSelected'
  FARM_ITEM = 'ingameMenuMPFarmsListItem'
}
InGameMenuMultiplayerFarmsFrame.L10N_SYMBOL = {
  WRONG_PASSWORD = 'ui_wrongPassword'
  BUTTON_EDIT_FARM = 'button_mp_editFarm'
  BUTTON_LEAVE_FARM = 'button_mp_leaveFarm'
  BUTTON_CREATE_FARM = 'button_mp_createFarm'
  PLAYER_COUNT = 'ui_players'
  LEAVE_FARM_CONFIRM = 'ui_farmLeaveConfirmation'
  BUTTON_DELETE_FARM = 'button_mp_deleteFarm'
  BUTTON_JOIN_FARM = 'button_mp_joinFarm'
  DELETE_FARM_CONFIRM = 'ui_farmDeleteConfirmation'
}
InGameMenuMultiplayerFarmsFrame.CONTROLS = {
  NO_FARMS_BOX = 'noFarmsBox'
  BUTTON_RIGHT = 'buttonRight'
  BUTTON_LEFT = 'buttonLeft'
  FARM_LIST = 'farmList'
  FARM_ITEM_TEMPLATE = 'listTemplate'
  NEW_FARM_ITEM = 'newFarmItem'
}
InGameMenuMultiplayerFarmsFrame.ELEMENT_NAME = {
  PLAYER_NAME_LAYOUT = 'playerNameLayout'
  FARM_ICON = 'farmIcon'
  PLAYER_NAME_TEMPLATE = 'playerNameTemplate'
  FARM_NAME = 'farmName'
  FARM_BALANCE = 'farmBalance'
  PLAYER_COUNT = 'farmPlayerCount'
}

function InGameMenuMultiplayerFarmsFrame:doLeaveFarm() end
function InGameMenuMultiplayerFarmsFrame:new() end
function InGameMenuMultiplayerFarmsFrame:setPlayer() end
function InGameMenuMultiplayerFarmsFrame:initialize() end
function InGameMenuMultiplayerFarmsFrame:onDeleteFarmYesNo() end
function InGameMenuMultiplayerFarmsFrame:copyAttributes() end
function InGameMenuMultiplayerFarmsFrame:update() end
function InGameMenuMultiplayerFarmsFrame:getListFarmIndex() end
function InGameMenuMultiplayerFarmsFrame:copy() end
function InGameMenuMultiplayerFarmsFrame:deleteFarm() end
function InGameMenuMultiplayerFarmsFrame:joinFarm() end
function InGameMenuMultiplayerFarmsFrame:leaveFarm() end
function InGameMenuMultiplayerFarmsFrame:onFarmsChanged() end
function InGameMenuMultiplayerFarmsFrame:updateFarmList() end
function InGameMenuMultiplayerFarmsFrame:onClickRight() end
function InGameMenuMultiplayerFarmsFrame:onMasterUserAdded() end
function InGameMenuMultiplayerFarmsFrame:onPermissionChanged() end
function InGameMenuMultiplayerFarmsFrame:onScroll() end
function InGameMenuMultiplayerFarmsFrame:onClickLeft() end
function InGameMenuMultiplayerFarmsFrame:onDoubleClickFarm() end
function InGameMenuMultiplayerFarmsFrame:isa() end
function InGameMenuMultiplayerFarmsFrame:onClickFarm() end
function InGameMenuMultiplayerFarmsFrame:onFarmMoneyChanged() end
function InGameMenuMultiplayerFarmsFrame:onSelectionChanged() end
function InGameMenuMultiplayerFarmsFrame:onPlayerSetFarmAnswer() end
function InGameMenuMultiplayerFarmsFrame:superClass() end
function InGameMenuMultiplayerFarmsFrame:onFarmPasswordEntered() end
function InGameMenuMultiplayerFarmsFrame:reset() end
function InGameMenuMultiplayerFarmsFrame:onPlayerFarmChanged() end
function InGameMenuMultiplayerFarmsFrame:createFarm() end
function InGameMenuMultiplayerFarmsFrame:onFrameClose() end
function InGameMenuMultiplayerFarmsFrame:editFarm() end
function InGameMenuMultiplayerFarmsFrame:updateScrollButtons() end
function InGameMenuMultiplayerFarmsFrame:onFrameOpen() end
function InGameMenuMultiplayerFarmsFrame:delete() end
function InGameMenuMultiplayerFarmsFrame:updateFarmPlayers() end
function InGameMenuMultiplayerFarmsFrame:setUsers() end
function InGameMenuMultiplayerFarmsFrame:updateMenuButtons() end
function InGameMenuMultiplayerFarmsFrame:doJoinFarm() end
function InGameMenuMultiplayerFarmsFrame:setFarmBalance() end
function InGameMenuMultiplayerFarmsFrame:setPlayerFarm() end
function InGameMenuMultiplayerFarmsFrame:class() end
function InGameMenuMultiplayerFarmsFrame:buildFarmListItems() end
function InGameMenuMultiplayerFarmsFrame:getMainElementSize() end
function InGameMenuMultiplayerFarmsFrame:setCurrentUserId() end
function InGameMenuMultiplayerFarmsFrame:getMainElementPosition() end
function InGameMenuMultiplayerFarmsFrame:onFarmCreated() end