InGameMenuGeneralSettingsFrame = {}

InGameMenuGeneralSettingsFrame.CONTROLS = {
  OPTION_CAMERA_SENSITIVITY = 'multiCameraSensitivity'
  OPTION_VOLUME_ENVIRONMENT = 'multiEnvironmentVolume'
  CHECKBOX_IS_RADIO_VEHICLE_ONLY = 'checkIsRadioVehicleOnly'
  BOX_LAYOUT = 'boxLayout'
  HELP_BOX_TEXT = 'generalSettingsHelpBoxText'
  OPTION_INPUT_HELP_MODE = 'multiInputHelpMode'
  OPTION_VOLUME_GUI = 'multiVolumeGUI'
  SETTINGS_CONTAINER = 'settingsContainer'
  OPTION_STEERING_BACK_SPEED = 'multiSteeringBackSpeed'
  CHECKBOX_IS_TRAIN_TABBABLE = 'checkIsTrainTabbable'
  CHECKBOX_SHOW_TRIGGER_MARKER = 'checkShowTriggerMarker'
  CHECKBOX_RESET_CAMERA = 'checkResetCamera'
  HELP_BOX = 'generalSettingsHelpBox'
  OPTION_VOLUME_MASTER = 'multiMasterVolume'
  OPTION_MONEY_UNIT = 'multiMoneyUnit'
  OPTION_VOLUME_VEHICLE = 'multiVehicleVolume'
  OPTION_VEHICLE_ARM_SENSITIVITY = 'multiVehicleArmSensitivity'
  CHECKBOX_HELP_ICONS = 'checkHelpIcons'
  BUTTON_NATIVE_HELP = 'buttonNativeHelp'
  CHECKBOX_USE_MILES = 'checkUseMiles'
  OPTION_VOLUME_RADIO = 'multiRadioVolume'
  CHECKBOX_COLORBLIND_MODE = 'checkColorBlindMode'
  CHECKBOX_USE_ACRE = 'checkUseAcre'
  CHECKBOX_INVERT_Y_LOOK = 'checkInvertYLook'
  CHECKBOX_AUTO_HELP = 'checkAutoHelp'
  CHECKBOX_USE_WORLD_CAMERA = 'checkUseWorldCamera'
  CHECKBOX_USE_EASY_ARM_CONTROLER = 'checkUseEasyArmControl'
  CHECKBOX_SHOW_FIELD_INFO = 'checkShowFieldInfo'
  CHECKBOX_IS_RADIO_ACTIVE = 'checkIsRadioActive'
}

function InGameMenuGeneralSettingsFrame:new() end
function InGameMenuGeneralSettingsFrame:updateToolTipBoxVisibility() end
function InGameMenuGeneralSettingsFrame:isa() end
function InGameMenuGeneralSettingsFrame:initialize() end
function InGameMenuGeneralSettingsFrame:updateGeneralSettings() end
function InGameMenuGeneralSettingsFrame:superClass() end
function InGameMenuGeneralSettingsFrame:onClickMultiOption() end
function InGameMenuGeneralSettingsFrame:onFrameClose() end
function InGameMenuGeneralSettingsFrame:copy() end
function InGameMenuGeneralSettingsFrame:getMainElementPosition() end
function InGameMenuGeneralSettingsFrame:onFrameOpen() end
function InGameMenuGeneralSettingsFrame:onClickCheckbox() end
function InGameMenuGeneralSettingsFrame:onClickNativeHelp() end
function InGameMenuGeneralSettingsFrame:onToolTipBoxTextChanged() end
function InGameMenuGeneralSettingsFrame:class() end
function InGameMenuGeneralSettingsFrame:copyAttributes() end
function InGameMenuGeneralSettingsFrame:getMainElementSize() end