InGameMenuMapFrame = {}

InGameMenuMapFrame.HOTSPOT_VALID_CATEGORIES = {
  0 = true
  8 = true
  3 = true
  7 = true
  2 = true
  10 = true
  9 = true
}
InGameMenuMapFrame.CLEAR_INPUT_ACTIONS = {
  1 = 'MENU_ACTIVATE'
  2 = 'MENU_CANCEL'
  3 = 'MENU_EXTRA_1'
  4 = 'MENU_EXTRA_2'
}
InGameMenuMapFrame.FRUIT_TYPE_BUTTON_ELEMENT = {
  TYPE = 'cropTypeFilterText'
  ICON = 'cropTypeFilterIcon'
  COLOR = 'cropTypeFilterColor'
  BUTTON = 'cropTypeFilterButton'
}
InGameMenuMapFrame.MODE_FARMLANDS = 2.000000

InGameMenuMapFrame.PROFILE = {
  MONEY_VALUE_NEUTRAL = 'ingameMenuMapMoneyValue'
  MONEY_VALUE_NEGATIVE = 'ingameMenuMapMoneyValueNegative'
}
InGameMenuMapFrame.L10N_SYMBOL = {
  INPUT_MOVE_CURSOR = 'ui_ingameMenuMapMoveCursor'
  DIALOG_VEHICLE_RESET_DONE = 'ui_vehicleResetDone'
  DIALOG_VEHICLE_RESET_FAILED = 'ui_vehicleResetFailed'
  DIALOG_BUY_FARMLAND_TITLE = 'shop_messageBuyFarmlandTitle'
  MAP_SELECTOR_SOIL_STATES = 'ui_mapOverviewSoil'
  MAP_SELECTOR_FRUIT_TYPES = 'ui_mapOverviewFruitTypes'
  DIALOG_VEHICLE_NO_PERMISSION = 'shop_messageNoPermissionGeneral'
  DIALOG_VEHICLE_RESET_CONFIRM = 'ui_wantToResetVehicleText'
  SWITCH_OVERVIEW = 'ui_ingameMenuMapOverview'
  SET_MARKER = 'action_tag'
  INPUT_PAN_MAP = 'ui_ingameMenuMapPan'
  DIALOG_BUY_FARMLAND_NOT_ENOUGH_MONEY = 'shop_messageNotEnoughMoneyToBuyFarmland'
  DIALOG_SELL_FARMLAND_TITLE = 'shop_messageSellFarmlandTitle'
  DIALOG_CANNOT_SELL_WTIH_PLACEABLES = 'shop_messageCannotSellFarmlandWithPlaceables'
  DIALOG_VEHICLE_IN_USE = 'shop_messageReturnVehicleInUse'
  DIALOG_SELL_FARMLAND = 'shop_messageSellFarmlandText'
  DIALOG_BUY_FARMLAND = 'shop_messageBuyFarmlandText'
  VEHICLE_RESET = 'button_reset'
  SWITCH_FARMLANDS = 'ui_ingameMenuMapFarmlands'
  REMOVE_MARKER = 'action_untag'
  INPUT_ZOOM_MAP = 'ui_ingameMenuMapZoom'
  MAP_SELECTOR_GROWTH_STATES = 'ui_mapOverviewGrowth'
}
InGameMenuMapFrame.CONTEXT_BOX_CORNER_ALIGNMENT = {
  bottomLeft = 'topRight'
  topLeft = 'bottomRight'
  bottomRight = 'topLeft'
  topRight = 'bottomLeft'
}
InGameMenuMapFrame.CONTEXT_BOX_ORIENTATION = {
  TOP_LEFT = 'topLeft'
  BOTTOM_RIGHT = 'bottomRight'
  BOTTOM_LEFT = 'bottomLeft'
  TOP_RIGHT = 'topRight'
}
InGameMenuMapFrame.GLYPH_COLOR = {
  1 = 1.000000
  2 = 1.000000
  3 = 1.000000
  4 = 1.000000
}
InGameMenuMapFrame.MAP_SOIL = 3.000000
InGameMenuMapFrame.HOTSPOT_FILTER_ICON_PROFILE = {
  false = {
    0 = 'ingameMenuMapFilterButtonIconOtherInactive'
    8 = 'ingameMenuMapFilterButtonIconTrailerInactive'
    3 = 'ingameMenuMapFilterButtonIconTippingInactive'
    7 = 'ingameMenuMapFilterButtonIconToolInactive'
    2 = 'ingameMenuMapFilterButtonIconFieldJobsInactive'
    10 = 'ingameMenuMapFilterButtonIconSteerableInactive'
    9 = 'ingameMenuMapFilterButtonIconCombineInactive'
  }
  true = {
    0 = 'ingameMenuMapFilterButtonIconOther'
    8 = 'ingameMenuMapFilterButtonIconTrailer'
    3 = 'ingameMenuMapFilterButtonIconTipping'
    7 = 'ingameMenuMapFilterButtonIconTool'
    2 = 'ingameMenuMapFilterButtonIconFieldJobs'
    10 = 'ingameMenuMapFilterButtonIconSteerable'
    9 = 'ingameMenuMapFilterButtonIconCombine'
  }
}
InGameMenuMapFrame.GLYPH_TEXT_SIZE = 20.000000
InGameMenuMapFrame.CONTEXT_BOX_TOP_FRAME_PROFILE = 'ingameMenuMapContextBoxFrameTop'
InGameMenuMapFrame.CONTEXT_BOX_BOTTOM_FRAME_PROFILE = 'ingameMenuMapContextBoxFrameBottom'InGameMenuMapFrame.GROUND_STATE_FILTER_COLOR_PROFILE = 'ingameMenuMapFilterDynamicColorLarge'
InGameMenuMapFrame.MAP_FRUIT_TYPE = 1.000000
InGameMenuMapFrame.MAP_GROWTH = 2.000000
InGameMenuMapFrame.INPUT_CONTEXT_NAME = 'MENU_MAP_OVERVIEW'
InGameMenuMapFrame.GLYPH_SIZE = {
  1 = 36.000000
  2 = 36.000000
}
InGameMenuMapFrame.MODE_OVERVIEW = 1.000000
InGameMenuMapFrame.CONTROLS = {
  FILTER_BUTTON_TOOL = 'filterButtonTool'
  GROWTH_STATE_FILTER_COLORS = 'growthStateFilterColor'
  BUTTON_VISIT_PLACE = 'buttonVisitPlace'
  FARMLAND_VALUE_TEXT = 'farmlandValueText'
  BALANCE_TEXT = 'balanceText'
  SOIL_STATE_FILTER_BUTTONS = 'soilStateFilterButton'
  MAP_CONTROLS_DISPLAY = 'mapControls'
  GROWTH_STATE_FILTER_BUTTONS = 'growthStateFilterButton'
  SAFE_AREA = 'safeArea'
  SOIL_STATE_FILTER_COLORS = 'soilStateFilterColor'
  FILTER_BUTTON_VEHICLE = 'filterButtonVehicle'
  CONTEXT_BOX_CORNER = 'contextBoxCorner'
  CONTEXT_FARM = 'contextFarm'
  BUTTON_ENTER_VEHICLE = 'buttonEnterVehicle'
  FILTER_BOX = 'filterBox'
  MOVE_GLYPH_PLACEHOLDER = 'mapMoveGlyphPlaceholder'
  BUTTON_SELECT = 'buttonSelectIngame'
  CONTEXT_BOX = 'contextBox'
  BUTTON_BUY_FARMLAND = 'buttonBuyFarmland'
  BUTTON_SET_MARKER = 'buttonSetMarker'
  CROP_TYPE_FILTER_BOX = 'mapOverviewFruitTypeBox'
  DYNAMIC_MAP_IMAGE_LOADING = 'dynamicMapImageLoading'
  MAP_CURSOR = 'mapCursor'
  MAP_OVERVIEW_SELECTOR = 'mapOverviewSelector'
  BUTTON_BOX = 'buttonBox'
  FILTER_BUTTON_TRAILER = 'filterButtonTrailer'
  FARMLAND_VALUE_BOX = 'farmlandValueBox'
  INGAME_MAP = 'ingameMap'
  GROWTH_STATE_FILTER_BOX = 'mapOverviewGrowthBox'
  BUTTON_LAYOUT = 'buttonLayout'
  ZOOM_GLYPH_PLACEHOLDER = 'mapZoomGlyphPlaceholder'
  BUTTON_SELL_FARMLAND = 'buttonSellFarmland'
  GROWTH_STATE_FILTER_TEXTS = 'growthStateFilterText'
  FILTER_BUTTON_FIELD_JOBS = 'filterButtonContracts'
  SOIL_STATE_FILTER_TEXTS = 'soilStateFilterText'
  BUTTON_SWITCH_MAP_MODE = 'buttonSwitchMapMode'
  FILTER_PAGING = 'filterPaging'
  CONTEXT_IMAGE = 'contextImage'
  FILTER_BUTTON_TIPPING = 'filterButtonTipping'
  CONTEXT_TEXT = 'contextText'
  SOIL_STATE_FILTER_BOX = 'mapOverviewSoilBox'
  FILTER_BUTTON_OTHER = 'filterButtonOther'
  BUTTON_RESET_VEHICLE = 'buttonResetVehicle'
  FILTER_BUTTON_COMBINE = 'filterButtonCombine'
}
InGameMenuMapFrame.FRUITS_PER_PAGE = 15.000000

function InGameMenuMapFrame:resetFarmlandSelection() end
function InGameMenuMapFrame:checkPlaceablesOnFarmland() end
function InGameMenuMapFrame:onClickMapFilterTools() end
function InGameMenuMapFrame:onYesNoSellFarmland() end
function InGameMenuMapFrame:assignFilterData() end
function InGameMenuMapFrame:copyAttributes() end
function InGameMenuMapFrame:setInGameMap() end
function InGameMenuMapFrame:copy() end
function InGameMenuMapFrame:setFilterButtonDisplayEnabled() end
function InGameMenuMapFrame:onFarmlandOverlayFinished() end
function InGameMenuMapFrame:toggleFilter() end
function InGameMenuMapFrame:generateFarmlandOverlay() end
function InGameMenuMapFrame:onClickMapFilterContracts() end
function InGameMenuMapFrame:isa() end
function InGameMenuMapFrame:onClickBuyFarmland() end
function InGameMenuMapFrame:draw() end
function InGameMenuMapFrame:onGuiSetupFinished() end
function InGameMenuMapFrame:setMissionFruitTypes() end
function InGameMenuMapFrame:onClickMapFilterTipStations() end
function InGameMenuMapFrame:updateContextInputBarVisibility() end
function InGameMenuMapFrame:getContextBoxPositionAndOrientation() end
function InGameMenuMapFrame:reset() end
function InGameMenuMapFrame:selectFirstHotspot() end
function InGameMenuMapFrame:initializeFilterButtonState() end
function InGameMenuMapFrame:onClickMapOverviewSelector() end
function InGameMenuMapFrame:class() end
function InGameMenuMapFrame:onSwitchVehicle() end
function InGameMenuMapFrame:onMenuCancel() end
function InGameMenuMapFrame:onMenuActivate() end
function InGameMenuMapFrame:showContextBox() end
function InGameMenuMapFrame:onZoomOut() end
function InGameMenuMapFrame:onClickSoilFilter() end
function InGameMenuMapFrame:registerInput() end
function InGameMenuMapFrame:getHotspotData() end
function InGameMenuMapFrame:assignGroundStateFilterData() end
function InGameMenuMapFrame:onYesNoBuyFarmland() end
function InGameMenuMapFrame:onOverviewOverlayFinished() end
function InGameMenuMapFrame:new() end
function InGameMenuMapFrame:updateInputGlyphs() end
function InGameMenuMapFrame:onClickMapFilterOther() end
function InGameMenuMapFrame:initialize() end
function InGameMenuMapFrame:showContextMarker() end
function InGameMenuMapFrame:onMoneyChanged() end
function InGameMenuMapFrame:onLoadMapFinished() end
function InGameMenuMapFrame:onYesNoReset() end
function InGameMenuMapFrame:onClickSellFarmland() end
function InGameMenuMapFrame:update() end
function InGameMenuMapFrame:setClient() end
function InGameMenuMapFrame:onClickHotspot() end
function InGameMenuMapFrame:onClickEnterVehicle() end
function InGameMenuMapFrame:onClickTagPlace() end
function InGameMenuMapFrame:setupMapOverview() end
function InGameMenuMapFrame:onClickVisitPlace() end
function InGameMenuMapFrame:onVehicleReset() end
function InGameMenuMapFrame:onClickResetVehicle() end
function InGameMenuMapFrame:delete() end
function InGameMenuMapFrame:assignCropTypeFilterData() end
function InGameMenuMapFrame:onClickGrowthFilter() end
function InGameMenuMapFrame:onVehiclesChanged() end
function InGameMenuMapFrame:setColorBlindMode() end
function InGameMenuMapFrame:resetUIDeadzones() end
function InGameMenuMapFrame:onClickMap() end
function InGameMenuMapFrame:onClickSwitchMapMode() end
function InGameMenuMapFrame:toggleMapInput() end
function InGameMenuMapFrame:onClickMapFilterCombine() end
function InGameMenuMapFrame:onClickCropFilter() end
function InGameMenuMapFrame:createInputGlyphs() end
function InGameMenuMapFrame:onZoomIn() end
function InGameMenuMapFrame:setMapSelectionItem() end
function InGameMenuMapFrame:notifyPause() end
function InGameMenuMapFrame:updateContextBoxPosition() end
function InGameMenuMapFrame:onClickMapFilterTrailer() end
function InGameMenuMapFrame:onClickMapFilterSteerable() end
function InGameMenuMapFrame:showContextInput() end
function InGameMenuMapFrame:onDrawPostIngameMap() end
function InGameMenuMapFrame:onFrameClose() end
function InGameMenuMapFrame:updateInputGlyphTransform() end
function InGameMenuMapFrame:updateMapSelectionFilterNavigation() end
function InGameMenuMapFrame:onFrameOpen() end
function InGameMenuMapFrame:onFarmlandStateChanged() end
function InGameMenuMapFrame:setTerrainSize() end
function InGameMenuMapFrame:toggleFarmlandsHotspotFilterSettings() end
function InGameMenuMapFrame:setStaticUIDeadzone() end
function InGameMenuMapFrame:disableAlternateBindings() end
function InGameMenuMapFrame:superClass() end
function InGameMenuMapFrame:setPlayerFarm() end
function InGameMenuMapFrame:onFilterButtonUnselect() end
function InGameMenuMapFrame:setFilterIconState() end
function InGameMenuMapFrame:generateOverviewOverlay() end
function InGameMenuMapFrame:onFilterButtonSelect() end
function InGameMenuMapFrame:assignGroundStateColors() end
function InGameMenuMapFrame:hideContextBox() end