SettingsConsoleFrame = {}

SettingsConsoleFrame.L10N_SYMBOL = {
  SAVING_FINISHED = 'ui_savingFinished',
  BUTTON_APPLY = 'button_apply',
  DOWNSAMPLED = 'setting_resolutionDownsampled'
}
SettingsConsoleFrame.CONTROLS = {
  MAIN_CONTAINER = 'settingsContainer',
  VOLUME_ENVIRONMENT = 'volumeEnvironmentElement',
  VOLUME_GUI = 'volumeGUIElement',
  ELEMENT_UI_SCALE = 'uiScaleElement',
  ELEMENT_INVERT_Y = 'invertYLookElement',
  ELEMENT_FOVY = 'fovyElement',
  ELEMENT_RENDER_QUALITY = 'renderQualityElement',
  VOLUME_RADIO = 'volumeRadioElement',
  MAIN_BOX = 'boxLayout',
  ELEMENT_DISPLAY_RESOLUTION = 'resolutionElement',
  VOLUME_MASTER = 'masterVolumeElement',
  VOLUME_MUSIC = 'musicVolumeElement',
  VOLUME_VEHICLE = 'volumeVehicleElement'
}

function SettingsConsoleFrame:onClickRenderQuality() end
function SettingsConsoleFrame:new() end
function SettingsConsoleFrame:onClickVolumeGUI() end
function SettingsConsoleFrame:initialize() end
function SettingsConsoleFrame:copyAttributes() end
function SettingsConsoleFrame:onClickUIScale() end
function SettingsConsoleFrame:onClickMusicVolume() end
function SettingsConsoleFrame:onUserProfileChanged() end
function SettingsConsoleFrame:onClickVolumeRadio() end
function SettingsConsoleFrame:copy() end
function SettingsConsoleFrame:getMainElementPosition() end
function SettingsConsoleFrame:getMenuButtonInfo() end
function SettingsConsoleFrame:onClickDisplayResolution() end
function SettingsConsoleFrame:onClickVSync() end
function SettingsConsoleFrame:onApplySettings() end
function SettingsConsoleFrame:onCreateFovy() end
function SettingsConsoleFrame:onClickFovy() end
function SettingsConsoleFrame:onCreateMusicVolume() end
function SettingsConsoleFrame:onClickMasterVolume() end
function SettingsConsoleFrame:isa() end
function SettingsConsoleFrame:onClickInvertYLook() end
function SettingsConsoleFrame:onCreateVolumeEnvironment() end
function SettingsConsoleFrame:superClass() end
function SettingsConsoleFrame:onClickVolumeVehicle() end
function SettingsConsoleFrame:onCreateMasterVolume() end
function SettingsConsoleFrame:onCreateDisplayResolution() end
function SettingsConsoleFrame:onCreateRenderQuality() end
function SettingsConsoleFrame:class() end
function SettingsConsoleFrame:getMainElementSize() end
function SettingsConsoleFrame:onCreateVolumeGUI() end
function SettingsConsoleFrame:onFrameOpen() end
function SettingsConsoleFrame:onCreateUIScale() end
function SettingsConsoleFrame:onCreateVolumeVehicle() end
function SettingsConsoleFrame:onCreateVolumeRadio() end
function SettingsConsoleFrame:updateValues() end
function SettingsConsoleFrame:onClickVolumeEnvironment() end