SettingsControlsFrame = {}

SettingsControlsFrame.KB_MOUSE_BOUND_CONTROLS = {
  KEY_1 = 'key1',
  ACTION = 'action',
  KEY_2 = 'key2',
  MOUSE_BUTTON = 'mouseButton'
}
SettingsControlsFrame.GAMEPAD_BOUND_CONTROLS = {
  ACTION = 'gamepadAction',
  BUTTON_2 = 'gamepadButton2',
  BUTTON_1 = 'gamepadButton1'
}
SettingsControlsFrame.L10N_TEMPLATE_SYMBOL = {
  13 = 'ui_actionRemapped'
}
SettingsControlsFrame.CONTROLS_UI_STRINGS = {
  2 = 'ui_cannotMapMouseHere',
  5 = 'ui_pressMouseButtonToMap',
  12 = 'ui_axisAlreadyMapped',
  11 = 'ui_buttonAlreadyMapped',
  4 = 'ui_pressKeyToMap',
  10 = 'ui_buttonAlreadyMapped',
  9 = 'ui_keyAlreadyMapped',
  8 = 'ui_selectActionToRemap',
  3 = 'ui_cannotMapGamepadHere',
  7 = 'ui_pressESCToCancel',
  1 = 'ui_cannotMapKeyHere',
  6 = 'ui_pressGamepadButtonToMap'
}
SettingsControlsFrame.CONTROLS = {
  KEYBOARD_HEADER_ICON = 'keyboardHeaderIcon',
  GAMEPAD_PAGE = 'gamepadPage',
  KEYBOARD_HIDDEN_BUTTON = 'keyboardHiddenButton',
  GAMEPAD_HIDDEN_BUTTON = 'gamepadHiddenButton',
  CONTROLS_MESSAGE_WARNING_ICON = 'controlsMessageWarningIcon',
  CONTROLS_MESSAGE = 'controlsMessage',
  GAMEPAD_HEADER_ICON = 'gamepadHeaderIcon',
  KEYBOARD_HEADER_TEXT = 'keyboardHeaderText',
  PAGING = 'pagingElement',
  KB_MOUSE_PAGE = 'keyboardMousePage',
  KB_MOUSE_TABLE = 'keyboardMouseTable',
  GAMEPAD_HEADER_TEXT = 'gamepadHeaderText',
  GAMEPAD_TABLE = 'gamepadTable'
}
SettingsControlsFrame.L10N_SYMBOL = {
  DEFAULTS_LOADED = 'ui_loadedDefaultSettings',
  SAVE_CHANGES_PROMPT = 'ui_saveChanges',
  BUTTON_PROMPT = 'ui_pressGamepadButtonToMap',
  BUTTON_RESET = 'button_reset',
  MOUSE_PROMPT = 'ui_pressMouseButtonToMap',
  BUTTON_GAMEPAD = 'ui_gamepad',
  BUTTON_SAVE = 'button_saveControls',
  KEY_PROMPT = 'ui_pressKeyToMap',
  BUTTON_KEYBOARD = 'ui_keyboard',
  SAVED_CHANGES_INFO = 'ui_savingFinished',
  BUTTON_DEFAULTS = 'button_defaults',
  LOAD_DEFAULTS = 'ui_loadDefaultSettings'
}

function SettingsControlsFrame:onClickGamepadButton2() end
function SettingsControlsFrame:new() end
function SettingsControlsFrame:notifyInputGatheringFinished() end
function SettingsControlsFrame:initialize() end
function SettingsControlsFrame:copyAttributes() end
function SettingsControlsFrame:setControlsMessage() end
function SettingsControlsFrame:getActionDataFromClickedTableButton() end
function SettingsControlsFrame:copy() end
function SettingsControlsFrame:updateHeader() end
function SettingsControlsFrame:setRequestButtonUpdateCallback() end
function SettingsControlsFrame:saveChanges() end
function SettingsControlsFrame:onClickGamepadHeader() end
function SettingsControlsFrame:bindControls() end
function SettingsControlsFrame:revertChanges() end
function SettingsControlsFrame:isa() end
function SettingsControlsFrame:onClickGamepadButton1() end
function SettingsControlsFrame:onInputClicked() end
function SettingsControlsFrame:superClass() end
function SettingsControlsFrame:onClickDefaults() end
function SettingsControlsFrame:onClickKey2() end
function SettingsControlsFrame:setupControlsView() end
function SettingsControlsFrame:onYesNoSaveControls() end
function SettingsControlsFrame:switchDevice() end
function SettingsControlsFrame:onClickKeyboardHeader() end
function SettingsControlsFrame:assignDeviceTableData() end
function SettingsControlsFrame:onClickMouse() end
function SettingsControlsFrame:showInputPrompt() end
function SettingsControlsFrame:updateDisplay() end
function SettingsControlsFrame:onClickKey1() end
function SettingsControlsFrame:getMainElementSize() end
function SettingsControlsFrame:requestClose() end
function SettingsControlsFrame:class() end
function SettingsControlsFrame:getMainElementPosition() end
function SettingsControlsFrame:updateMenuButtons() end
function SettingsControlsFrame:onFrameOpen() end
function SettingsControlsFrame:setDevicePage() end