SettingsGeneralFrame = {}

SettingsGeneralFrame.CONTROLS = {
  MAIN_CONTAINER = 'settingsContainer'
  VOLUME_ENVIRONMENT = 'volumeEnvironmentElement'
  VOLUME_GUI = 'volumeGUIElement'
  HEAD_TRACKING = 'isHeadTrackingEnabledElement'
  GAMEPAD_MODE = 'isGamepadEnabledElement'
  MP_LANGUAGE = 'mpLanguageElement'
  INPUT_HELP_MODE = 'inputHelpModeElement'
  VOLUME_RADIO = 'volumeRadioElement'
  LANGUAGE = 'languageElement'
  VOLUME_MUSIC = 'musicVolumeElement'
  VOLUME_MASTER = 'masterVolumeElement'
  INVERT_Y_LOOK = 'invertYLookElement'
  VOLUME_VEHICLE = 'volumeVehicleElement'
}
SettingsGeneralFrame.L10N_SYMBOL = {
  BUTTON_APPLY = 'button_apply'
}

function SettingsGeneralFrame:new() end
function SettingsGeneralFrame:onClickVolumeGUI() end
function SettingsGeneralFrame:initialize() end
function SettingsGeneralFrame:copyAttributes() end
function SettingsGeneralFrame:onClickInputHelpMode() end
function SettingsGeneralFrame:onClickMusicVolume() end
function SettingsGeneralFrame:onClickVolumeRadio() end
function SettingsGeneralFrame:copy() end
function SettingsGeneralFrame:getMainElementPosition() end
function SettingsGeneralFrame:getMenuButtonInfo() end
function SettingsGeneralFrame:onClickMPLanguage() end
function SettingsGeneralFrame:applyDefaultSettingsValues() end
function SettingsGeneralFrame:onCreateInputHelpMode() end
function SettingsGeneralFrame:onApplySettings() end
function SettingsGeneralFrame:onCreateMusicVolume() end
function SettingsGeneralFrame:onCreateMPLanguage() end
function SettingsGeneralFrame:onClickMasterVolume() end
function SettingsGeneralFrame:isa() end
function SettingsGeneralFrame:onClickInvertYLook() end
function SettingsGeneralFrame:onCreateVolumeEnvironment() end
function SettingsGeneralFrame:superClass() end
function SettingsGeneralFrame:onClickVolumeVehicle() end
function SettingsGeneralFrame:onCreateMasterVolume() end
function SettingsGeneralFrame:onFrameOpen() end
function SettingsGeneralFrame:onClickIsGamepadEnabled() end
function SettingsGeneralFrame:onCreateVolumeRadio() end
function SettingsGeneralFrame:class() end
function SettingsGeneralFrame:onCreateVolumeVehicle() end
function SettingsGeneralFrame:getMainElementSize() end
function SettingsGeneralFrame:onCreateLanguage() end
function SettingsGeneralFrame:onCreateVolumeGUI() end
function SettingsGeneralFrame:onClickLanguage() end
function SettingsGeneralFrame:onClickIsHeadTrackingEnabled() end
function SettingsGeneralFrame:onClickVolumeEnvironment() end