ShopController = {}

ShopController.L10N_SYMBOL = {
  RETURN_VEHICLE_IN_USE = 'shop_messageReturnVehicleInUse',
  RETURN_VEHICLE_SUCCESS = 'shop_messageReturnedVehicle',
  SELL_VEHICLE_NO_PERMISSION = 'shop_messageNoPermissionToSellVehicleText',
  WARNING_NO_SPACE = 'shop_messageNoSpace',
  SELL_VEHICLE_FAILED = 'shop_messageFailedToSellVehicle',
  BUY_VEHICLE_SUCCESS = 'shop_messagePurchaseReady',
  BUY_VEHICLE_NO_PERMISSION = 'shop_messageNoPermissionToBuyVehicleText',
  RETURNING_VEHICLE = 'shop_messageReturningVehicle',
  BUY_CHAINSAW_THANKS = 'shop_messageThanksForBuying',
  LEASE_VEHICLE_SUCCESS = 'shop_messageLeasingReady',
  NO_PERMISSION = 'shop_messageNoPermissionGeneral',
  RETURN_VEHICLE_NO_PERMISSION = 'shop_messageNoPermissionToReturnVehicleText',
  BUY_CHAINSAW_SUCCESS = 'shop_messageBoughtChainsaw',
  CANNOT_SELL_TOUR_ITEMS = 'shop_messageTourItemsCannotBeSold',
  BUY_ALREADY_OWNED = 'shop_messageAlreadyOwned',
  BUY_CONFIRMATION = 'shop_doYouWantToBuy',
  WARNING_TOO_MANY_PALLETS = 'warning_tooManyPallets',
  BUYING_VEHICLE = 'shop_messageBuyingVehicle',
  BUY_VEHICLE_FAILED_TO_LOAD = 'shop_messageFailedToLoadVehicle',
  RETURN_VEHICLE_FAILED = 'shop_messageFailedToReturnVehicle',
  LEASING_VEHICLE = 'shop_messageLeasingVehicle',
  BUY_OBJECT_SUCCESS = 'shop_messageGardenCenterPurchaseReady',
  WARNING_NOT_ENOUGH_SLOTS = 'shop_messageNotEnoughSlotsToBuy',
  WARNING_NOT_ENOUGH_MONEY = 'shop_messageNotEnoughMoneyToBuy',
  SELL_VEHICLE_SUCCESS = 'shop_messageSoldVehicle',
  LOAD_OBJECT_FAILED = 'shop_messageFailedToLoadObject',
  SELLING_VEHICLE = 'shop_messageSellingVehicle',
  SELL_VEHICLE_IN_USE = 'shop_messageSellVehicleInUse',
  WARNING_TOO_MANY_PLACEABLES = 'warning_tooManyPlaceables'
}
ShopController.PROFILE = {
  ICON_LEASED = 'shopListAttributeIconLeased',
  ICON_OWNED = 'shopListAttributeIconOwned'
}
ShopController.MAX_ATTRIBUTES_PER_ROW = 5.000000

function ShopController:onObjectBuyFailed() end
function ShopController:buy() end
function ShopController:setConfigurations() end
function ShopController:displayItemSortFunction() end
function ShopController:setCurrentMission() end
function ShopController:onHandToolBuyFailed() end
function ShopController:onVehicleSold() end
function ShopController:setOwnedFarmItems() end
function ShopController:onSellCallback() end
function ShopController:copy() end
function ShopController:onVehicleSellEvent() end
function ShopController:canBeBought() end
function ShopController:onSellItem() end
function ShopController:onHandToolBuyEvent() end
function ShopController:isa() end
function ShopController:getVehicleCategories() end
function ShopController:setUpdateAllItemsCallback() end
function ShopController:onObjectBought() end
function ShopController:setLeasedFarmItems() end
function ShopController:reset() end
function ShopController:onPlaceableSellEvent() end
function ShopController:class() end
function ShopController:load() end
function ShopController:getBrands() end
function ShopController:onVehicleBought() end
function ShopController:addBrandForDisplay() end
function ShopController:onVehicleSellFailed() end
function ShopController:onVehicleBuyFailed() end
function ShopController:new() end
function ShopController:buyVehicle() end
function ShopController:onVehicleBuyEvent() end
function ShopController:getToolCategories() end
function ShopController:setClient() end
function ShopController:makeDisplayItem() end
function ShopController:sellPlaceableWarningInfoClickOk() end
function ShopController:onPlaceableSold() end
function ShopController:onYesNoBuyObject() end
function ShopController:addCategoryForDisplay() end
function ShopController:onHandToolSellEvent() end
function ShopController:filterOwnedItemsByFarmId() end
function ShopController:sellVehicle() end
function ShopController:getObjectCategories() end
function ShopController:getPlaceableCategories() end
function ShopController:categorySortFunction() end
function ShopController:brandSortFunction() end
function ShopController:onSoldCallback() end
function ShopController:onBoughtCallback() end
function ShopController:onYesNoBuyHandtool() end
function ShopController:buyHandTool() end
function ShopController:sell() end
function ShopController:getLeasedVehicles() end
function ShopController:getOwnedFarmItems() end
function ShopController:update() end
function ShopController:sellPlaceable() end
function ShopController:superClass() end
function ShopController:setSwitchToConfigurationCallback() end
function ShopController:subscribeEvents() end
function ShopController:getOwnedItems() end
function ShopController:getItemsByCategory() end
function ShopController:onObjectBuyEvent() end
function ShopController:sellHandTool() end
function ShopController:updateDisplayItems() end
function ShopController:getItemsByBrand() end
function ShopController:setUpdateShopItemsCallback() end
function ShopController:getLeasedFarmItems() end
function ShopController:onHandToolBought() end
function ShopController:finalizeBuy() end
function ShopController:setPlayerFarm() end
function ShopController:buyObject() end
function ShopController:setStartPlacementModeCallback() end
function ShopController:onPlaceableSellFailed() end
function ShopController:onHandToolSold() end
function ShopController:onHandToolSellFailed() end