FrameElement = {}

function FrameElement:disableInputForDuration() end
function FrameElement:new() end
function FrameElement:isa() end
function FrameElement:setChangeScreenCallback() end
function FrameElement:playSample() end
function FrameElement:copyAttributes() end
function FrameElement:superClass() end
function FrameElement:update() end
function FrameElement:changeScreen() end
function FrameElement:toggleCustomInputContext() end
function FrameElement:exposeControlsAsFields() end
function FrameElement:copy() end
function FrameElement:setInputContextCallback() end
function FrameElement:class() end
function FrameElement:registerControls() end
function FrameElement:getRootElement() end
function FrameElement:setPlaySampleCallback() end
function FrameElement:clone() end
function FrameElement:isInputDisabled() end