GuiElement = {}

GuiElement.SCREEN_ALIGN_MIDDLE = 16.000000
GuiElement.SCREEN_ALIGN_YNONE = 128.000000
GuiElement.FRAME_RIGHT = 3.000000
GuiElement.ORIGIN_RIGHT = 4.000000
GuiElement.MARGIN_LEFT = 1.000000
GuiElement.ORIGIN_LEFT = 1.000000
GuiElement.FRAME_TOP = 2.000000
GuiElement.MARGIN_TOP = 2.000000
GuiElement.SCREEN_ALIGN_XNONE = 64.000000
GuiElement.ORIGIN_CENTER = 2.000000
GuiElement.SCREEN_ALIGN_LEFT = 1.000000
GuiElement.SCREEN_ALIGN_RIGHT = 4.000000
GuiElement.ORIGIN_TOP = 32.000000
GuiElement.FRAME_BOTTOM = 4.000000
GuiElement.SCREEN_ALIGN_CENTER = 2.000000
GuiElement.ORIGIN_MIDDLE = 16.000000
GuiElement.SCREEN_ALIGN_TOP = 32.000000
GuiElement.MARGIN_RIGHT = 3.000000
GuiElement.MARGIN_BOTTOM = 4.000000
GuiElement.debugOverlay = 4.000000
GuiElement.ORIGIN_BOTTOM = 8.000000
GuiElement.FRAME_LEFT = 1.000000
GuiElement.SCREEN_ALIGN_BOTTOM = 8.000000

function GuiElement:getOverlayState() end
function GuiElement:copyAttributes() end
function GuiElement:deleteFrame() end
function GuiElement:setVisible() end
function GuiElement:inputEvent() end
function GuiElement:onClose() end
function GuiElement:unlinkElement() end
function GuiElement:setId() end
function GuiElement:getIsVisibleNonRec() end
function GuiElement:getBorders() end
function GuiElement:onFocusActivate() end
function GuiElement:addElement() end
function GuiElement:getSoundSuppressed() end
function GuiElement:updateFramePosition() end
function GuiElement:isa() end
function GuiElement:getIsDisabled() end
function GuiElement:draw() end
function GuiElement:onGuiSetupFinished() end
function GuiElement:updateAbsolutePosition() end
function GuiElement:toString() end
function GuiElement:setAbsolutePosition() end
function GuiElement:verifyConfiguration() end
function GuiElement:include() end
function GuiElement:getParentBorders() end
function GuiElement:reset() end
function GuiElement:getDescendantByName() end
function GuiElement:clone() end
function GuiElement:mouseEvent() end
function GuiElement:getHandleFocus() end
function GuiElement:getIsSelected() end
function GuiElement:getIsActiveNonRec() end
function GuiElement:move() end
function GuiElement:removeElement() end
function GuiElement:setPosition() end
function GuiElement:setAlpha() end
function GuiElement:addCallback() end
function GuiElement:storeOverlayState() end
function GuiElement:shouldFocusChange() end
function GuiElement:applyScreenAlignment() end
function GuiElement:getIsActive() end
function GuiElement:applyProfile() end
function GuiElement:applyElementAspectScale() end
function GuiElement:setDisabled() end
function GuiElement:getCenter() end
function GuiElement:delete() end
function GuiElement:superClass() end
function GuiElement:fixThinLines() end
function GuiElement:createFrame() end
function GuiElement:updatePositionForOrigin() end
function GuiElement:onFocusLeave() end
function GuiElement:cutFrameBordersVertical() end
function GuiElement:extractIndexAndNameFromID() end
function GuiElement:getFocusTarget() end
function GuiElement:getDescendantById() end
function GuiElement:getFirstDescendant() end
function GuiElement:getDescendants() end
function GuiElement:isChildOf() end
function GuiElement:findDescendantsRec() end
function GuiElement:setSoundSuppressed() end
function GuiElement:fadeOut() end
function GuiElement:getIsHighlighted() end
function GuiElement:fadeIn() end
function GuiElement:raiseCallback() end
function GuiElement:setSize() end
function GuiElement:cutFrameBordersHorizontal() end
function GuiElement:new() end
function GuiElement:loadProfile() end
function GuiElement:loadFromXML() end
function GuiElement:onHighlightRemove() end
function GuiElement:getIsVisible() end
function GuiElement:onOpen() end
function GuiElement:class() end
function GuiElement:updateScreenAlign() end
function GuiElement:toggleFrameSide() end
function GuiElement:onFocusEnter() end
function GuiElement:onHighlight() end
function GuiElement:canReceiveFocus() end
function GuiElement:update() end
function GuiElement:keyEvent() end
function GuiElement:restoreOverlayState() end
function GuiElement:getAspectScale() end
function GuiElement:copy() end
function GuiElement:setOverlayState() end
function GuiElement:setHandleFocus() end