IngameMapElement = {}

IngameMapElement.CURSOR_SPEED_FACTOR = 0.000600
IngameMapElement.ZOOM_SPEED_FACTOR = 0.050000
IngameMapElement.MAP_ZOOM_SHOW_NAMES = 0.800000
IngameMapElement.BORDER_SCROLL_THRESHOLD = 0.030000
IngameMapElement.DRAG_START_DISTANCE = 2.000000

function IngameMapElement:new() end
function IngameMapElement:loadFromXML() end
function IngameMapElement:updateCursor() end
function IngameMapElement:update() end
function IngameMapElement:onClose() end
function IngameMapElement:copy() end
function IngameMapElement:clearCursorDeadzones() end
function IngameMapElement:getLocaPointerTarget() end
function IngameMapElement:getElementSize() end
function IngameMapElement:selectHotspotAt() end
function IngameMapElement:delete() end
function IngameMapElement:onZoomInput() end
function IngameMapElement:resetFrameInputState() end
function IngameMapElement:onAccept() end
function IngameMapElement:onVerticalCursorInput() end
function IngameMapElement:isCursorInDeadzones() end
function IngameMapElement:setTerrainSize() end
function IngameMapElement:isa() end
function IngameMapElement:removeActionEvents() end
function IngameMapElement:updateMap() end
function IngameMapElement:registerActionEvents() end
function IngameMapElement:draw() end
function IngameMapElement:onGuiSetupFinished() end
function IngameMapElement:setIngameMap() end
function IngameMapElement:isPointVisible() end
function IngameMapElement:setMapFocusToHotspot() end
function IngameMapElement:localToWorldPos() end
function IngameMapElement:zoom() end
function IngameMapElement:onClickMap() end
function IngameMapElement:reset() end
function IngameMapElement:getLocalPosition() end
function IngameMapElement:mouseEvent() end
function IngameMapElement:class() end
function IngameMapElement:onHorizontalCursorInput() end
function IngameMapElement:addCursorDeadzone() end
function IngameMapElement:checkAndResetMouse() end
function IngameMapElement:moveCenter() end
function IngameMapElement:onOpen() end
function IngameMapElement:superClass() end
function IngameMapElement:loadProfile() end
function IngameMapElement:copyAttributes() end