MultiTextOptionElement = {}

function MultiTextOptionElement:inputRight() end
function MultiTextOptionElement:setState() end
function MultiTextOptionElement:new() end
function MultiTextOptionElement:isa() end
function MultiTextOptionElement:loadFromXML() end
function MultiTextOptionElement:getState() end
function MultiTextOptionElement:copyAttributes() end
function MultiTextOptionElement:canReceiveFocus() end
function MultiTextOptionElement:superClass() end
function MultiTextOptionElement:setTexts() end
function MultiTextOptionElement:updateTextElement() end
function MultiTextOptionElement:onFocusLeave() end
function MultiTextOptionElement:onHighlightRemove() end
function MultiTextOptionElement:onFocusEnter() end
function MultiTextOptionElement:inputEvent() end
function MultiTextOptionElement:onHighlight() end
function MultiTextOptionElement:onLeftButtonClicked() end
function MultiTextOptionElement:copy() end
function MultiTextOptionElement:mouseEvent() end
function MultiTextOptionElement:class() end
function MultiTextOptionElement:onRightButtonClicked() end
function MultiTextOptionElement:setLabel() end
function MultiTextOptionElement:getCanChangeState() end
function MultiTextOptionElement:setCanChangeState() end
function MultiTextOptionElement:inputLeft() end
function MultiTextOptionElement:setForceHighlight() end
function MultiTextOptionElement:addElement() end
function MultiTextOptionElement:addText() end
function MultiTextOptionElement:loadProfile() end
function MultiTextOptionElement:disableButtonSounds() end