PagingElement = {}

function PagingElement:addPage() end
function PagingElement:addElement() end
function PagingElement:setPageDisabled() end
function PagingElement:new() end
function PagingElement:setPage() end
function PagingElement:isa() end
function PagingElement:loadFromXML() end
function PagingElement:getPageIdByElement() end
function PagingElement:copyAttributes() end
function PagingElement:getNextID() end
function PagingElement:onGuiSetupFinished() end
function PagingElement:getPageIndexByElement() end
function PagingElement:setPageIdDisabled() end
function PagingElement:getCurrentPageId() end
function PagingElement:getPageById() end
function PagingElement:getVisiblePagesCount() end
function PagingElement:class() end
function PagingElement:getPageTitles() end
function PagingElement:getPageElementByIndex() end
function PagingElement:getPageMappingIndexByElement() end
function PagingElement:removeElement() end
function PagingElement:getIsPageDisabled() end
function PagingElement:getPageMappingIndex() end
function PagingElement:removePageByElement() end
function PagingElement:updatePageMapping() end
function PagingElement:superClass() end
function PagingElement:copy() end