SliderElement = {}

SliderElement.DIRECTION_X = 1.000000
SliderElement.DIRECTION_Y = 2.000000

function SliderElement:shouldFocusChange() end
function SliderElement:new() end
function SliderElement:updateSliderButtons() end
function SliderElement:onScrollDown() end
function SliderElement:setValue() end
function SliderElement:setSliderVisible() end
function SliderElement:setMaxValue() end
function SliderElement:updateSliderPosition() end
function SliderElement:onFocusLeave() end
function SliderElement:copy() end
function SliderElement:setMinValue() end
function SliderElement:getValue() end
function SliderElement:getMaxValue() end
function SliderElement:applySliderAspectScale() end
function SliderElement:addElement() end
function SliderElement:isa() end
function SliderElement:onListUpdate() end
function SliderElement:updateSliderLimits() end
function SliderElement:draw() end
function SliderElement:onGuiSetupFinished() end
function SliderElement:getMinValue() end
function SliderElement:onScrollUp() end
function SliderElement:onFocusActivate() end
function SliderElement:onFocusEnter() end
function SliderElement:canReceiveFocus() end
function SliderElement:applyScreenAlignment() end
function SliderElement:delete() end
function SliderElement:copyAttributes() end
function SliderElement:mouseEvent() end
function SliderElement:class() end
function SliderElement:setDataElement() end
function SliderElement:superClass() end
function SliderElement:setSize() end
function SliderElement:updateAbsolutePosition() end
function SliderElement:keyEvent() end
function SliderElement:callOnChanged() end
function SliderElement:setAlpha() end
function SliderElement:setSliderSize() end
function SliderElement:loadProfile() end
function SliderElement:loadFromXML() end