StableListElement = {}

function StableListElement:addElement() end
function StableListElement:setDataSource() end
function StableListElement:new() end
function StableListElement:buildListItems() end
function StableListElement:loadFromXML() end
function StableListElement:getSelectedElement() end
function StableListElement:copyAttributes() end
function StableListElement:superClass() end
function StableListElement:setAssignItemDataFunction() end
function StableListElement:getItemCount() end
function StableListElement:notifyClick() end
function StableListElement:clone() end
function StableListElement:notifyDoubleClick() end
function StableListElement:class() end
function StableListElement:updateItemPositionsInRange() end
function StableListElement:onGuiSetupFinished() end
function StableListElement:getSelectedElementIndex() end
function StableListElement:removeElement() end
function StableListElement:copy() end
function StableListElement:onDataSourceChanged() end
function StableListElement:setSelectedIndex() end
function StableListElement:delete() end
function StableListElement:getSelectedDataIndex() end
function StableListElement:isa() end