TabbedMenuFrameElement = {}

function TabbedMenuFrameElement:getHasCustomMenuButtons() end
function TabbedMenuFrameElement:isMenuButtonInfoDirty() end
function TabbedMenuFrameElement:new() end
function TabbedMenuFrameElement:requestClose() end
function TabbedMenuFrameElement:initialize() end
function TabbedMenuFrameElement:clearMenuButtonInfoDirty() end
function TabbedMenuFrameElement:superClass() end
function TabbedMenuFrameElement:onFrameClose() end
function TabbedMenuFrameElement:copy() end
function TabbedMenuFrameElement:getMainElementPosition() end
function TabbedMenuFrameElement:onFrameOpen() end
function TabbedMenuFrameElement:getMainElementSize() end
function TabbedMenuFrameElement:setMenuButtonInfoDirty() end
function TabbedMenuFrameElement:isa() end
function TabbedMenuFrameElement:class() end
function TabbedMenuFrameElement:setMenuButtonInfo() end
function TabbedMenuFrameElement:getMenuButtonInfo() end