TextElement = {}

TextElement.VERTICAL_ALIGNMENT = {
  MIDDLE = 'middle'
  BOTTOM = 'bottom'
  TOP = 'top'
}

function TextElement:getTextPosition() end
function TextElement:new() end
function TextElement:loadFromXML() end
function TextElement:setTextSelectedColor() end
function TextElement:copyAttributes() end
function TextElement:getTextPositionX() end
function TextElement:getTextColor() end
function TextElement:setTextHighlightedColor() end
function TextElement:copy() end
function TextElement:getText2Color() end
function TextElement:getText2Offset() end
function TextElement:getTextPositionY() end
function TextElement:applyTextAspectScale() end
function TextElement:setTextSize() end
function TextElement:setText2HighlightedColor() end
function TextElement:draw() end
function TextElement:superClass() end
function TextElement:getText() end
function TextElement:getTextHeight() end
function TextElement:setText2Color() end
function TextElement:updateSize() end
function TextElement:applyScreenAlignment() end
function TextElement:updateScaledWidth() end
function TextElement:setTextColor() end
function TextElement:getTextWidth() end
function TextElement:getTextOffset() end
function TextElement:class() end
function TextElement:isa() end
function TextElement:setText() end
function TextElement:setText2SelectedColor() end
function TextElement:loadProfile() end
function TextElement:getDoRenderText() end