TextInputElement = {}

TextInputElement.INITIAL_REPEAT_DELAY = 500.000000
TextInputElement.MIN_REPEAT_DELAY = 100.000000
TextInputElement.inputContextActive = false
TextInputElement.INPUT_CONTEXT_NAME = 'TEXT_INPUT'

function TextInputElement:shouldFocusChange() end
function TextInputElement:getIsActive() end
function TextInputElement:new() end
function TextInputElement:getDoRenderText() end
function TextInputElement:copyAttributes() end
function TextInputElement:moveCursorRight() end
function TextInputElement:onFocusLeave() end
function TextInputElement:update() end
function TextInputElement:updateVisibleTextElements() end
function TextInputElement:inputEvent() end
function TextInputElement:onClose() end
function TextInputElement:copy() end
function TextInputElement:translate() end
function TextInputElement:moveCursorLeft() end
function TextInputElement:drawTextPart() end
function TextInputElement:stopSpecialKeyRepeating() end
function TextInputElement:getIsUnicodeAllowed() end
function TextInputElement:isa() end
function TextInputElement:getNeededTextWidth() end
function TextInputElement:draw() end
function TextInputElement:superClass() end
function TextInputElement:setCaptureInput() end
function TextInputElement:getAvailableTextWidth() end
function TextInputElement:limitTextToAvailableWidth() end
function TextInputElement:drawCursor() end
function TextInputElement:applyTextInputAspectScale() end
function TextInputElement:onFocusActivate() end
function TextInputElement:reset() end
function TextInputElement:finalize() end
function TextInputElement:class() end
function TextInputElement:mouseEvent() end
function TextInputElement:applyScreenAlignment() end
function TextInputElement:setText() end
function TextInputElement:setForcePressed() end
function TextInputElement:keyEvent() end
function TextInputElement:loadFromXML() end
function TextInputElement:setAlpha() end
function TextInputElement:delete() end
function TextInputElement:loadProfile() end
function TextInputElement:deleteText() end