ToggleButtonElement = {}

function ToggleButtonElement:onFocusActivate() end
function ToggleButtonElement:addElement() end
function ToggleButtonElement:new() end
function ToggleButtonElement:isa() end
function ToggleButtonElement:loadFromXML() end
function ToggleButtonElement:copyAttributes() end
function ToggleButtonElement:canReceiveFocus() end
function ToggleButtonElement:superClass() end
function ToggleButtonElement:onFocusLeave() end
function ToggleButtonElement:getFocusTarget() end
function ToggleButtonElement:copy() end
function ToggleButtonElement:mouseEvent() end
function ToggleButtonElement:onFocusEnter() end
function ToggleButtonElement:onButtonClicked() end
function ToggleButtonElement:setIsChecked() end
function ToggleButtonElement:loadProfile() end
function ToggleButtonElement:class() end