VideoElement = {}

function VideoElement:getIsActive() end
function VideoElement:new() end
function VideoElement:isa() end
function VideoElement:loadFromXML() end
function VideoElement:copyAttributes() end
function VideoElement:draw() end
function VideoElement:superClass() end
function VideoElement:disposeVideo() end
function VideoElement:update() end
function VideoElement:stopVideo() end
function VideoElement:copy() end
function VideoElement:mouseEvent() end
function VideoElement:class() end
function VideoElement:playVideo() end
function VideoElement:keyEvent() end
function VideoElement:changeVideo() end
function VideoElement:delete() end
function VideoElement:loadProfile() end
function VideoElement:onEndVideo() end