Client = {
  graphColors = {},
  tickDuration = 0.0,
  tickRate = 0,
  activeObjects = {},
  tickSum = 0,
  showActiveObjects = false,
  serverStreamId = 0,
  lastUploadedKBs = 0,
  netIsRunning = false,
  tempClientManurallyRegisteringObjects = {},
  packetGraphs = {},
  packetBytes = {},
  lastNumUpdatesSent = 0,
  networkListener = {},
  currentLatency = 0,
  objects = {},
  clientPort = 0,
  serverConnection = {},
  tempClientCreatingObjects = {},
  objectIds = {},
  removedObjects = {},
  activeObjectsNextFrame = {},
  lastUploadedKBsSmooth = 0,
  showNetworkTraffic = false,
  clientNetworkCardAddress = '',
  maxUploadedKBs = 0
}

function Client:stop() end
function Client:packetReceived() end
function Client:isa() end
function Client:connectionRequestAccepted() end
function Client:delete() end
function Client:draw() end
function Client:registerObject() end
function Client:start() end
function Client:getServerConnection() end
function Client:copy() end
function Client:mouseEvent() end
function Client:class() end
function Client:finishRegisterObject() end
function Client:keyEvent() end
function Client:superClass() end
function Client:unregisterObject() end
function Client:update() end
function Client:startLocal() end
function Client:new() end