NetworkNode = {}

NetworkNode.PACKET_OTHERS = 7.000000
NetworkNode.NUM_PACKETS = 7.000000
NetworkNode.CHANNEL_CHAT = 4.000000
NetworkNode.OBJECT_SEND_NUM_BITS = 24.000000
NetworkNode.CHANNEL_GROUND = 3.000000
NetworkNode.PACKET_DENSITY_MAPS = 5.000000
NetworkNode.PACKET_SPLITSHAPES = 4.000000
NetworkNode.CHANNEL_MAIN = 1.000000
NetworkNode.LOCAL_STREAM_ID = 0.000000
NetworkNode.PACKET_TERRAIN_DEFORM = 6.000000
NetworkNode.PACKET_PLAYER = 3.000000
NetworkNode.PACKET_EVENT = 1.000000
NetworkNode.CHANNEL_SECONDARY = 2.000000
NetworkNode.PACKET_VEHICLE = 2.000000

function NetworkNode:updateActiveObjectsTick() end
function NetworkNode:new() end
function NetworkNode:removeObject() end
function NetworkNode:setNetworkListener() end
function NetworkNode:update() end
function NetworkNode:getObjectPacketType() end
function NetworkNode:getPacketTypeName() end
function NetworkNode:removeObjectFromUpdateLoop() end
function NetworkNode:unregisterObject() end
function NetworkNode:getObject() end
function NetworkNode:packetReceived() end
function NetworkNode:isa() end
function NetworkNode:addPacketSize() end
function NetworkNode:draw() end
function NetworkNode:superClass() end
function NetworkNode:consoleCommandToggleNetworkShowActiveObjects() end
function NetworkNode:consoleCommandToggleShowNetworkTraffic() end
function NetworkNode:registerObject() end
function NetworkNode:addObjectToUpdateLoop() end
function NetworkNode:addObject() end
function NetworkNode:getObjectId() end
function NetworkNode:checkObjectUpdateDebugReadSize() end
function NetworkNode:updatePacketStats() end
function NetworkNode:class() end
function NetworkNode:copy() end
function NetworkNode:mouseEvent() end
function NetworkNode:delete() end
function NetworkNode:keyEvent() end
function NetworkNode:updateActiveObjects() end
function NetworkNode:drawConnectionNetworkStats() end