Object = {}

Object.classId = 3.000000
Object.className = 'Object'
Object.nextObjectId = 4.000000

function Object:new() end
function Object:unregister() end
function Object:delete() end
function Object:clearDirtyFlags() end
function Object:register() end
function Object:updateTick() end
function Object:raiseActive() end
function Object:setOwnerFarmId() end
function Object:getNextDirtyFlag() end
function Object:copy() end
function Object:getOwnerFarmId() end
function Object:getUpdatePriority() end
function Object:readStream() end
function Object:testScope() end
function Object:raiseDirtyFlags() end
function Object:onMissionStarted() end
function Object:draw() end
function Object:superClass() end
function Object:removeDeleteListener() end
function Object:setOwner() end
function Object:onGhostAdd() end
function Object:onGhostRemove() end
function Object:mouseEvent() end
function Object:class() end
function Object:writeUpdateStream() end
function Object:readUpdateStream() end
function Object:writeStream() end
function Object:resetObjectIds() end
function Object:updateEnd() end
function Object:update() end
function Object:addDeleteListener() end
function Object:isa() end