ObjectIds = {}

ObjectIds.OBJECT_TRAIN_PLACEABLE = 55.000000
ObjectIds.OBJECT_VEHICLE_PLACEABLE = 52.000000
ObjectIds.MISSION_HARVEST = 72.000000
ObjectIds.OBJECT_BALE = 6.000000
ObjectIds.OBJECT_SILO_TRIGGER = 12.000000
ObjectIds.OBJECT_SILO_PLACEABLE = 47.000000
ObjectIds.OBJECT_ANIMAL_LOADING_TRIGGER = 10.000000
ObjectIds.objectIdToClass = {
    1 = {
        onEnter = function() end
        consoleCommandToggleSuperStrongMode = function() end
        getParentComponent = function() end
        playHandToolStopSample = function() end
        hasHandtoolEquipped = function() end
        onLeave = function() end
        onInputActivateHandtool = function() end
        updateFX = function() end
        onInputCycleHandTool = function() end
        deleteVisuals = function() end
        onInputCrouch = function() end
        drawUIInfo = function() end
        onPausGame = function() end
        groundRaycastCallback = function() end
        onInputEnter = function() end
        onInputDebugFlyUpDown = function() end
        checkObjectInRange = function() end
        rotateObject = function() end
        kinematicCollisionMask = 2148532228.000000
        onInputLookLeftRight = function() end
        setFarm = function() end
        onInputThrowObject = function() end
        onInputToggleLight = function() end
        setVisibility = function() end
        updatePlayerStates = function() end
        onInputInteract = function() end
        COLLISIONMASK_TRIGGER = 1048576.000000
        onInputJump = function() end
        onInputDebugFlyToggle = function() end
        testScope = function() end
        loadHandTool = function() end
        updateInterpolation = function() end
        deleteHandToolStopSample = function() end
        draw = function() end
        setWoodWorkVisibility = function() end
        onInputRun = function() end
        consoleCommandToggleWoodCuttingMaker = function() end
        onPickedUpObjectJointBreak = function() end
        setCuttingAnim = function() end
        updateSound = function() end
        resetBrake = function() end
        loadVisuals = function() end
        onInputLookUpDown = function() end
        INPUT_ACTIVE_TYPE = {
            IS_DEBUG = 5.000000
            STARTS_DISABLED = 1.000000
            STARTS_ENABLED = 2.000000
            IS_CARRYING = 4.000000
            IS_MOVEMENT = 3.000000
        }
        MAX_PICKABLE_OBJECT_DISTANCE = 3.000000
        class = function() end
        getIsInputAllowed = function() end
        readUpdateStream = function() end
        movementCollisionMask = 2148532255.000000
        load = function() end
        removeActionEvents = function() end
        moveToAbsoluteInternal = function() end
        updatePlayHandToolStopSample = function() end
        BUTTONSTATES = {
            PRESSED = 2.000000
            RELEASED = 3.000000
            JUST_PRESSED = 1.000000
        }
        pickUpObject = function() end
        onLeaveVehicle = function() end
        updateAnimationParameters = function() end
        updateHandTools = function() end
        consoleCommandToggleFlightAndNoHUDMode = function() end
        new = function() end
        onFarmChange = function() end
        consoleCommandTogglePlayerDebug = function() end
        setWalkingLock = function() end
        onInputActivateObject = function() end
        delete = function() end
        updateKinematic = function() end
        INPUT_CONTEXT_NAME = 'PLAYER'
        getPositionData = function() end
        updateTick = function() end
        recordPositionInformation = function() end
        update = function() end
        updateWaterParms = function() end
        getDesiredSpeed = function() end
        consoleCommandReloadIKChains = function() end
        loadHandToolStopSample = function() end
        lockInput = function() end
        deleteStartleAnimalData = function() end
        resetInputsInformation = function() end
        getUpdatePriority = function() end
        throwObject = function() end
        equipHandtool = function() end
        MAX_PICKABLE_OBJECT_MASS = 0.200000
        movePlayer = function() end
        getCurrentSurfaceSound = function() end
        updateRotation = function() end
        onInputMoveForward = function() end
        moveTo = function() end
        cameraBob = function() end
        onInputRotateObjectHorizontally = function() end
        calculate2DDotProductAgainstVelocity = function() end
        pickUpObjectRaycastCallback = function() end
        readStream = function() end
        unequipHandtool = function() end
        onInputRotateObjectVertically = function() end
        deleteStartleAnimalSound = function() end
        setLightIsActive = function() end
        registerActionEvents = function() end
        isa = function() end
        superClass = function() end
        onInputMoveSide = function() end
        setRotation = function() end
        PICKED_UP_OBJECTS = {
        }
        moveRootNodeToAbsolute = function() end
        classId = 1.000000
        moveToExitPoint = function() end
        mouseEvent = function() end
        onGhostAdd = function() end
        onGhostRemove = function() end
        updateActionEvents = function() end
        getEquippedHandtoolFilename = function() end
        writeUpdateStream = function() end
        setIKDirty = function() end
        writeStream = function() end
        className = 'Player'
        updateNetworkMovementHistory = function() end
        moveToAbsolute = function() end
        copy = function() end
        updateInterpolationTick = function() end
        resetCameraInputsInformation = function() end
        debugDraw = function() end
    }
    2 = {
        getLastSpeed = function() end
        setMassDirty = function() end
        unselectVehicle = function() end
        onVehicleWakeUpCallback = function() end
        setWorldPosition = function() end
        PROPERTY_STATE_NONE = 0.000000
        getPrice = function() end
        copy = function() end
        getCanToggleSelectable = function() end
        getRootVehicle = function() end
        getReloadXML = function() end
        addSubselection = function() end
        getSpecValueSlots = function() end
        getIsAIActive = function() end
        registerSelectableObjects = function() end
        doCollisionMaskCheck = function() end
        deactivate = function() end
        setAbsolutePosition = function() end
        setComponentJointRotLimit = function() end
        setComponentJointFrame = function() end
        clearActionEventsTable = function() end
        PROPERTY_STATE_OWNED = 1.000000
        load = function() end
        getIsReadyForAutomatedTrainTravel = function() end
        addNodeObjectMapping = function() end
        registerInteractionFlag = function() end
        saveStatsToXMLFile = function() end
        getIsActive = function() end
        loadSchemaOverlay = function() end
        SPRING_SCALE = 10.000000
        addToPhysics = function() end
        delete = function() end
        getDailyUpkeep = function() end
        INPUT_CONTEXT_NAME = 'VEHICLE'
        updateTick = function() end
        loadComponentJointFromXML = function() end
        STATE_CHANGE_LOWER_ALL_IMPLEMENTS = 3.000000
        registerEvents = function() end
        loadComponentFromXML = function() end
        getName = function() end
        raiseStateChange = function() end
        getIsActiveForSound = function() end
        setRelativePosition = function() end
        setLoadingState = function() end
        getActiveFarm = function() end
        getSpecValueDailyUpkeep = function() end
        updateSelectableObjects = function() end
        getSpeedLimit = function() end
        setSelectedVehicle = function() end
        writeUpdateStream = function() end
        className = 'Vehicle'
        registerStateChange = function() end
        getSelectedVehicle = function() end
        selectVehicle = function() end
        getParentComponent = function() end
        getLimitedVehicleYPosition = function() end
        STATE_CHANGE_ATTACH = 1.000000
        getCanBeReset = function() end
        setSelectedObject = function() end
        drawUIInfo = function() end
        removeFromPhysics = function() end
        getWorkLoad = function() end
        PROPERTY_STATE_SHOP_CONFIG = 4.000000
        PROPERTY_STATE_MISSION = 3.000000
        getTotalMass = function() end
        getTailwaterDepth = function() end
        getSelectedObject = function() end
        isa = function() end
        STATE_CHANGE_AI_START_LINE = 6.000000
        draw = function() end
        getSellPrice = function() end
        STATE_CHANGE_MOTOR_TURN_ON = 4.000000
        hasInputConflictWithSelection = function() end
        getIsSelected = function() end
        INTERACTION_FLAG_NONE = 0.000000
        setOperatingTime = function() end
        getAdditionalComponentMass = function() end
        readUpdateStream = function() end
        STATE_CHANGE_AI_END_LINE = 7.000000
        STATE_CHANGE_MOTOR_TURN_OFF = 5.000000
        STATE_CHANGE_DETACH = 2.000000
        new = function() end
        getIsOperating = function() end
        getIsOnField = function() end
        getDistanceToNode = function() end
        loadSpecValueCombinations = function() end
        getSpecValueSpeedLimit = function() end
        loadSpecValueSpeedLimit = function() end
        getSpecValueWorkingWidth = function() end
        STATE_CHANGE_FILLTYPE_CHANGE = 8.000000
        getSpecValueOperatingTime = function() end
        addActionEvent = function() end
        actionEventToggleSelection = function() end
        registerFunctions = function() end
        getFullName = function() end
        getIsInUse = function() end
        init = function() end
        getOwner = function() end
        interact = function() end
        defaultLength = 8.000000
        addVehicleToAIImplementList = function() end
        getCanBeSelected = function() end
        writeStream = function() end
        loadSpecValueWorkingWidth = function() end
        loadFinished = function() end
        getDeactivateOnLeave = function() end
        getInteractionHelp = function() end
        getCanBePickedUp = function() end
        removeNodeObjectMapping = function() end
        defaultWidth = 8.000000
        NUM_INTERACTION_FLAGS = 0.000000
        DAMAGED_SPEEDLIMIT_REDUCTION = 0.300000
        saveToXMLFile = function() end
        updateActionEvents = function() end
        getChildVehicles = function() end
        createComponentJoint = function() end
        setWorldPositionQuaternion = function() end
        getAdditionalSchemaText = function() end
        getIsLowered = function() end
        PROPERTY_STATE_LEASED = 2.000000
        getRepairPrice = function() end
        readStream = function() end
        superClass = function() end
        getUpdatePriority = function() end
        removeActionEvents = function() end
        getVehicleDamage = function() end
        registerActionEvents = function() end
        getOperatingTime = function() end
        requestActionEventUpdate = function() end
        setBroken = function() end
        updateVehicleSpeed = function() end
        getIsVehicleNode = function() end
        dayChanged = function() end
        classId = 2.000000
        updateMass = function() end
        activate = function() end
        removeActionEvent = function() end
        getIsActiveForInput = function() end
        prefixSchemaOverlayName = function() end
        update = function() end
        getSpecValueCombinations = function() end
        getFillLevelInformation = function() end
        getCanByMounted = function() end
        updateEnd = function() end
        class = function() end
        doCheckSpeedLimit = function() end
        setComponentJointTransLimit = function() end
        NUM_STATE_CHANGES = 8.000000
        getSpecValueAge = function() end
        debugNetworkUpdate = false
    }
    3 = {
        new = function() end
        unregister = function() end
        delete = function() end
        clearDirtyFlags = function() end
        register = function() end
        updateTick = function() end
        raiseActive = function() end
        setOwnerFarmId = function() end
        getNextDirtyFlag = function() end
        copy = function() end
        getOwnerFarmId = function() end
        getUpdatePriority = function() end
        readStream = function() end
        testScope = function() end
        raiseDirtyFlags = function() end
        onMissionStarted = function() end
        draw = function() end
        superClass = function() end
        classId = 3.000000
        removeDeleteListener = function() end
        setOwner = function() end
        onGhostAdd = function() end
        onGhostRemove = function() end
        mouseEvent = function() end
        class = function() end
        writeUpdateStream = function() end
        readUpdateStream = function() end
        writeStream = function() end
        className = 'Object'
        resetObjectIds = function() end
        updateEnd = function() end
        nextObjectId = 4.000000
        update = function() end
        addDeleteListener = function() end
        isa = function() end
    }
    4 = {
        new = function() end
        isa = function() end
        delete = function() end
        getDefaultRigidBodyType = function() end
        superClass = function() end
        updateMove = function() end
        updateTick = function() end
        onPhysicObjectWakeUpCallback = function() end
        update = function() end
        classId = 4.000000
        loadOnCreate = function() end
        onGhostRemove = function() end
        onGhostAdd = function() end
        copy = function() end
        setWorldPositionQuaternion = function() end
        class = function() end
        writeUpdateStream = function() end
        readUpdateStream = function() end
        writeStream = function() end
        className = 'PhysicsObject'
        getUpdatePriority = function() end
        testScope = function() end
        addChildsToNodeObject = function() end
        setNodeId = function() end
        readStream = function() end
        getAllowsAutoDelete = function() end
    }
    5 = {
        unmount = function() end
        getMeshNodes = function() end
        new = function() end
        mount = function() end
        testScope = function() end
        delete = function() end
        superClass = function() end
        unmountDynamic = function() end
        updateTick = function() end
        classId = 5.000000
        mountDynamic = function() end
        dynamicMountTriggerCallback = function() end
        copy = function() end
        class = function() end
        getUpdatePriority = function() end
        className = 'MountableObject'
        onDynamicMountJointBreak = function() end
        setNodeId = function() end
        getSupportsMountDynamic = function() end
        isa = function() end
        getAllowsAutoDelete = function() end
    }
    6 = {
        unmount = function() end
        new = function() end
        delete = function() end
        getSupportsTensionBelts = function() end
        loadFromMemory = function() end
        loadFromXMLFile = function() end
        setColor = function() end
        copy = function() end
        getFillLevel = function() end
        setCanBeSold = function() end
        getValue = function() end
        getMeshNodes = function() end
        readStream = function() end
        mount = function() end
        isa = function() end
        superClass = function() end
        createNode = function() end
        classId = 6.000000
        getFillType = function() end
        getTensionBeltNodeId = function() end
        className = 'Bale'
        load = function() end
        class = function() end
        getCanBeSold = function() end
        readUpdateStream = function() end
        writeStream = function() end
        loadExtraAttributesFromXMLFile = function() end
        setFillLevel = function() end
        setWrappingState = function() end
        saveToXMLFile = function() end
        setNodeId = function() end
        writeUpdateStream = function() end
        applyExtraAttributes = function() end
    }
    9 = {
        getTensionBeltNodeId = function() end
        getSupportsTensionBelts = function() end
        loadFromMemory = function() end
        new = function() end
        load = function() end
        class = function() end
        setNodeId = function() end
        copy = function() end
        delete = function() end
        className = 'MissionPhysicsObject'
        superClass = function() end
        writeStream = function() end
        readStream = function() end
        isa = function() end
        createNode = function() end
        classId = 9.000000
    }
    10 = {
        onCreate = function() end
        new = function() end
        getAnimals = function() end
        isa = function() end
        showAnimalScreen = function() end
        delete = function() end
        onSelectedHusbandry = function() end
        superClass = function() end
        drawActivate = function() end
        classId = 10.000000
        updateActivatableObject = function() end
        triggerCallback = function() end
        copy = function() end
        class = function() end
        onActivateObject = function() end
        className = 'AnimalLoadingTrigger'
        getIsActivatable = function() end
        load = function() end
        setLoadingTrailer = function() end
    }
    11 = {
        feed = function() end
        new = function() end
        delete = function() end
        idleStay = function() end
        updateTick = function() end
        update = function() end
        playerInteractionTriggerCallback = function() end
        pet = function() end
        copy = function() end
        getUpdatePriority = function() end
        saveToXMLFile = function() end
        hourChanged = function() end
        setVisibility = function() end
        idleWander = function() end
        followEntity = function() end
        readStream = function() end
        isa = function() end
        superClass = function() end
        onPlayerLeave = function() end
        playerFarmChanged = function() end
        classId = 11.000000
        teleportToSpawn = function() end
        goToSpawn = function() end
        onGhostAdd = function() end
        onGhostRemove = function() end
        resetSteeringParms = function() end
        class = function() end
        writeUpdateStream = function() end
        readUpdateStream = function() end
        writeStream = function() end
        setName = function() end
        isAbandoned = function() end
        className = 'Dog'
        fetchItem = function() end
        load = function() end
        loadFromXMLFile = function() end
        testScope = function() end
    }
    13 = {
        getTarget = function() end
        loadBaleTrigger = function() end
        new = function() end
        getFillUnitIndexFromNode = function() end
        isa = function() end
        getFillUnitExactFillRootNode = function() end
        delete = function() end
        getCustomDischargeNotAllowedWarning = function() end
        superClass = function() end
        getFillUnitSupportsFillType = function() end
        loadFillTypes = function() end
        getFillUnitFreeCapacity = function() end
        update = function() end
        classId = 13.000000
        getIsFillAllowedFromFarm = function() end
        loadAvoidFillTypes = function() end
        getIsFillTypeSupported = function() end
        copy = function() end
        getIsFillTypeAllowed = function() end
        class = function() end
        loadAcceptedToolType = function() end
        getFillUnitAllowsFillType = function() end
        getFillUnitSupportsToolType = function() end
        load = function() end
        baleTriggerCallback = function() end
        setTarget = function() end
        addFillUnitFillLevel = function() end
        updateBales = function() end
        className = 'UnloadTrigger'
        getIsToolTypeAllowed = function() end
    }
    14 = {
        new = function() end
        isa = function() end
        delete = function() end
        getFillTargetNode = function() end
        superClass = function() end
        onFillTypeSelection = function() end
        drawActivate = function() end
        classId = 14.000000
        setSource = function() end
        setFillSoundIsPlaying = function() end
        copy = function() end
        getCurrentFillType = function() end
        class = function() end
        update = function() end
        stopLoading = function() end
        onActivateObject = function() end
        className = 'LoadTrigger'
        startLoading = function() end
        setIsLoading = function() end
        farmIdForFillableObject = function() end
        getIsActivatable = function() end
        loadTriggerCallback = function() end
        load = function() end
    }
    15 = {
        new = function() end
        isa = function() end
        delete = function() end
        superClass = function() end
        loadFromXMLFile = function() end
        getCapacity = function() end
        hasFarmAccessToStorage = function() end
        classId = 15.000000
        removeTargetStorage = function() end
        getIsFillAllowedFromFarm = function() end
        getIsFillTypeSupported = function() end
        copy = function() end
        addFillLevelFromTool = function() end
        class = function() end
        getIsToolTypeAllowed = function() end
        getFillLevel = function() end
        writeStream = function() end
        className = 'UnloadingStation'
        saveToXMLFile = function() end
        load = function() end
        getIsFillTypeAllowed = function() end
        readStream = function() end
        getFreeCapacity = function() end
        addTargetStorage = function() end
    }
    16 = {
        setIsInGreatDemand = function() end
        PRICE_HIGH = 4.000000
        new = function() end
        getSupportsGreatDemand = function() end
        setPriceMultiplier = function() end
        addAcceptedFillType = function() end
        PRICE_FALLING = 1.000000
        executePriceDrop = function() end
        PRICE_LOW = 3.000000
        copy = function() end
        doPriceDrop = function() end
        PRICE_DROP_DELAY = 3600000.000000
        saveToXMLFile = function() end
        getTotalReceived = function() end
        addTargetStorage = function() end
        getPriceMultiplier = function() end
        readStream = function() end
        isa = function() end
        getIncomeNameForFillType = function() end
        PRICE_GREAT_DEMAND = 5.000000
        getAppearsOnStats = function() end
        superClass = function() end
        getIsFillAllowedFromFarm = function() end
        update = function() end
        addFillLevelFromTool = function() end
        updatePrices = function() end
        classId = 16.000000
        getCurrentPricingTrend = function() end
        initPricingDynamics = function() end
        loadFromXMLFile = function() end
        sellFillType = function() end
        load = function() end
        getIsFillTypeAllowed = function() end
        writeUpdateStream = function() end
        readUpdateStream = function() end
        writeStream = function() end
        className = 'SellingStation'
        PRICE_CLIMBING = 2.000000
        class = function() end
        getTotalPaid = function() end
        updateTick = function() end
        getFreeCapacity = function() end
        getEffectiveFillTypePrice = function() end
    }
    17 = {
        new = function() end
        class = function() end
        getEffectiveFillTypePrice = function() end
        getAppearsOnStats = function() end
        isa = function() end
        load = function() end
        superClass = function() end
        getSupportsGreatDemand = function() end
        className = 'BgaSellStation'
        copy = function() end
        getCurrentPricingTrend = function() end
        classId = 17.000000
    }
    18 = {
        getProvidedFillTypes = function() end
        getIsFillAllowedToFarm = function() end
        new = function() end
        addFillLevelToFillableObject = function() end
        class = function() end
        getIncomeNameForFillType = function() end
        getAllFillLevels = function() end
        className = 'BuyingStation'
        load = function() end
        superClass = function() end
        isa = function() end
        addSourceStorage = function() end
        copy = function() end
        update = function() end
        classId = 18.000000
    }
    19 = {
        getIsFillAllowedToFarm = function() end
        new = function() end
        isa = function() end
        delete = function() end
        superClass = function() end
        loadFromXMLFile = function() end
        updateProvidedFillTyes = function() end
        getProvidedFillTypes = function() end
        removeSourceStorage = function() end
        copy = function() end
        readStream = function() end
        class = function() end
        getSourceStorages = function() end
        load = function() end
        writeStream = function() end
        className = 'LoadingStation'
        saveToXMLFile = function() end
        getAllFillLevels = function() end
        addSourceStorage = function() end
        classId = 19.000000
        hasFarmAccessToStorage = function() end
        addFillLevelToFillableObject = function() end
    }
    20 = {
        loadFillTypes = function() end
        new = function() end
        addFillUnitFillLevel = function() end
        class = function() end
        copy = function() end
        initFillTypesFromFoodGroups = function() end
        updateAnimalPlaces = function() end
        load = function() end
        superClass = function() end
        loadAnimalPlaces = function() end
        className = 'UnloadFeedingTrough'
        addFoodMixtureFillType = function() end
        isa = function() end
        classId = 20.000000
    }
    21 = {
        setSource = function() end
        fillLevelsChanged = function() end
        new = function() end
        writeStream = function() end
        class = function() end
        writeUpdateStream = function() end
        readUpdateStream = function() end
        delete = function() end
        load = function() end
        superClass = function() end
        readStream = function() end
        className = 'FillLevelListener'
        copy = function() end
        isa = function() end
        classId = 21.000000
    }
    22 = {
        isAnimalDirty = function() end
        getAnimals = function() end
        getCanBeRidden = function() end
        loadFromXMLFile = function() end
        getSpecValueNumberAnimals = function() end
        initPlaceableType = function() end
        copy = function() end
        isRideableInOnHusbandryGround = function() end
        getSupportsSubType = function() end
        getMaxNumAnimals = function() end
        getTypedAnimals = function() end
        updateGlobalProductionFactor = function() end
        removeSingleAnimal = function() end
        getConsumedFood = function() end
        getFluidStatsText = function() end
        hourChanged = function() end
        getManureFilltypeInfo = function() end
        canBuy = function() end
        hasStraw = function() end
        isa = function() end
        getProductionFilltypeInfo = function() end
        modulesFinalizePlacement = function() end
        getHusbandryModule = function() end
        getFoodProductionFactor = function() end
        getLiquidManureFilltypeInfo = function() end
        setModuleParameters = function() end
        getReproductionTimePerDay = function() end
        class = function() end
        getGlobalDirtFactor = function() end
        readUpdateStream = function() end
        getAnimalSubTypeCount = function() end
        collectPickObjects = function() end
        getWaterFilltypeInfo = function() end
        renameAnimal = function() end
        finalizePlacement = function() end
        new = function() end
        getHusbandryId = function() end
        getNumOfAnimals = function() end
        update = function() end
        minuteChanged = function() end
        getMilkFilltypeInfo = function() end
        getSpecValueAnimalFoodFillTypes = function() end
        loadSpecValueAnimalFoodFillTypes = function() end
        canBeSold = function() end
        hasWater = function() end
        onIntervalModulesUpdate = function() end
        registerHusbandryToMission = function() end
        loadSpecValueNumberAnimals = function() end
        saveToXMLFile = function() end
        isSimilarHusbandryRegistered = function() end
        getFoodFilltypeInfo = function() end
        getModuleByName = function() end
        getSupportsRiding = function() end
        getCanBePlacedAt = function() end
        setAnimalDirt = function() end
        getPalletsFilltypeInfo = function() end
        addSingleAnimal = function() end
        readStream = function() end
        removeAnimals = function() end
        getGlobalProductionFactor = function() end
        cleanAnimal = function() end
        removeRideable = function() end
        GAME_LIMIT = 10.000000
        addRideable = function() end
        superClass = function() end
        getFilltype = function() end
        addPendingAnimal = function() end
        NO_FILLTYPE_INFOS = {
        }
        dayChanged = function() end
        onSell = function() end
        load = function() end
        classId = 22.000000
        getAnimalName = function() end
        addAnimals = function() end
        getMinutesUntilNextAnimal = function() end
        loadModules = function() end
        getAnimalType = function() end
        writeUpdateStream = function() end
        writeStream = function() end
        className = 'AnimalHusbandry'
        getFoodSpillageFactor = function() end
        getStrawFilltypeInfo = function() end
        canAddMoreHusbandriesToGame = function() end
        getModuleById = function() end
        unregisterHusbandryToMission = function() end
        delete = function() end
    }
    23 = {
        new = function() end
        isa = function() end
        delete = function() end
        superClass = function() end
        update = function() end
        classId = 23.000000
        getIsInWater = function() end
        removeFarAwayAnimals = function() end
        copy = function() end
        countSpawned = function() end
        class = function() end
        createAnimals = function() end
        getClosestDistance = function() end
        load = function() end
        groundRaycastCallback = function() end
        getTerrainHeightWithProps = function() end
        className = 'LightWildlife'
        removeAllAnimals = function() end
    }
    24 = {
        getAverageLocationOfIdleAnimals = function() end
        treeSearchCallback = function() end
        searchTree = function() end
        new = function() end
        isa = function() end
        CROW_STATES = {
            1 = {
                class = {
TABLE_EXCEED_DEPTH
                }
                id = 'default'
            }
            2 = {
                class = {
TABLE_EXCEED_DEPTH
                }
                id = 'fly_glide'
            }
            3 = {
                class = {
TABLE_EXCEED_DEPTH
                }
                id = 'fly'
            }
            4 = {
                class = {
TABLE_EXCEED_DEPTH
                }
                id = 'land'
            }
            5 = {
                class = {
TABLE_EXCEED_DEPTH
                }
                id = 'takeOff'
            }
            6 = {
                class = {
TABLE_EXCEED_DEPTH
                }
                id = 'idle_walk'
            }
            7 = {
                class = {
TABLE_EXCEED_DEPTH
                }
                id = 'idle_eat'
            }
            8 = {
                class = {
TABLE_EXCEED_DEPTH
                }
                id = 'idle_attention'
            }
        }
        load = function() end
        createAnimals = function() end
        delete = function() end
        className = 'CrowsWildlife'
        superClass = function() end
        CROW_SOUND_STATES = {
            NONE = 1.000000
            CALM_AIR = 3.000000
            CALM_GROUND = 2.000000
            BUSY = 4.000000
            TAKEOFF = 5.000000
        }
        class = function() end
        copy = function() end
        update = function() end
        classId = 24.000000
    }
    25 = {
        getValueScale = function() end
        new = function() end
        isa = function() end
        getFillTypeIndex = function() end
        delete = function() end
        createFromFillType = function() end
        superClass = function() end
        clean = function() end
        loadFromXMLFile = function() end
        createFromXMLFile = function() end
        getDirtScale = function() end
        classId = 25.000000
        getOwner = function() end
        readStream = function() end
        getSubType = function() end
        copy = function() end
        getVisualId = function() end
        class = function() end
        writeUpdateStream = function() end
        readUpdateStream = function() end
        writeStream = function() end
        className = 'Animal'
        saveToXMLFile = function() end
        setVisualId = function() end
        getValue = function() end
        setOwner = function() end
        setDirtScale = function() end
        getIsInUse = function() end
    }
    26 = {
        getValueScale = function() end
        new = function() end
        isa = function() end
        onFitnessChangedCallback = function() end
        updateFitness = function() end
        superClass = function() end
        onLoadedRideable = function() end
        loadFromXMLFile = function() end
        deactivateRiding = function() end
        getTodaysRidingTime = function() end
        classId = 26.000000
        readStream = function() end
        DAILY_TARGET_RIDING_TIME = 300000.000000
        setHealthScale = function() end
        copy = function() end
        setFitnessScale = function() end
        class = function() end
        writeUpdateStream = function() end
        readUpdateStream = function() end
        writeStream = function() end
        setName = function() end
        saveToXMLFile = function() end
        getFitnessScale = function() end
        getName = function() end
        getHealthScale = function() end
        DAILY_MINIMUM_RIDING_TIME = 60000.000000
        className = 'Horse'
    }
    27 = {
        getIsRideableSetupDone = function() end
        isOnHusbandyGround = function() end
        activateRiding = function() end
        tryToFinishRideable = function() end
        deactivateRiding = function() end
        delete = function() end
        superClass = function() end
        loadFromXMLFile = function() end
        classId = 27.000000
        onLoadedRideable = function() end
        readStream = function() end
        copy = function() end
        onDirtChangedCallback = function() end
        class = function() end
        getCanBeRidden = function() end
        new = function() end
        writeStream = function() end
        className = 'RideableAnimal'
        saveToXMLFile = function() end
        setVisualId = function() end
        isa = function() end
        finishRideable = function() end
        setDirtScale = function() end
        getIsInUse = function() end
    }
    28 = {
        onCreate = function() end
        new = function() end
        getInteractionPosition = function() end
        delete = function() end
        updateTick = function() end
        update = function() end
        STATE_FERMENTED = 2.000000
        getCanInteract = function() end
        copy = function() end
        saveToXMLFile = function() end
        getCanOpenSilo = function() end
        setState = function() end
        readStream = function() end
        clearSiloArea = function() end
        isa = function() end
        getCanCloseSilo = function() end
        getIsCloserToFront = function() end
        STATE_DRAIN = 3.000000
        superClass = function() end
        switchFillTypeAtOffset = function() end
        classId = 28.000000
        onChangedFillLevelCallback = function() end
        STATE_CLOSED = 1.000000
        interactionTriggerCallback = function() end
        COMPACTING_BASE_MASS = 5.000000
        className = 'BunkerSilo'
        class = function() end
        writeUpdateStream = function() end
        readUpdateStream = function() end
        writeStream = function() end
        load = function() end
        STATE_FILL = 0.000000
        openSilo = function() end
        getBunkerAreaOffset = function() end
        NUM_STATES = 4.000000
        updateFillLevel = function() end
        loadFromXMLFile = function() end
    }
    31 = {
        setTrainSystem = function() end
        new = function() end
        class = function() end
        registerFunctions = function() end
        className = 'RailroadVehicle'
        superClass = function() end
        isa = function() end
        copy = function() end
        classId = 31.000000
    }
    32 = {
        onCreate = function() end
        removeUnloadingStation = function() end
        new = function() end
        addUnloadingStation = function() end
        isa = function() end
        getSupportedFillTypes = function() end
        getFreeCapacity = function() end
        delete = function() end
        load = function() end
        superClass = function() end
        register = function() end
        loadFromXMLFile = function() end
        getCapacity = function() end
        update = function() end
        classId = 32.000000
        setOwnerFarmId = function() end
        dayChanged = function() end
        getIsFillTypeSupported = function() end
        copy = function() end
        getFillLevel = function() end
        class = function() end
        writeUpdateStream = function() end
        readUpdateStream = function() end
        writeStream = function() end
        className = 'Bga'
        saveToXMLFile = function() end
        setFillLevel = function() end
        getFillTypeLiterPrice = function() end
        updateTick = function() end
        addDigestate = function() end
        readStream = function() end
    }
    34 = {
        PREVIEW_RAMP_COLOR = {
            1 = {
                1 = 0.000000
                2 = 1.000000
                3 = 1.000000
                4 = 1.000000
            }
            2 = {
                1 = 0.000000
                2 = 1.000000
                3 = 1.000000
                4 = 1.000000
            }
            3 = {
                1 = 1.000000
                2 = 0.000000
                3 = 0.000000
                4 = 1.000000
            }
        }
        getTerrainModificationBlockingAreas = function() end
        isInActionDistance = function() end
        initPose = function() end
        loadFromXMLFile = function() end
        loadHotspotFromXML = function() end
        initPlaceableType = function() end
        onCreateGlowMaterial = function() end
        getPrice = function() end
        copy = function() end
        getSpecValueIncomePerHour = function() end
        setCollisionMask = function() end
        getPositionSnapSize = function() end
        isMapBound = function() end
        hourChanged = function() end
        clearFoliageAndTipAreas = function() end
        canBuy = function() end
        isa = function() end
        getRotationSnapAngle = function() end
        getSellPrice = function() end
        deleteFinal = function() end
        getPositionSnapOffset = function() end
        getIsPlayerInRange = function() end
        getNeedsSaving = function() end
        alignToTerrain = function() end
        loadAreasFromXML = function() end
        load = function() end
        collectPickObjects = function() end
        setPlaceablePreviewState = function() end
        PREVIEW_COLOR = {
            1 = {
                1 = 1.000000
                2 = 1.000000
                3 = 0.000000
                4 = 1.000000
            }
            2 = {
                1 = 0.000000
                2 = 1.000000
                3 = 0.000000
                4 = 1.000000
            }
            3 = {
                1 = 1.000000
                2 = 0.000000
                3 = 0.000000
                4 = 1.000000
            }
        }
        finalizePlacement = function() end
        setPreviewMaterials = function() end
        new = function() end
        loadSpecValueIncomePerHour = function() end
        RAMP_PREVIEW_THICKNESS = 0.200000
        delete = function() end
        getDailyUpkeep = function() end
        updateTick = function() end
        update = function() end
        setOwnerFarmId = function() end
        getIsAreaOwned = function() end
        canBeSold = function() end
        getName = function() end
        loadAreaFromXML = function() end
        PREVIEW_STATE = {
            INVALID = 3.000000
            VALID = 2.000000
            CHECKING = 1.000000
        }
        getCanBePlacedAt = function() end
        getPlacementRotation = function() end
        superClass = function() end
        dayChanged = function() end
        onSell = function() end
        saveToXMLFile = function() end
        createNode = function() end
        readUpdateStream = function() end
        loadFoliageAreaFromXML = function() end
        class = function() end
        writeUpdateStream = function() end
        classId = 34.000000
        writeStream = function() end
        className = 'Placeable'
        onBuy = function() end
        readStream = function() end
        setTipOcclusionAreaDirty = function() end
        getPlacementPosition = function() end
        RAMP_PREVIEW_PATH = '$data/placeables/shared/rampPreview.i3d'
        weatherChanged = function() end
    }
    35 = {
        finalizePlacement = function() end
        readStream = function() end
        isa = function() end
        delete = function() end
        initPose = function() end
        loadFromXMLFile = function() end
        createNode = function() end
        classId = 35.000000
        copy = function() end
        class = function() end
        className = 'WindTurbinePlaceable'
        writeStream = function() end
        load = function() end
        saveToXMLFile = function() end
        update = function() end
        superClass = function() end
        hourChanged = function() end
        new = function() end
        updateHeadRotation = function() end
    }
    36 = {
        updateHeadRotation = function() end
        new = function() end
        isa = function() end
        delete = function() end
        initPose = function() end
        loadFromXMLFile = function() end
        createNode = function() end
        deleteFinal = function() end
        copy = function() end
        class = function() end
        superClass = function() end
        update = function() end
        writeStream = function() end
        load = function() end
        saveToXMLFile = function() end
        classId = 36.000000
        readStream = function() end
        hourChanged = function() end
        className = 'SolarCollectorPlaceable'
        finalizePlacement = function() end
    }
    37 = {
        new = function() end
        class = function() end
        delete = function() end
        className = 'BeehivePlaceable'
        superClass = function() end
        isa = function() end
        load = function() end
        hourChanged = function() end
        copy = function() end
        classId = 37.000000
    }
    38 = {
        finalizePlacement = function() end
        readStream = function() end
        setWaterTankFillLevel = function() end
        isa = function() end
        addFillLevelFromTool_OLD = function() end
        delete = function() end
        onWaterTankTrigger = function() end
        superClass = function() end
        removeWaterTrailer = function() end
        loadFromXMLFile = function() end
        addWaterTrailer = function() end
        createNode = function() end
        classId = 38.000000
        setManureFillLevel = function() end
        getShowInfo = function() end
        setIsWaterTankFilling = function() end
        copy = function() end
        getAllowFillTypeFromTool = function() end
        class = function() end
        writeUpdateStream = function() end
        readUpdateStream = function() end
        writeStream = function() end
        load = function() end
        saveToXMLFile = function() end
        update = function() end
        updateTick = function() end
        hourChanged = function() end
        className = 'GreenhousePlaceable'
        new = function() end
    }
    39 = {
        onHandtoolDelete = function() end
        new = function() end
        isa = function() end
        delete = function() end
        activateHandtool = function() end
        superClass = function() end
        updateTick = function() end
        getIsActiveForInput = function() end
        update = function() end
        setIsTurnedOn = function() end
        copy = function() end
        class = function() end
        canBeSold = function() end
        classId = 39.000000
        getHighPressureWasherLoad = function() end
        className = 'HighPressureWasher'
        onDeactivate = function() end
        load = function() end
        getIsActiveForSound = function() end
        readStream = function() end
        onPlayerDelete = function() end
        writeStream = function() end
    }
    40 = {
        finalizePlacement = function() end
        saveToXMLFile = function() end
        new = function() end
        readStream = function() end
        class = function() end
        getNeedsSaving = function() end
        copy = function() end
        delete = function() end
        className = 'TreePlaceable'
        superClass = function() end
        writeStream = function() end
        loadFromXMLFile = function() end
        isa = function() end
        createNode = function() end
        classId = 40.000000
    }
    41 = {
        finalizePlacement = function() end
        new = function() end
        isa = function() end
        delete = function() end
        getSpecValueVolume = function() end
        superClass = function() end
        loadFromXMLFile = function() end
        classId = 41.000000
        setOwnerFarmId = function() end
        copy = function() end
        loadSpecValueVolume = function() end
        class = function() end
        canBeSold = function() end
        getCanBePlacedAt = function() end
        writeStream = function() end
        load = function() end
        saveToXMLFile = function() end
        onSell = function() end
        readStream = function() end
        initPlaceableType = function() end
        className = 'SiloExtensionPlaceable'
        PRICE_SELL_FACTOR = 0.600000
    }
    42 = {
        finalizePlacement = function() end
        new = function() end
        class = function() end
        copy = function() end
        delete = function() end
        className = 'WoodCrusherPlaceable'
        superClass = function() end
        onCrushedSplitShape = function() end
        updateTick = function() end
        isa = function() end
        update = function() end
        classId = 42.000000
    }
    43 = {
        onUpdateEvent = function() end
        readStream = function() end
        isa = function() end
        delete = function() end
        superClass = function() end
        updateTick = function() end
        update = function() end
        classId = 43.000000
        copy = function() end
        class = function() end
        writeUpdateStream = function() end
        readUpdateStream = function() end
        writeStream = function() end
        load = function() end
        collectPickObjects = function() end
        className = 'HeatingPlantPlaceable'
        new = function() end
    }
    44 = {
        setOwnerFarmId = function() end
        new = function() end
        class = function() end
        delete = function() end
        className = 'Workshop'
        superClass = function() end
        load = function() end
        isa = function() end
        copy = function() end
        classId = 44.000000
    }
    45 = {
        finalizePlacement = function() end
        canBuy = function() end
        new = function() end
        isa = function() end
        delete = function() end
        unregisterDoghouseToMission = function() end
        superClass = function() end
        registerDoghouseToMission = function() end
        loadFromXMLFile = function() end
        isDoghouseRegistered = function() end
        update = function() end
        classId = 45.000000
        setOwnerFarmId = function() end
        playerInteractionTriggerCallback = function() end
        drawActivate = function() end
        copy = function() end
        getIsActivatable = function() end
        class = function() end
        writeUpdateStream = function() end
        readUpdateStream = function() end
        writeStream = function() end
        className = 'Doghouse'
        saveToXMLFile = function() end
        onActivateObject = function() end
        drawDogName = function() end
        setFoodVisibility = function() end
        readStream = function() end
        getCanBePlacedAt = function() end
    }
    46 = {
        new = function() end
        class = function() end
        delete = function() end
        className = 'WaterTower'
        superClass = function() end
        load = function() end
        isa = function() end
        copy = function() end
        classId = 46.000000
    }
    47 = {
        finalizePlacement = function() end
        new = function() end
        isa = function() end
        setAmount = function() end
        delete = function() end
        getSpecValueVolume = function() end
        superClass = function() end
        loadFromXMLFile = function() end
        initPlaceableType = function() end
        setOwnerFarmId = function() end
        copy = function() end
        loadSpecValueVolume = function() end
        class = function() end
        canBeSold = function() end
        onSell = function() end
        writeStream = function() end
        load = function() end
        saveToXMLFile = function() end
        collectPickObjects = function() end
        classId = 47.000000
        readStream = function() end
        className = 'SiloPlaceable'
        PRICE_SELL_FACTOR = 0.700000
    }
    48 = {
        finalizePlacement = function() end
        saveToXMLFile = function() end
        new = function() end
        load = function() end
        class = function() end
        readStream = function() end
        writeStream = function() end
        delete = function() end
        className = 'SellingStationPlaceable'
        superClass = function() end
        collectPickObjects = function() end
        loadFromXMLFile = function() end
        isa = function() end
        copy = function() end
        classId = 48.000000
    }
    49 = {
        finalizePlacement = function() end
        new = function() end
        class = function() end
        readStream = function() end
        writeStream = function() end
        delete = function() end
        className = 'BuyingStationPlaceable'
        superClass = function() end
        collectPickObjects = function() end
        load = function() end
        isa = function() end
        copy = function() end
        classId = 49.000000
    }
    50 = {
        onCreate = function() end
        registerActionEventsWhenInRange = function() end
        new = function() end
        updateActionEventTexts = function() end
        isa = function() end
        removeActionEvents = function() end
        delete = function() end
        superClass = function() end
        loadFromXMLFile = function() end
        update = function() end
        classId = 50.000000
        setFrameValues = function() end
        className = 'AnimatedObject'
        triggerCallback = function() end
        copy = function() end
        setAnimTime = function() end
        class = function() end
        writeUpdateStream = function() end
        readUpdateStream = function() end
        writeStream = function() end
        load = function() end
        saveToXMLFile = function() end
        readStream = function() end
        onAnimationInputToggle = function() end
        hourChanged = function() end
        loadFrameValues = function() end
        onAnimationInputContinuous = function() end
    }
    51 = {
        onCreate = function() end
        new = function() end
        class = function() end
        delete = function() end
        className = 'AnimatedMapObject'
        superClass = function() end
        load = function() end
        isa = function() end
        copy = function() end
        classId = 51.000000
    }
    52 = {
        new = function() end
        class = function() end
        onDeleteObject = function() end
        delete = function() end
        load = function() end
        superClass = function() end
        className = 'VehiclePlaceable'
        loadFromXMLFile = function() end
        copy = function() end
        isa = function() end
        classId = 52.000000
    }
    53 = {
        canBuy = function() end
        new = function() end
        isa = function() end
        delete = function() end
        getSpawnPoint = function() end
        sleepingTriggerCallback = function() end
        getIsActivatable = function() end
        classId = 53.000000
        canPlaceHouse = function() end
        getSpawnWorldPosition = function() end
        copy = function() end
        class = function() end
        onActivateObject = function() end
        className = 'FarmhousePlaceable'
        drawActivate = function() end
        load = function() end
        getSleepCamera = function() end
        superClass = function() end
        getCanBePlacedAt = function() end
    }
    55 = {
        setIsTrainTabbable = function() end
        new = function() end
        getElectricitySplineLength = function() end
        isa = function() end
        onLoadFinished = function() end
        getSplineLength = function() end
        delete = function() end
        onDeleteObject = function() end
        superClass = function() end
        load = function() end
        loadFromXMLFile = function() end
        removeSplinePositionUpdateListener = function() end
        update = function() end
        classId = 55.000000
        setSplineTime = function() end
        updateTrainLength = function() end
        readStream = function() end
        copy = function() end
        updateTrainPositionByLocomotiveSpeed = function() end
        class = function() end
        writeUpdateStream = function() end
        readUpdateStream = function() end
        writeStream = function() end
        className = 'TrainPlaceable'
        saveToXMLFile = function() end
        addSplinePositionUpdateListener = function() end
        getSplineTime = function() end
        getElectricitySpline = function() end
        setRequestedSplinePosition = function() end
        updateTrainPositionByLocomotiveSplinePosition = function() end
    }
    56 = {
        new = function() end
        isa = function() end
        delete = function() end
        superClass = function() end
        woodTriggerCallback = function() end
        getIsActivatable = function() end
        classId = 56.000000
        copy = function() end
        woodSellTriggerCallback = function() end
        class = function() end
        onActivateObject = function() end
        className = 'WoodSellStationPlaceable'
        sellWood = function() end
        drawActivate = function() end
        load = function() end
        removeUpdateEventListener = function() end
        calculateBaseValue = function() end
        addUpdateEventListener = function() end
    }
    57 = {
        finalizePlacement = function() end
        new = function() end
        isa = function() end
        delete = function() end
        superClass = function() end
        loadFromXMLFile = function() end
        classId = 57.000000
        setOwnerFarmId = function() end
        copy = function() end
        class = function() end
        writeStream = function() end
        load = function() end
        saveToXMLFile = function() end
        collectPickObjects = function() end
        onFarmlandStateChanged = function() end
        updateOwnership = function() end
        className = 'BgaPlaceable'
        readStream = function() end
    }
    58 = {
        saveToXMLFile = function() end
        finalizePlacement = function() end
        load = function() end
        new = function() end
        onSell = function() end
        class = function() end
        writeStream = function() end
        readStream = function() end
        delete = function() end
        className = 'BunkerSiloPlaceable'
        superClass = function() end
        collectPickObjects = function() end
        loadFromXMLFile = function() end
        isa = function() end
        copy = function() end
        classId = 58.000000
    }
    59 = {
        new = function() end
        isa = function() end
        removeActionEvents = function() end
        delete = function() end
        getDailyUpkeep = function() end
        onDeactivate = function() end
        handToolTypes = {
            chainsaw = {
                isCuttingAllowed = function() end
                updateDelimb = function() end
                new = function() end
                testTooLow = function() end
                updateParticles = function() end
                delete = function() end
                onDeactivate = function() end
                updateCuttingTimers = function() end
                update = function() end
                copy = function() end
                resetTransitionState = function() end
                calculateCutDuration = function() end
                CAMERA_TRANSITION_STATES = {
TABLE_EXCEED_DEPTH
                }
                updateCuttingCamera = function() end
                getLookAt = function() end
                SOUND_STATES = {
TABLE_EXCEED_DEPTH
                }
                isa = function() end
                registerActionEvents = function() end
                updateCutRaycast = function() end
                superClass = function() end
                cutRaycastCallback = function() end
                setCutting = function() end
                classId = 60.000000
                class = function() end
                getChainSpeedFactor = function() end
                onInputRotate = function() end
                onActivate = function() end
                updateRingSelector = function() end
                isBeingUsed = function() end
                getCutShapeInformation = function() end
                load = function() end
                className = 'Chainsaw'
                updateChainsawModel = function() end
                getCutStartEnd = function() end
            }
            highPressureWasherLance = {
                isBeingUsed = function() end
                copy = function() end
                isa = function() end
                new = function() end
                setIsWashing = function() end
                class = function() end
                cleanVehicle = function() end
                washRaycastCallback = function() end
                delete = function() end
                load = function() end
                superClass = function() end
                onDeactivate = function() end
                className = 'HighPressureWasherLance'
                getIsActiveForInput = function() end
                update = function() end
                classId = 61.000000
            }
        }
        loadFromXMLFile = function() end
        update = function() end
        classId = 59.000000
        copy = function() end
        class = function() end
        registerActionEvents = function() end
        isBeingUsed = function() end
        onActivate = function() end
        load = function() end
        saveToXMLFile = function() end
        dayChanged = function() end
        getSellPrice = function() end
        setHandNode = function() end
        superClass = function() end
        className = 'HandTool'
    }
    60 = {
        isCuttingAllowed = function() end
        updateDelimb = function() end
        new = function() end
        testTooLow = function() end
        updateParticles = function() end
        delete = function() end
        onDeactivate = function() end
        updateCuttingTimers = function() end
        update = function() end
        copy = function() end
        resetTransitionState = function() end
        calculateCutDuration = function() end
        CAMERA_TRANSITION_STATES = {
            IN = 0.000000
            NONE = -1.000000
            OUT = 2.000000
            CUT = 1.000000
        }
        updateCuttingCamera = function() end
        getLookAt = function() end
        SOUND_STATES = {
            ACTIVE = 4.000000
            STOP = 2.000000
            QUICKTAP = 6.000000
            START = 1.000000
            IDLE = 3.000000
            CUT = 5.000000
        }
        isa = function() end
        registerActionEvents = function() end
        updateCutRaycast = function() end
        superClass = function() end
        cutRaycastCallback = function() end
        setCutting = function() end
        classId = 60.000000
        class = function() end
        getChainSpeedFactor = function() end
        onInputRotate = function() end
        onActivate = function() end
        updateRingSelector = function() end
        isBeingUsed = function() end
        getCutShapeInformation = function() end
        load = function() end
        className = 'Chainsaw'
        updateChainsawModel = function() end
        getCutStartEnd = function() end
    }
    61 = {
        isBeingUsed = function() end
        copy = function() end
        isa = function() end
        new = function() end
        setIsWashing = function() end
        class = function() end
        cleanVehicle = function() end
        washRaycastCallback = function() end
        delete = function() end
        load = function() end
        superClass = function() end
        onDeactivate = function() end
        className = 'HighPressureWasherLance'
        getIsActiveForInput = function() end
        update = function() end
        classId = 61.000000
    }
    62 = {
        onCreate = function() end
        new = function() end
        class = function() end
        load = function() end
        copy = function() end
        delete = function() end
        className = 'Basketball'
        superClass = function() end
        writeStream = function() end
        readStream = function() end
        isa = function() end
        createNode = function() end
        classId = 62.000000
    }
    63 = {
        reset = function() end
        RESET_DISTANCE = 100.000000
        new = function() end
        load = function() end
        class = function() end
        readStream = function() end
        isa = function() end
        delete = function() end
        className = 'DogBall'
        superClass = function() end
        writeStream = function() end
        updateTick = function() end
        copy = function() end
        createNode = function() end
        classId = 63.000000
    }
    65 = {
        readStream = function() end
        isa = function() end
        removeUnloadingStation = function() end
        removeLoadingStation = function() end
        delete = function() end
        addLoadingStation = function() end
        superClass = function() end
        farmDestroyed = function() end
        loadFromXMLFile = function() end
        getCapacity = function() end
        addUnloadingStation = function() end
        classId = 65.000000
        getFillLevel = function() end
        getSupportedFillTypes = function() end
        getIsFillTypeSupported = function() end
        copy = function() end
        load = function() end
        class = function() end
        writeUpdateStream = function() end
        readUpdateStream = function() end
        writeStream = function() end
        className = 'Storage'
        saveToXMLFile = function() end
        empty = function() end
        setFillLevel = function() end
        hourChanged = function() end
        getFreeCapacity = function() end
        new = function() end
    }
    66 = {
        merge = function() end
        getUserPermissions = function() end
        farmPropertyChanged = function() end
        new = function() end
        getFarmhouse = function() end
        getNumActivePlayers = function() end
        getHandTools = function() end
        COLOR_SPECTATOR = {
            1 = 0.000000
            2 = 0.000000
            3 = 0.000000
            4 = 0.000000
        }
        delete = function() end
        setUserPermission = function() end
        EQUITY_LOAN_RATIO = 0.800000
        loadFromXMLFile = function() end
        calculateDailyLoanInterest = function() end
        removeHandTool = function() end
        updateLastNickname = function() end
        copy = function() end
        onUserQuitGame = function() end
        getActiveUsers = function() end
        canBeDestroyed = function() end
        isUserFarmManager = function() end
        DEFAULT_PERMISSIONS = {
        }
        NO_PERMISSIONS = {
        }
        saveToXMLFile = function() end
        removeUser = function() end
        addUser = function() end
        addHandTool = function() end
        hasHandtool = function() end
        dayChanged = function() end
        getLoan = function() end
        getBalance = function() end
        changeBalance = function() end
        readStream = function() end
        MAX_LOAN = 3000000.000000
        getSleepCamera = function() end
        promoteUser = function() end
        updateMaxLoan = function() end
        getEquity = function() end
        onUserJoinGame = function() end
        getSpawnPoint = function() end
        getIsContractingFor = function() end
        COLORS = {
            1 = {
                1 = 0.250000
                2 = 1.000000
                3 = 0.250000
                4 = 1.000000
            }
            2 = {
                1 = 0.000000
                2 = 0.044600
                3 = 0.187000
                4 = 1.000000
            }
            3 = {
                1 = 0.938600
                2 = 0.467800
                3 = 0.012300
                4 = 1.000000
            }
            4 = {
                1 = 0.883200
                2 = 0.163600
                3 = 0.004600
                4 = 1.000000
            }
            5 = {
                1 = 0.573200
                2 = 0.005000
                3 = 0.005000
                4 = 1.000000
            }
            6 = {
                1 = 0.000000
                2 = 0.234800
                3 = 0.796900
                4 = 1.000000
            }
            7 = {
                1 = 0.887900
                2 = 0.054500
                3 = 0.300500
                4 = 1.000000
            }
            8 = {
                1 = 0.090800
                2 = 0.004000
                3 = 0.130100
                4 = 1.000000
            }
        }
        getColor = function() end
        setIsContractingFor = function() end
        classId = 66.000000
        demoteUser = function() end
        setInitialEconomy = function() end
        getNumPlayers = function() end
        COLOR_SEND_NUM_BITS = 4.000000
        LOAN_INTEREST_RATE = 100.000000
        PERMISSIONS = {
            1 = 'buyVehicle'
            2 = 'sellVehicle'
            3 = 'buyPlaceable'
            4 = 'sellPlaceable'
            5 = 'manageContracts'
            6 = 'tradeAnimals'
            7 = 'createFields'
            8 = 'hireAssistant'
            9 = 'resetVehicle'
            10 = 'manageRights'
            11 = 'transferMoney'
            12 = 'manageContracts'
            13 = 'updateFarm'
            14 = 'manageContracting'
        }
        writeUpdateStream = function() end
        readUpdateStream = function() end
        writeStream = function() end
        className = 'Farm'
        resetToSingleplayer = function() end
        superClass = function() end
        class = function() end
        MIN_LOAN = 500000.000000
        PERMISSION = {
            MANAGE_RIGHTS = 'manageRights'
            UPDATE_FARM = 'updateFarm'
            MANAGE_CONTRACTING = 'manageContracting'
            TRADE_ANIMALS = 'tradeAnimals'
            TRANSFER_MONEY = 'transferMoney'
            RESET_VEHICLE = 'resetVehicle'
            SELL_VEHICLE = 'sellVehicle'
            SELL_PLACEABLE = 'sellPlaceable'
            BUY_PLACEABLE = 'buyPlaceable'
            BUY_VEHICLE = 'buyVehicle'
            CREATE_FIELDS = 'createFields'
            HIRE_ASSISTANT = 'hireAssistant'
            MANAGE_CONTRACTS = 'manageContracts'
        }
        isa = function() end
    }
    67 = {
        calculateStealingCost = function() end
        new = function() end
        delete = function() end
        getCompletion = function() end
        loadFromXMLFile = function() end
        init = function() end
        update = function() end
        copy = function() end
        getExtraProgressText = function() end
        saveToXMLFile = function() end
        readStream = function() end
        getNPC = function() end
        isa = function() end
        validate = function() end
        farmDestroyed = function() end
        SUCCESS_FACTOR = 0.950000
        hasField = function() end
        classId = 67.000000
        STATUS_STOPPED = 0.000000
        updateTick = function() end
        start = function() end
        getData = function() end
        STATUS_FINISHED = 2.000000
        class = function() end
        writeUpdateStream = function() end
        readUpdateStream = function() end
        dismiss = function() end
        className = 'AbstractMission'
        writeStream = function() end
        started = function() end
        finish = function() end
        hasLeasableVehicles = function() end
        superClass = function() end
        STATUS_RUNNING = 1.000000
    }
    68 = {
        destroyMapMarker = function() end
        new = function() end
        isSpawnSpaceAvailable = function() end
        REWARD_PER_HA = 800.000000
        delete = function() end
        loadNextVehicleCallback = function() end
        getCompletion = function() end
        loadFromXMLFile = function() end
        init = function() end
        update = function() end
        getMaxCutLiters = function() end
        REIMBURSEMENT_FACTOR = 0.950000
        copy = function() end
        loadNextVehicle = function() end
        getFieldSize = function() end
        hasLeasableVehicles = function() end
        saveToXMLFile = function() end
        FIELD_SIZE_MEDIUM = 1.500000
        resetField = function() end
        readStream = function() end
        getNPC = function() end
        isa = function() end
        canRunOnField = function() end
        hasMapMarker = function() end
        createMapMarkerAtSellingStation = function() end
        calculateReimbursement = function() end
        superClass = function() end
        addToMissionMap = function() end
        VEHICLE_USE_COST = 200.000000
        getVehicleGroup = function() end
        hasField = function() end
        classId = 68.000000
        calculateVehicleUseCost = function() end
        calculateReward = function() end
        onVehicleReset = function() end
        finish = function() end
        getFieldCompletion = function() end
        class = function() end
        getVehicleGroupFromIdentifier = function() end
        started = function() end
        dismiss = function() end
        className = 'AbstractFieldMission'
        removeAccess = function() end
        completeField = function() end
        writeStream = function() end
        getVehicleVariant = function() end
        FIELD_SIZE_LARGE = 5.000000
        start = function() end
    }
    69 = {
        validate = function() end
        readStream = function() end
        getStationName = function() end
        isa = function() end
        fillSold = function() end
        canRunOnField = function() end
        delete = function() end
        getData = function() end
        superClass = function() end
        getCompletion = function() end
        loadFromXMLFile = function() end
        init = function() end
        REWARD_PER_HA_HAY = 3000.000000
        classId = 69.000000
        SILAGE_VARIANT_CHANCE = 0.500000
        new = function() end
        roundToWholeBales = function() end
        copy = function() end
        REWARD_PER_HA_SILAGE = 3300.000000
        class = function() end
        update = function() end
        partitionCompletion = function() end
        writeStream = function() end
        className = 'BaleMission'
        saveToXMLFile = function() end
        completeField = function() end
        start = function() end
        getVehicleVariant = function() end
        FILL_SUCCESS_FACTOR = 0.900000
        updateRewardPerHa = function() end
    }
    70 = {
        validate = function() end
        new = function() end
        partitionCompletion = function() end
        isa = function() end
        getData = function() end
        REWARD_PER_HA = 600.000000
        canRunOnField = function() end
        className = 'CultivateMission'
        superClass = function() end
        completeField = function() end
        finish = function() end
        class = function() end
        copy = function() end
        classId = 70.000000
    }
    71 = {
        REIMBURSEMENT_PER_HA = 950.000000
        copy = function() end
        validate = function() end
        isa = function() end
        partitionCompletion = function() end
        REWARD_PER_HA = 400.000000
        getData = function() end
        className = 'FertilizeMission'
        superClass = function() end
        completeField = function() end
        canRunOnField = function() end
        new = function() end
        class = function() end
        classId = 71.000000
    }
    72 = {
        calculateStealingCost = function() end
        new = function() end
        delete = function() end
        getCompletion = function() end
        loadFromXMLFile = function() end
        init = function() end
        update = function() end
        copy = function() end
        REWARD_PER_HA_SMALL = 4800.000000
        createModifiers = function() end
        getExtraProgressText = function() end
        fillSold = function() end
        readStream = function() end
        getStationName = function() end
        isa = function() end
        FAILURE_COST_OF_TOTAL = 0.950000
        superClass = function() end
        getHighestSellPointPrice = function() end
        start = function() end
        classId = 72.000000
        validate = function() end
        REWARD_PER_HA_WIDE = 1500.000000
        getData = function() end
        getFruitInVehicles = function() end
        class = function() end
        FAILURE_COST_FACTOR = 0.100000
        partitionCompletion = function() end
        writeStream = function() end
        className = 'HarvestMission'
        saveToXMLFile = function() end
        completeField = function() end
        finish = function() end
        getVehicleVariant = function() end
        canRunOnField = function() end
        updateRewardPerHa = function() end
    }
    73 = {
        validate = function() end
        new = function() end
        partitionCompletion = function() end
        isa = function() end
        getData = function() end
        REWARD_PER_HA = 1400.000000
        canRunOnField = function() end
        className = 'PlowMission'
        superClass = function() end
        completeField = function() end
        finish = function() end
        class = function() end
        copy = function() end
        classId = 73.000000
    }
    74 = {
        readStream = function() end
        isa = function() end
        REWARD_PER_HA = 1000.000000
        superClass = function() end
        loadFromXMLFile = function() end
        init = function() end
        decideFruitType = function() end
        classId = 74.000000
        validate = function() end
        finish = function() end
        getData = function() end
        copy = function() end
        canRunOnField = function() end
        class = function() end
        createModifier = function() end
        partitionCompletion = function() end
        writeStream = function() end
        className = 'SowMission'
        saveToXMLFile = function() end
        completeField = function() end
        updateReimbursement = function() end
        getVehicleVariant = function() end
        start = function() end
        new = function() end
    }
    75 = {
        resetField = function() end
        canRunOnField = function() end
        getNewWeedState = function() end
        isa = function() end
        REWARD_PER_HA = 250.000000
        superClass = function() end
        start = function() end
        classId = 75.000000
        REIMBURSEMENT_PER_HA = 1000.000000
        getData = function() end
        class = function() end
        partitionCompletion = function() end
        className = 'SprayMission'
        completeField = function() end
        validate = function() end
        new = function() end
        copy = function() end
    }
    76 = {
        getPickupTrigger = function() end
        new = function() end
        hasHotspots = function() end
        delete = function() end
        createHotspot = function() end
        getCompletion = function() end
        loadFromXMLFile = function() end
        init = function() end
        update = function() end
        objectLeftTrigger = function() end
        getTriggerInfo = function() end
        getDropoffTrigger = function() end
        REWARD_PER_METER = 0.200000
        destroyHotspots = function() end
        createHotspots = function() end
        updateTriggerVisibility = function() end
        calculateReward = function() end
        readStream = function() end
        getNPC = function() end
        isa = function() end
        createObject = function() end
        superClass = function() end
        canRun = function() end
        getData = function() end
        getTriggerTitle = function() end
        start = function() end
        CONTRACT_DURATION = 115200000.000000
        objectEnteredTrigger = function() end
        collisionTestCallback = function() end
        isTriggerEmpty = function() end
        finish = function() end
        TEST_HEIGHT = 50.000000
        class = function() end
        CONTRACT_DURATION_VAR = 57600000.000000
        copy = function() end
        dismiss = function() end
        className = 'TransportMission'
        writeStream = function() end
        NUM_OBJECTS_PER_DRIVE = 5.000000
        saveToXMLFile = function() end
        loadObjects = function() end
        REWARD_PER_OBJECT = 200.000000
        classId = 76.000000
    }
    77 = {
        new = function() end
        validate = function() end
        isa = function() end
        partitionCompletion = function() end
        REWARD_PER_HA = 400.000000
        getData = function() end
        className = 'WeedMission'
        superClass = function() end
        completeField = function() end
        canRunOnField = function() end
        class = function() end
        copy = function() end
        classId = 77.000000
    }
    78 = {
        onCreate = function() end
        new = function() end
        isa = function() end
        setEnabled = function() end
        delete = function() end
        superClass = function() end
        onIndoorStateChanged = function() end
        updateTick = function() end
        update = function() end
        classId = 78.000000
        reset = function() end
        copy = function() end
        class = function() end
        writeUpdateStream = function() end
        readUpdateStream = function() end
        setNightTimeRange = function() end
        className = 'TrafficSystem'
        load = function() end
    }
    139 = {
        new = function() end
        isa = function() end
        delete = function() end
        className = 'FillTriggerPlaceable'
        superClass = function() end
        load = function() end
        class = function() end
        copy = function() end
        classId = 139.000000
    }
}
ObjectIds.OBJECT_OBJECT = 3.000000
ObjectIds.OBJECT_ANIMAL = 25.000000
function ObjectIds:assignObjectClassId() end
ObjectIds.OBJECT_WOOD_CRUSHER_PLACEABLE = 42.000000
ObjectIds.OBJECT_WORKSHOP_PLACEABLE = 44.000000
ObjectIds.OBJECT_RIDEABLE_ANIMAL = 27.000000
ObjectIds.OBJECT_BGA_SELLING_STATION = 17.000000
ObjectIds.OBJECT_VEHICLE = 2.000000
function ObjectIds:assignObjectClassIds() end
ObjectIds.OBJECT_WOOD_SELL_STATION_PLACEABLE = 56.000000
function ObjectIds:assignObjectClassObjectId() end
ObjectIds.OBJECT_HIGHPRESSURE_WASHER_PLACEABLE = 39.000000
ObjectIds.OBJECT_FILLLEVEL_LISTENER = 21.000000
ObjectIds.OBJECT_HEATING_PLANT_PLACEABLE = 43.000000
ObjectIds.OBJECT_WIND_TURBINE_PLACEABLE = 35.000000
ObjectIds.OBJECT_BUYING_STATION_PLACEABLE = 49.000000
ObjectIds.OBJECT_UNLOAD_TRIGGER = 13.000000
ObjectIds.OBJECT_GREENHOUSE_PLACEABLE = 38.000000
ObjectIds.OBJECT_WATERTOWER_PLACEABLE = 46.000000
ObjectIds.OBJECT_LOADING_STATION = 19.000000
ObjectIds.OBJECT_MOUNTABLE_OBJECT = 5.000000
ObjectIds.FARM = 66.000000
ObjectIds.MAX_OBJECT_ID = 65535.000000
ObjectIds.MISSION_PLOW = 73.000000
ObjectIds.OBJECT_UNLOAD_FEEDING_TROUGH = 20.000000
function ObjectIds:getObjectClassByName() end
ObjectIds.OBJECT_DOGHOUSE_PLACEABLE = 45.000000
ObjectIds.SEND_NUM_BITS = 16.000000
ObjectIds.OBJECT_TRAIN = 30.000000
ObjectIds.OBJECT_PHYSICS_OBJECT = 4.000000
ObjectIds.OBJECT_BUNKER_SILO_TIP_TRIGGER = 29.000000
ObjectIds.TRAFFIC_SYSTEM = 78.000000
ObjectIds.OBJECT_PLACEABLE = 34.000000
ObjectIds.objectIdNext = 140.000000
ObjectIds.OBJECT_ANIMAL_LIGHT_WILDLIFE = 23.000000
ObjectIds.OBJECT_MISSION_PHYSICS_OBJECT = 9.000000
ObjectIds.OBJECT_FARMHOUSE_PLACEABLE = 53.000000
ObjectIds.MISSION_WEED = 77.000000
ObjectIds.OBJECT_BGA_TIP_TRIGGER = 33.000000
ObjectIds.MISSION_TRANSPORT = 76.000000
ObjectIds.OBJECT_BUYING_STATION = 18.000000
ObjectIds.MISSION_SPRAY = 75.000000
ObjectIds.OBJECT_STORAGE = 65.000000
ObjectIds.MISSION_FERTILIZE = 71.000000
ObjectIds.MISSION_SOW = 74.000000
ObjectIds.OBJECT_SAPLING_PALLET = 8.000000
ObjectIds.MISSION_FIELD = 68.000000
ObjectIds.MISSION = 67.000000
ObjectIds.OBJECT_ANIMATED_MAP_OBJECT = 51.000000
ObjectIds.MISSION_CULTIVATE = 70.000000
ObjectIds.OBJECT_CHAINSAW = 60.000000
ObjectIds.OBJECT_DOGBALL = 63.000000
ObjectIds.OBJECT_BASKETBALL = 62.000000
ObjectIds.OBJECT_HIGHPRESSUREWASHERLANCE = 61.000000
ObjectIds.OBJECT_RECIEVING_TIP_TRIGGER = 64.000000
ObjectIds.OBJECT_HANDTOOL = 59.000000
ObjectIds.OBJECT_BUNKERSILO_PLACEABLE = 58.000000
ObjectIds.OBJECT_BGA_PLACEABLE = 57.000000
ObjectIds.OBJECT_SILO_EXTENSION_PLACEABLE = 41.000000
ObjectIds.OBJECT_REFILLABLE_PLACEABLE = 54.000000
ObjectIds.OBJECT_BEEHIVE_PLACEABLE = 37.000000
ObjectIds.OBJECT_ANIMATED_OBJECT = 50.000000
ObjectIds.OBJECT_ANIMAL_CROWS_WILDLIFE = 24.000000
ObjectIds.OBJECT_TREE = 7.000000
ObjectIds.OBJECT_PLAYER = 1.000000
ObjectIds.OBJECT_UNLOADING_STATION = 15.000000
ObjectIds.objectClasses = {
    FillTriggerPlaceable = {
        new = function() end
        isa = function() end
        delete = function() end
        className = 'FillTriggerPlaceable'
        superClass = function() end
        load = function() end
        class = function() end
        copy = function() end
        classId = 139.000000
    }
}
ObjectIds.OBJECT_SELLING_STATION = 16.000000
ObjectIds.OBJECT_SOLAR_COLLECTOR_PLACEABLE = 36.000000
ObjectIds.OBJECT_HORSE = 26.000000
ObjectIds.OBJECT_ANIMAL_HUSBANDRY = 22.000000
ObjectIds.OBJECT_BGA = 32.000000
ObjectIds.OBJECT_RAILROADVEHICLE = 31.000000
ObjectIds.OBJECT_LOAD_TRIGGER = 14.000000
function ObjectIds:getObjectClassById() end
ObjectIds.OBJECT_TREE_PLACEABLE = 40.000000
ObjectIds.objectIdsUsed = {
    1 = true
    2 = true
    3 = true
    4 = true
    5 = true
    6 = true
    9 = true
    10 = true
    11 = true
    13 = true
    14 = true
    15 = true
    16 = true
    17 = true
    18 = true
    19 = true
    20 = true
    21 = true
    22 = true
    23 = true
    24 = true
    25 = true
    26 = true
    27 = true
    28 = true
    31 = true
    32 = true
    34 = true
    35 = true
    36 = true
    37 = true
    38 = true
    39 = true
    40 = true
    41 = true
    42 = true
    43 = true
    44 = true
    45 = true
    46 = true
    47 = true
    48 = true
    49 = true
    50 = true
    51 = true
    52 = true
    53 = true
    55 = true
    56 = true
    57 = true
    58 = true
    59 = true
    60 = true
    61 = true
    62 = true
    63 = true
    65 = true
    66 = true
    67 = true
    68 = true
    69 = true
    70 = true
    71 = true
    72 = true
    73 = true
    74 = true
    75 = true
    76 = true
    77 = true
    78 = true
    139 = true
}
ObjectIds.OBJECT_BUNKER_SILO = 28.000000
ObjectIds.MISSION_BALE = 69.000000
ObjectIds.OBJECT_DOG = 11.000000
ObjectIds.OBJECT_SELLING_STATION_PLACEABLE = 48.000000