Server = {}

function Server:stop() end
function Server:setClientPosition() end
function Server:packetReceived() end
function Server:isa() end
function Server:consoleCommandToggleNetworkDebug() end
function Server:prioCmp() end
function Server:delete() end
function Server:registerObjectInStream() end
function Server:registerObject() end
function Server:getClientClipDistCoeff() end
function Server:sendObjectClassIds() end
function Server:init() end
function Server:start() end
function Server:broadcastEvent() end
function Server:setClientClipDistCoeff() end
function Server:sendObjects() end
function Server:removeStreamFromClients() end
function Server:copy() end
function Server:mouseEvent() end
function Server:class() end
function Server:hasGhostObject() end
function Server:finishRegisterObject() end
function Server:closeConnection() end
function Server:getClientPosition() end
function Server:sendEventIds() end
function Server:new() end
function Server:unregisterObject() end
function Server:update() end
function Server:startLocal() end
function Server:superClass() end