PlayerStyle = {}

function PlayerStyle:getProtectiveVisibility() end
function PlayerStyle:readStream() end
function PlayerStyle:loadXML() end
function PlayerStyle:isa() end
function PlayerStyle:copySelection() end
function PlayerStyle:setHair() end
function PlayerStyle:setBody() end
function PlayerStyle:setJacket() end
function PlayerStyle:superClass() end
function PlayerStyle:removeAccessory() end
function PlayerStyle:linkProtectiveWear() end
function PlayerStyle:setColor() end
function PlayerStyle:copy() end
function PlayerStyle:updateHeadWearVisibility() end
function PlayerStyle:class() end
function PlayerStyle:setProtectiveUV() end
function PlayerStyle:setProtectiveVisibility() end
function PlayerStyle:unlinkProtectiveWear() end
function PlayerStyle:setHat() end
function PlayerStyle:setAccessory() end
function PlayerStyle:new() end
function PlayerStyle:applySelection() end
function PlayerStyle:removeHat() end
function PlayerStyle:writeStream() end
function PlayerStyle:setVisibility() end