Dog = {}

Dog.classId = 11.000000
Dog.className = 'Dog'

function Dog:feed() end
function Dog:new() end
function Dog:delete() end
function Dog:idleStay() end
function Dog:updateTick() end
function Dog:update() end
function Dog:playerInteractionTriggerCallback() end
function Dog:pet() end
function Dog:copy() end
function Dog:getUpdatePriority() end
function Dog:saveToXMLFile() end
function Dog:hourChanged() end
function Dog:setVisibility() end
function Dog:idleWander() end
function Dog:followEntity() end
function Dog:readStream() end
function Dog:isa() end
function Dog:superClass() end
function Dog:onPlayerLeave() end
function Dog:playerFarmChanged() end
function Dog:teleportToSpawn() end
function Dog:goToSpawn() end
function Dog:onGhostAdd() end
function Dog:onGhostRemove() end
function Dog:resetSteeringParms() end
function Dog:class() end
function Dog:writeUpdateStream() end
function Dog:readUpdateStream() end
function Dog:writeStream() end
function Dog:setName() end
function Dog:isAbandoned() end
function Dog:fetchItem() end
function Dog:load() end
function Dog:loadFromXMLFile() end
function Dog:testScope() end