EconomyManager = {}

EconomyManager.DEFAULT_RUNNING_LEASING_FACTOR = 0.050000
EconomyManager.CONFIG_CHANGE_PRICE = 1000.000000
EconomyManager.MAX_GREAT_DEMANDS = 3.000000
EconomyManager.DIRECT_SELL_MULTIPLIER = 1.200000
EconomyManager.PRICE_MULTIPLIER = {
    1 = 3.000000
    2 = 1.800000
    3 = 1.000000
}
EconomyManager.LIFETIME_OPERATINGTIME_RATIO = 0.083330
EconomyManager.COST_MULTIPLIER = {
    1 = 0.400000
    2 = 0.700000
    3 = 1.000000
}
EconomyManager.sendNumBits = 2.000000
EconomyManager.MAX_DAILYUPKEEP_MULTIPLIER = 4.000000
EconomyManager.PER_DAY_LEASING_FACTOR = 0.010000
EconomyManager.DEFAULT_LEASING_DEPOSIT_FACTOR = 0.020000
EconomyManager.PRICE_DROP_MIN_PERCENT = 0.600000

function EconomyManager:getGreatDemandId() end
function EconomyManager:new() end
function EconomyManager:delete() end
function EconomyManager:update() end
function EconomyManager:getBuyPrice() end
function EconomyManager:minuteChanged() end
function EconomyManager:getPricePerLiter() end
function EconomyManager:copy() end
function EconomyManager:saveToXMLFile() end
function EconomyManager:hourChanged() end
function EconomyManager:getPriceMultiplier() end
function EconomyManager:isa() end
function EconomyManager:getGreatDemandById() end
function EconomyManager:superClass() end
function EconomyManager:getSellPrice() end
function EconomyManager:dayChanged() end
function EconomyManager:getCostMultiplier() end
function EconomyManager:loadFromXMLFile() end
function EconomyManager:getInitialLeasingPrice() end
function EconomyManager:manageGreatDemands() end
function EconomyManager:getCostPerLiter() end
function EconomyManager:class() end
function EconomyManager:startGreatDemand() end
function EconomyManager:updateGreatDemandsPDASpots() end
function EconomyManager:restartGreatDemands() end
function EconomyManager:stopGreatDemand() end
function EconomyManager:vehicleOperatingHourChanged() end
function EconomyManager:getCurrentGreatDemand() end