FSDensityMapUtil = {}

FSDensityMapUtil.DEBUG_ENABLED = false

function FSDensityMapUtil:setWeedArea() end
function FSDensityMapUtil:convertToDensityMapAngle() end
function FSDensityMapUtil:assert() end
function FSDensityMapUtil:cutFruitArea() end
function FSDensityMapUtil:removeFieldArea() end
function FSDensityMapUtil:getFieldValue() end
function FSDensityMapUtil:updateDirectSowingArea() end
function FSDensityMapUtil:getFieldStatusAsync() end
function FSDensityMapUtil:updateWeederArea() end
function FSDensityMapUtil:updateFertilizerArea() end
function FSDensityMapUtil:getFieldDensity() end
function FSDensityMapUtil:eraseTireTrack() end
function FSDensityMapUtil:resetSprayArea() end
function FSDensityMapUtil:getStatus() end
function FSDensityMapUtil:getFruitArea() end
function FSDensityMapUtil:removeSprayArea() end
function FSDensityMapUtil:getTireTrackColorFromDensityBits() end
function FSDensityMapUtil:initTerrain() end
function FSDensityMapUtil:updateWheelDestructionArea() end
function FSDensityMapUtil:removeWeedArea() end
function FSDensityMapUtil:getWeedFactor() end
function FSDensityMapUtil:getFieldStatus() end
function FSDensityMapUtil:updateRollerArea() end
function FSDensityMapUtil:getAreaDensity() end
function FSDensityMapUtil:updatePlowArea() end
function FSDensityMapUtil:updateSubsoilerArea() end
function FSDensityMapUtil:setGroundTypeLayerArea() end
function FSDensityMapUtil:updateHerbicideArea() end
function FSDensityMapUtil:updateCultivatorArea() end
function FSDensityMapUtil:updateLimeArea() end
function FSDensityMapUtil:updateSprayArea() end
function FSDensityMapUtil:updateDestroyCommonArea() end
function FSDensityMapUtil:updateSowingArea() end
function FSDensityMapUtil:updateFruitPreparerArea() end