IKUtil = {}

function IKUtil:updateAlignNode() end
function IKUtil:setIKChainInactive() end
function IKUtil:loadRotationNodes() end
function IKUtil:setIKChainActive() end
function IKUtil:setIKChainDirty() end
function IKUtil:debugDrawChains() end
function IKUtil:updateAlignNodes() end
function IKUtil:updateIKChain() end
function IKUtil:loadIKChain() end
function IKUtil:loadIKChainTargets() end
function IKUtil:updateIKChains() end
function IKUtil:debugDrawChain() end
function IKUtil:setTarget() end
function IKUtil:deleteIKChain() end
function IKUtil:setIKChainPose() end
function IKUtil:getIKChainByTarget() end
function IKUtil:setRotationNodes() end