MathUtil = {}

function MathUtil:dotProduct() end
function MathUtil:lerp() end
function MathUtil:getFlooredBounded() end
function MathUtil:isPointInParallelogram() end
function MathUtil:getFlooredPercent() end
function MathUtil:minutesToMs() end
function MathUtil:hasRectangleLineIntersection2D() end
function MathUtil:getYRotationFromDirection() end
function MathUtil:getRotationLimitedVector2() end
function MathUtil:getCircleCircleIntersection() end
function MathUtil:inverseVector3Lerp() end
function MathUtil:clamp() end
function MathUtil:getProjectOnLineParameter() end
function MathUtil:vector2LengthSq() end
function MathUtil:getHaveLineSegementsIntersection2D() end
function MathUtil:kmhToMps() end
function MathUtil:getAngleDifference() end
function MathUtil:getBinary() end
function MathUtil:rpmToMps() end
function MathUtil:getValidLimit() end
function MathUtil:vector3Length() end
function MathUtil:lerp3() end
function MathUtil:vector3ArrayLerp() end
function MathUtil:sign() end
function MathUtil:vector2Normalize() end
function MathUtil:getDirectionFromYRotation() end
function MathUtil:round() end
function MathUtil:vector3Clamp() end
function MathUtil:getHasCircleLineIntersection() end
function MathUtil:vector2Length() end
function MathUtil:msToHours() end
function MathUtil:slerpQuaternion() end
function MathUtil:degToRad() end
function MathUtil:getBrightnessFromColor() end
function MathUtil:getCircleLineIntersection() end
function MathUtil:getSignedDistanceToLineSegment2D() end
function MathUtil:numberToSetBitsStr() end
function MathUtil:vector3Normalize() end
function MathUtil:msToDays() end
function MathUtil:hoursToMs() end
function MathUtil:bitsToMask() end
function MathUtil:mToInch() end
function MathUtil:daysToMs() end
function MathUtil:slerpQuaternionShortestPath() end
function MathUtil:hasSphereSphereIntersection() end
function MathUtil:crossProduct() end
function MathUtil:inverseVector3ArrayLerp() end
function MathUtil:getLineLineIntersection2D() end
function MathUtil:nlerpQuaternionShortestPath() end
function MathUtil:projectOnLine() end
function MathUtil:vector3SetLength() end
function MathUtil:vector3LengthSq() end
function MathUtil:getDistanceToRectangle2D() end
function MathUtil:isNan() end
function MathUtil:inchToM() end
function MathUtil:vector3Lerp() end
function MathUtil:quaternionNormalized() end
function MathUtil:getIsOutOfBounds() end
function MathUtil:quaternionMadShortestPath() end
function MathUtil:numberToSetBits() end
function MathUtil:getClosestPointOnLineSegment() end
function MathUtil:normalizeRotationForShortestPath() end
function MathUtil:areaToHa() end
function MathUtil:vector3Transformation() end
function MathUtil:quaternionMult() end
function MathUtil:getXZWidthAndHeight() end
function MathUtil:inverseLerp() end
function MathUtil:msToMinutes() end
function MathUtil:mpsToKmh() end