ParticleUtil = {}

function ParticleUtil:getParticleSystemAverageSpeed() end
function ParticleUtil:loadParticleSystem() end
function ParticleUtil:getParticleSystemSpeed() end
function ParticleUtil:setParticleSystemSpeed() end
function ParticleUtil:setParticleSystemSpriteScaleYGain() end
function ParticleUtil:deleteParticleSystem() end
function ParticleUtil:getParticleSystemSpeedRandom() end
function ParticleUtil:loadParticleSystemData() end
function ParticleUtil:setEmitCountScale() end
function ParticleUtil:setParticleSystemSpriteScaleY() end
function ParticleUtil:setParticleSystemNormalSpeed() end
function ParticleUtil:loadParticleSystemFromNode() end
function ParticleUtil:setParticleSystemSpeedRandom() end
function ParticleUtil:getParticleSystemSpriteScaleXGain() end
function ParticleUtil:addParticleSystemSimulationTime() end
function ParticleUtil:initEmitterScale() end
function ParticleUtil:copyParticleSystem() end
function ParticleUtil:setParticleSystemTimeScale() end
function ParticleUtil:getParticleSystemTangentSpeed() end
function ParticleUtil:getParticleSystemSpriteScaleX() end
function ParticleUtil:loadParticleSystemFromData() end
function ParticleUtil:setParticleSystemTangentSpeed() end
function ParticleUtil:resetNumOfEmittedParticles() end
function ParticleUtil:setParticleSystemSpriteScaleX() end
function ParticleUtil:setParticleLifespan() end
function ParticleUtil:setEmitterShape() end
function ParticleUtil:setEmittingState() end
function ParticleUtil:getParticleSystemNormalSpeed() end
function ParticleUtil:setParticleStartStopTime() end
function ParticleUtil:getParticleSystemSpriteScaleY() end
function ParticleUtil:getParticleSystemSpriteScaleYGain() end
function ParticleUtil:setParticleSystemSpriteScaleXGain() end
function ParticleUtil:deleteParticleSystems() end