Utils = {}

function Utils:getMasterVolumeFromIndex() end
function Utils:getTimeScaleIndex() end
function Utils:getModNameAndBaseDirectory() end
function Utils:getVersatileRotation() end
function Utils:appendedFunction() end
function Utils:isBitSet() end
function Utils:overwrittenFunction() end
function Utils:setMovedLimitedValues() end
function Utils:stringToBoolean() end
function Utils:renderMultiColumnText() end
function Utils:getUIScaleFromIndex() end
function Utils:getPerformanceClassIndex() end
function Utils:renderTextAtWorldPosition() end
function Utils:getMovedLimitedValue() end
function Utils:getFilename() end
function Utils:limitTextToWidth() end
function Utils:getFilenameInfo() end
function Utils:getCoinToss() end
function Utils:getStateFromValues() end
function Utils:getMasterVolumeIndex() end
function Utils:evaluateFormula() end
function Utils:getValueIndex() end
function Utils:setBit() end
function Utils:getUIScaleIndex() end
function Utils:getPerformanceClassId() end
function Utils:getPerformanceClassFromIndex() end
function Utils:getIntersectionOfLinearMovementAndTerrain() end
function Utils:formatTime() end
function Utils:getNormallyDistributedRandomVariables() end
function Utils:randomFloat() end
function Utils:prependedFunction() end
function Utils:getNumTimeScales() end
function Utils:getYRotationBetweenNodes() end
function Utils:shuffle() end
function Utils:getTimeScaleString() end
function Utils:getMovedLimitedValues() end
function Utils:getTimeScaleFromIndex() end
function Utils:getMaxJointForceLimit() end
function Utils:getNoNilRad() end
function Utils:clearBit() end
function Utils:getNoNil() end
function Utils:removeModDirectory() end
function Utils:get2DArray() end