AnimationManager = {}

function AnimationManager:stopAnimations() end
function AnimationManager:getAnimationClass() end
function AnimationManager:isa() end
function AnimationManager:superClass() end
function AnimationManager:registerAnimationClass() end
function AnimationManager:update() end
function AnimationManager:deleteAnimations() end
function AnimationManager:stopAnimation() end
function AnimationManager:class() end
function AnimationManager:copy() end
function AnimationManager:new() end
function AnimationManager:startAnimation() end
function AnimationManager:areAnimationsRunning() end
function AnimationManager:resetAnimations() end
function AnimationManager:resetAnimation() end
function AnimationManager:setFillType() end
function AnimationManager:loadAnimations() end
function AnimationManager:startAnimations() end
function AnimationManager:initDataStructures() end