AbstractFieldMission = {}

AbstractFieldMission.VEHICLE_USE_COST = 200.000000
AbstractFieldMission.classId = 68.000000
AbstractFieldMission.FIELD_SIZE_LARGE = 5.000000
AbstractFieldMission.className = 'AbstractFieldMission'
AbstractFieldMission.REWARD_PER_HA = 800.000000
AbstractFieldMission.REIMBURSEMENT_FACTOR = 0.950000
AbstractFieldMission.FIELD_SIZE_MEDIUM = 1.500000

function AbstractFieldMission:destroyMapMarker() end
function AbstractFieldMission:new() end
function AbstractFieldMission:isSpawnSpaceAvailable() end
function AbstractFieldMission:delete() end
function AbstractFieldMission:loadNextVehicleCallback() end
function AbstractFieldMission:getCompletion() end
function AbstractFieldMission:loadFromXMLFile() end
function AbstractFieldMission:init() end
function AbstractFieldMission:update() end
function AbstractFieldMission:getMaxCutLiters() end
function AbstractFieldMission:copy() end
function AbstractFieldMission:loadNextVehicle() end
function AbstractFieldMission:getFieldSize() end
function AbstractFieldMission:hasLeasableVehicles() end
function AbstractFieldMission:saveToXMLFile() end
function AbstractFieldMission:resetField() end
function AbstractFieldMission:readStream() end
function AbstractFieldMission:getNPC() end
function AbstractFieldMission:isa() end
function AbstractFieldMission:canRunOnField() end
function AbstractFieldMission:hasMapMarker() end
function AbstractFieldMission:createMapMarkerAtSellingStation() end
function AbstractFieldMission:calculateReimbursement() end
function AbstractFieldMission:superClass() end
function AbstractFieldMission:addToMissionMap() end
function AbstractFieldMission:getVehicleGroup() end
function AbstractFieldMission:hasField() end
function AbstractFieldMission:calculateVehicleUseCost() end
function AbstractFieldMission:calculateReward() end
function AbstractFieldMission:onVehicleReset() end
function AbstractFieldMission:finish() end
function AbstractFieldMission:getFieldCompletion() end
function AbstractFieldMission:class() end
function AbstractFieldMission:getVehicleGroupFromIdentifier() end
function AbstractFieldMission:started() end
function AbstractFieldMission:dismiss() end
function AbstractFieldMission:removeAccess() end
function AbstractFieldMission:completeField() end
function AbstractFieldMission:writeStream() end
function AbstractFieldMission:getVehicleVariant() end
function AbstractFieldMission:start() end