AbstractMission = {}

AbstractMission.className = 'AbstractMission'
AbstractMission.STATUS_RUNNING = 1.000000
AbstractMission.classId = 67.000000
AbstractMission.STATUS_STOPPED = 0.000000
AbstractMission.SUCCESS_FACTOR = 0.950000
AbstractMission.STATUS_FINISHED = 2.000000

function AbstractMission:calculateStealingCost() end
function AbstractMission:new() end
function AbstractMission:delete() end
function AbstractMission:getCompletion() end
function AbstractMission:loadFromXMLFile() end
function AbstractMission:init() end
function AbstractMission:update() end
function AbstractMission:copy() end
function AbstractMission:getExtraProgressText() end
function AbstractMission:saveToXMLFile() end
function AbstractMission:readStream() end
function AbstractMission:getNPC() end
function AbstractMission:isa() end
function AbstractMission:validate() end
function AbstractMission:farmDestroyed() end
function AbstractMission:hasField() end
function AbstractMission:updateTick() end
function AbstractMission:start() end
function AbstractMission:getData() end
function AbstractMission:class() end
function AbstractMission:writeUpdateStream() end
function AbstractMission:readUpdateStream() end
function AbstractMission:dismiss() end
function AbstractMission:writeStream() end
function AbstractMission:started() end
function AbstractMission:finish() end
function AbstractMission:hasLeasableVehicles() end
function AbstractMission:superClass() end