Field = {
  fieldId = 0,
  posZ = 0.000000,
  fruitType = 0,
  setFieldStatusPartitions = {},
  mapHotspot = {},
  fieldGrassMission = false,
  rootNode = 0,
  fieldDimensions = 0,
  getFieldStatusPartitions = {},
  nameIndicator = 0,
  fieldMissionAllowed = false,
  fieldArea = 0.000000,
  farmland = {},
  posX = 0.000000,
  maxFieldStatusPartitions = {},
  fieldAngle = 0,
  name = '',
  isAIActive = false
}

function Field:setFieldOwned() end
function Field:getIsAIActive() end
function Field:new() end
function Field:isa() end
function Field:delete() end
function Field:updateHotspotColor() end
function Field:deactivate() end
function Field:activate() end
function Field:copy() end
function Field:addMapHotspot() end
function Field:getCenterOfFieldWorldPosition() end
function Field:load() end
function Field:class() end
function Field:setFarmland() end
function Field:updateOwnership() end
function Field:setFieldId() end
function Field:superClass() end