HarvestMission = {}

HarvestMission.classId = 72.000000
HarvestMission.REWARD_PER_HA_WIDE = 1500.000000
HarvestMission.FAILURE_COST_FACTOR = 0.100000
HarvestMission.className = 'HarvestMission'
HarvestMission.REWARD_PER_HA_SMALL = 4800.000000
HarvestMission.FAILURE_COST_OF_TOTAL = 0.950000

function HarvestMission:calculateStealingCost() end
function HarvestMission:new() end
function HarvestMission:delete() end
function HarvestMission:getCompletion() end
function HarvestMission:loadFromXMLFile() end
function HarvestMission:init() end
function HarvestMission:update() end
function HarvestMission:copy() end
function HarvestMission:createModifiers() end
function HarvestMission:getExtraProgressText() end
function HarvestMission:fillSold() end
function HarvestMission:readStream() end
function HarvestMission:getStationName() end
function HarvestMission:isa() end
function HarvestMission:superClass() end
function HarvestMission:getHighestSellPointPrice() end
function HarvestMission:start() end
function HarvestMission:validate() end
function HarvestMission:getData() end
function HarvestMission:getFruitInVehicles() end
function HarvestMission:class() end
function HarvestMission:partitionCompletion() end
function HarvestMission:writeStream() end
function HarvestMission:saveToXMLFile() end
function HarvestMission:completeField() end
function HarvestMission:finish() end
function HarvestMission:getVehicleVariant() end
function HarvestMission:canRunOnField() end
function HarvestMission:updateRewardPerHa() end