TransportMission = {}

TransportMission.REWARD_PER_OBJECT = 200.000000
TransportMission.classId = 76.000000
TransportMission.REWARD_PER_METER = 0.200000
TransportMission.CONTRACT_DURATION = 115200000.000000
TransportMission.TEST_HEIGHT = 50.000000
TransportMission.CONTRACT_DURATION_VAR = 57600000.000000
TransportMission.className = 'TransportMission'
TransportMission.NUM_OBJECTS_PER_DRIVE = 5.000000

function TransportMission:getPickupTrigger() end
function TransportMission:new() end
function TransportMission:hasHotspots() end
function TransportMission:delete() end
function TransportMission:createHotspot() end
function TransportMission:getCompletion() end
function TransportMission:loadFromXMLFile() end
function TransportMission:init() end
function TransportMission:update() end
function TransportMission:objectLeftTrigger() end
function TransportMission:getTriggerInfo() end
function TransportMission:getDropoffTrigger() end
function TransportMission:destroyHotspots() end
function TransportMission:createHotspots() end
function TransportMission:updateTriggerVisibility() end
function TransportMission:calculateReward() end
function TransportMission:readStream() end
function TransportMission:getNPC() end
function TransportMission:isa() end
function TransportMission:createObject() end
function TransportMission:superClass() end
function TransportMission:canRun() end
function TransportMission:getData() end
function TransportMission:getTriggerTitle() end
function TransportMission:start() end
function TransportMission:objectEnteredTrigger() end
function TransportMission:collisionTestCallback() end
function TransportMission:isTriggerEmpty() end
function TransportMission:finish() end
function TransportMission:class() end
function TransportMission:copy() end
function TransportMission:dismiss() end
function TransportMission:writeStream() end
function TransportMission:saveToXMLFile() end
function TransportMission:loadObjects() end