User = {}

function User:setUniqueUserId() end
function User:setNickname() end
function User:getPlatformNodeId() end
function User:setIsMasterUser() end
function User:getPlatformIndex() end
function User:copy() end
function User:setId() end
function User:getConnection() end
function User:setLanguageIndex() end
function User:getPlayerStyle() end
function User:setFinancesVersionCounter() end
function User:setState() end
function User:readStream() end
function User:getFinancesVersionCounter() end
function User:isa() end
function User:getPlatformUserId() end
function User:superClass() end
function User:setPlayerStyle() end
function User:setFinanceUpdateSendTime() end
function User:getConnectedTime() end
function User:getFinanceUpdateSendTime() end
function User:new() end
function User:getId() end
function User:setPlatformIndex() end
function User:class() end
function User:setConnection() end
function User:getState() end
function User:writeStream() end
function User:getUniqueUserId() end
function User:getIsMasterUser() end
function User:getNickname() end
function User:setPlatformUserId() end
function User:setConnectedTime() end
function User:getLanguageIndex() end
function User:setPlatformNodeId() end