GreenhousePlaceable = {}

GreenhousePlaceable.classId = 38.000000
GreenhousePlaceable.className = 'GreenhousePlaceable'

function GreenhousePlaceable:finalizePlacement() end
function GreenhousePlaceable:readStream() end
function GreenhousePlaceable:setWaterTankFillLevel() end
function GreenhousePlaceable:isa() end
function GreenhousePlaceable:addFillLevelFromTool_OLD() end
function GreenhousePlaceable:delete() end
function GreenhousePlaceable:onWaterTankTrigger() end
function GreenhousePlaceable:superClass() end
function GreenhousePlaceable:removeWaterTrailer() end
function GreenhousePlaceable:loadFromXMLFile() end
function GreenhousePlaceable:addWaterTrailer() end
function GreenhousePlaceable:createNode() end
function GreenhousePlaceable:setManureFillLevel() end
function GreenhousePlaceable:getShowInfo() end
function GreenhousePlaceable:setIsWaterTankFilling() end
function GreenhousePlaceable:copy() end
function GreenhousePlaceable:getAllowFillTypeFromTool() end
function GreenhousePlaceable:class() end
function GreenhousePlaceable:writeUpdateStream() end
function GreenhousePlaceable:readUpdateStream() end
function GreenhousePlaceable:writeStream() end
function GreenhousePlaceable:load() end
function GreenhousePlaceable:saveToXMLFile() end
function GreenhousePlaceable:update() end
function GreenhousePlaceable:updateTick() end
function GreenhousePlaceable:hourChanged() end
function GreenhousePlaceable:new() end