TrainPlaceable = {}

TrainPlaceable.classId = 55.000000
TrainPlaceable.className = 'TrainPlaceable'

function TrainPlaceable:setIsTrainTabbable() end
function TrainPlaceable:new() end
function TrainPlaceable:getElectricitySplineLength() end
function TrainPlaceable:isa() end
function TrainPlaceable:onLoadFinished() end
function TrainPlaceable:getSplineLength() end
function TrainPlaceable:delete() end
function TrainPlaceable:onDeleteObject() end
function TrainPlaceable:superClass() end
function TrainPlaceable:load() end
function TrainPlaceable:loadFromXMLFile() end
function TrainPlaceable:removeSplinePositionUpdateListener() end
function TrainPlaceable:update() end
function TrainPlaceable:setSplineTime() end
function TrainPlaceable:updateTrainLength() end
function TrainPlaceable:readStream() end
function TrainPlaceable:copy() end
function TrainPlaceable:updateTrainPositionByLocomotiveSpeed() end
function TrainPlaceable:class() end
function TrainPlaceable:writeUpdateStream() end
function TrainPlaceable:readUpdateStream() end
function TrainPlaceable:writeStream() end
function TrainPlaceable:saveToXMLFile() end
function TrainPlaceable:addSplinePositionUpdateListener() end
function TrainPlaceable:getSplineTime() end
function TrainPlaceable:getElectricitySpline() end
function TrainPlaceable:setRequestedSplinePosition() end
function TrainPlaceable:updateTrainPositionByLocomotiveSplinePosition() end